### ISSUE TITLE
The predicted genome size is 450, and the size assembled by hifisam alone is consistent with the predicted size. Why is the size assembled with this software 570m?

### ISSUE THREAD

**Issue by xfcypeng** [marbl/verkko#100]
The predicted genome size is 450, and the size assembled by hifisam alone is consistent with the predicted size. Why is the size assembled with this software 570m?

**Comment by skoren** [comment]
Hifiasm has a built in purging step to remove alternate haplotypes while verkko does not. Verkko output is also phased unitigs while hifiasm outputs unphased contigs. I'd guess the extra sequence is remaining haplotype variation (usually on diploid genomes you get twice the genome size).

**Comment by xfcypeng** [comment]
I think this step of de hybridizing should be added to the kit. Obviously, the results I assembled were mixed with the heterozygous part, but the genomes of the two haplotypes were not completely assembled.

**Comment by skoren** [comment]
I'm not sure what you mean by de-hybridyzing. All outputs of verkko are completely phased and represent one haplotype. If you mean removing one haplotype (which is what hifiasm or tools like purge_dups are doing), we're not planning to add that. You can run purge_dups if you'd like. Verkko is designed for use cases where you have long-range phasing information (like Hi-C or trio or strand-seq) available in which case purging isn't needed, you get two complete haplotypes. Are you looking at the final assembly.fasta size or the gfa?

**Comment by skoren** [comment]
Idle
