### ISSUE TITLE
Assertion error in 5-untip

### ISSUE THREAD

**Issue by Day109** [marbl/verkko#104]
Hi,

I am getting this assertion error saying the length of the assembly is not matching:

# 5-untip/untip.err 

UntipRelative
Unitigify 3
Combine mappings
Combine edges
Find lengths
Fix coverage
Traceback (most recent call last):
  File "[/path/to/verkko/]scripts/get_origin
al_coverage.py", line 122, in <module>
    (path, overlaps) = get_leafs([">" + parts[1]], mapping, edge_overlaps, raw_node_lens, original_coverages)
  File "[/path/to/verkko/]scripts/get_origin
al_coverage.py", line 77, in get_leafs
    assert current_len == path_len
AssertionError

I have successfully run Verkko v1.1 for all of the samples I am working on but only one of them outputs this error.

Would there be any easy solution for this error?

**Comment by skoren** [comment]
Sorry for not replying earlier. I think this is the same root cause as #99. Can you try to update the `chop_misassemblies.py` script from this commit: b34fd095eb843169363e4beabf51feee32a5ad2f, remove the `4-processONT` folder and `5-untip` folders and re-start. That should fix the error.

**Comment by Day109** [comment]
Thank you for the solution, it resolved the error!
