### ISSUE TITLE
Difficulty running verkko

### ISSUE THREAD

**Issue by Jokendo-collab** [marbl/verkko#106]
I am gettong the following error and I am not sure how to go about it. Could you help because my `temp_analysis` folder is empty and it still failes.

```Launching bioconda verkko bioconda 1.1
Using snakemake 7.15.2.
Building DAG of jobs...
LockException:
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/scratch/oknjav001/postdocProjects/temp_analysis
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be rem
oved with the --unlock argument.```

**Comment by brianwalenz** [comment]
It's a snakemake feature to prevent running multiple copies of the workflow in the same directory.  Remove the hidden directory `.snakemake` in temp_analysis.

**Comment by Jokendo-collab** [comment]
@brianwalenz thanks for this update. I am running this pipeline on HPC environment and I want to use multi-threading to speed up then analysis. Will the following speed  up my analysis `--snakeopts "--cores 1000" --slurm --threads 40 --local-cpus 40` ?

**Comment by skoren** [comment]
The default run on an HPC environment will use multiple jobs and cores/job as appropriate. Local cpus don't matter if you're running on slurm, neither do the threads option. The cores 1000 should be equivalent to the defaults jobs of 1000. 

I expect the main limitation will be how many cores you can get allocated at a time not what you tell verkko to use (e.g. if you tell verkko to use 1000 cores but your grid only allocates you 100 at a time it doesn't help to increase the 1000 to 10000). If you see empty nodes on your cluster but verkko is not submitting additional jobs and reports it has them to run (e.g. in the parallel steps where it runs many jobs), you could increase the jobs option.

**Comment by Jokendo-collab** [comment]
@skoren Thank you.
