### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Jokendo-collab** [marbl/verkko#107]
I am getting an error when running verkko and I am not sure what the problem is. Could you have a look at the log file and advise. 
I did run the following code ```verkko -d analysis_results --hifi ./data/*.fastq.gz --snakeopts "--cores 1000" --slurm --cleanup  --no-nano --threads 40  --correct-k-mer-size 21```
[tout-4810442-stderr.log](https://github.com/marbl/verkko/files/9803682/tout-4810442-stderr.log)

**Comment by brianwalenz** [comment]
Paste in `analysis_results/0-correction/combineOverlapsConfigure.err`, please!

Also, check that `ovb-files` in the same directory has a list of around 30 *.ovb files and those files exist.

**Comment by Jokendo-collab** [comment]
`combineOverlapsConfigure.err` is empty

**Comment by Jokendo-collab** [comment]
There is nothing in that file.

**Comment by brianwalenz** [comment]
Look through the files in `overlap-jobs` - do the `*.err` files have errors?  They should end with with 'Bye.'.  This will tell us if the overlap job actually finished successfully.  Based on the times in the first log it looks like these jobs did _something_ - at least, they took around 30 minutes to finish.

The stats files should have non-zero values too.  Here's an example from ecoli:
```
 Kmer hits without olaps = 1219176
    Kmer hits with olaps = 196236
  Multiple overlaps/pair = 0
 Total overlaps produced = 196236
      Contained overlaps = 11503
       Dovetail overlaps = 184733
Rejected by short window = 0
 Rejected by long window = 0
```
`Kmer hits with olaps` of zero would explain the empty ovb files, though I've never ever seen that happen in real data.  Do all the stats files have nice large numbers for both the 'kmer hits' entries?

You've had verkko running before, right?

You could try rerunning this step by removing the overlap-jobs directory; not at all sure that will help.

**Comment by Jokendo-collab** [comment]
This is the first time I am running it on the real data but it's giving me these errors. I will try the above suggestion and get back to you.

**Comment by Jokendo-collab** [comment]
I did install `BMG`, `GraphAligner`, and `verkko` in one conda environment and when I activate my environment all the three software are there.  I have tried to test the installation but it is still failing. I am attaching the logfile for your attention. Could you have a look and let me know what could be going south. 
[2022-10-19T155925.037075.snakemake.log](https://github.com/marbl/verkko/files/9821192/2022-10-19T155925.037075.snakemake.log)

**Comment by skoren** [comment]
What is the input data you're running with (genome size, expected coverage, etc)?

Is the ovb file still empty? What's in the combineOverlapsConfigure.err log? Can you try running combineOverlapsConfigure.sh by hand and see what it reports.

**Comment by Jokendo-collab** [comment]
I am still running on:
```
curl -L https://obj.umiacs.umd.edu/sergek/shared/ecoli_hifi_subset24x.fastq.gz -o hifi.fastq.gz
curl -L https://obj.umiacs.umd.edu/sergek/shared/ecoli_ont_subset50x.fastq.gz -o ont.fastq.gz
```
with the default settings. I am attaching the ovb file for your attention.
[ovb.zip](https://github.com/marbl/verkko/files/9821261/ovb.zip)

**Comment by Jokendo-collab** [comment]
By running `combvineOverlapsConfigure.sh` manually I can see the following even after increasing the `--latency-wait` to one minute.

```Waiting at most 30 seconds for missing files.
Missing files after 30 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/cbio/users/javanokendo/postdoc_project/a_thaliana/.snakemake/tmp.2gcbeve8```

**Comment by skoren** [comment]
It reports that just going into the 0-correction folder and running `sh combineOverlapsConfigure.sh`. That script shouldn't have anything regarding snakemake, can you post the contents of combineOverlapsConfigure.sh?

**Comment by Jokendo-collab** [comment]
My ` 0-correction folder` has no `combineOverlapsConfigure.sh` script, it only has `configureOverlaps.sh`
![Screenshot (199)](https://user-images.githubusercontent.com/26459707/196726200-ba1bd672-02ed-4987-918e-0e6a300d3c6a.png)

**Comment by Jokendo-collab** [comment]
When I run the `configureOverlaps.sh` I get:
``Configuring overlap jobs.

Configuring for:
  hash table:      640000000 bases.
  read stream:   10000000000 bases.


       Raw          Raw  Corrected    Corrected    Trimmed      Trimmed
     Reads        Bases      Reads        Bases      Reads        Bases
---------- ------------ ---------- ------------ ---------- ------------
         0            0        230      3407490        230      3407490
         0            0        460      6801714        460      6801714
         0            0        690     10179581        690     10179581
         0            0        920     13549886        920     13549886
         0            0       1150     16927454       1150     16927454
         0            0       1380     20282638       1380     20282638
         0            0       1610     23655346       1610     23655346
         0            0       1840     27022812       1840     27022812
         0            0       2070     30344005       2070     30344005
         0            0       2300     33703775       2300     33703775
         0            0       2530     37078517       2530     37078517
         0            0       2760     40417715       2760     40417715
         0            0       2990     43783320       2990     43783320
         0            0       3220     47109611       3220     47109611
         0            0       3450     50466582       3450     50466582
         0            0       3680     53795908       3680     53795908
         0            0       3910     57147042       3910     57147042
         0            0       4140     60465891       4140     60465891
         0            0       4370     63775202       4370     63775202
         0            0       4600     67117090       4600     67117090
         0            0       4830     70459416       4830     70459416
         0            0       5060     73792002       5060     73792002
         0            0       5290     77120559       5290     77120559
         0            0       5520     80465498       5520     80465498
         0            0       5750     83786512       5750     83786512
         0            0       5980     87132347       5980     87132347
         0            0       6210     90485888       6210     90485888
         0            0       6440     93804462       6440     93804462
         0            0       6670     97191971       6670     97191971
         0            0       6900    100569062       6900    100569062
         0            0       7130    103939634       7130    103939634
         0            0       7360    107295117       7360    107295117
         0            0       7590    110636497       7590    110636497
         0            0       7820    113996028       7820    113996028
         0            0       8050    117363688       8050    117363688
         0            0       8280    120698057       8280    120698057
         0            0       8510    124084995       8510    124084995
         0            0       8740    127423765       8740    127423765
---------- ------------ ---------- ------------ ---------- ------------
         0            0       8943    130321243       8943    130321243

  Job       Hash Range        # Reads      # Bases      Stream Range        # Reads      # Bases
----- --------------------- --------- ------------  --------------------- --------- ------------
    1          1-8943            8943     96133454           1-8943            8943     96133454```
```

**Comment by skoren** [comment]
I think either your snakemake or verkko installation is broken. Snakemake reports that it was generating that shell script but seems to have failed to do so. 

What versions of snakemake and verkko do you have installed? 
You said earlier you were able to run something with this verkko install, was that without the --slurm option?

**Comment by Jokendo-collab** [comment]
They just suspended my HPC account on the server I was using saying I am no longer affiliated to the University of Cape Town. I will have to wait for access on Biowulf and start running my jobs from there. I hope this problem will be solved over there.

**Comment by brianwalenz** [comment]
That wasn't very nice of them!  I saw similar errors early in development of the verkko workflow, but none recently.  I somewhat understand what causes the error...but not why it is showing up for you on that system, let alone how to fix it.
