### ISSUE TITLE
Verkko with HiFi + Hi-C

### ISSUE THREAD

**Issue by larryns** [marbl/verkko#108]
Hi,

Is it possible to run Verkko without ONT, i.e. just HiFi + Hi-C? Is there a way to skip the GraphAlign phase? 

Thanks for any help,
Larry.

**Comment by brianwalenz** [comment]
It is possible to run without ONT; leave out --nano or explicitly include --no-nano.

**Comment by larryns** [comment]
Thanks very much, Brian. I appreciate it.

**Comment by larryns** [comment]
Thank you @skoren for the insight. You mean we'd have to tune rukki, right? Can you elaborate on what you mean by "diversity", please? Do you mean number of haplotypes, repeats, something else?

Thanks again.

**Comment by skoren** [comment]
How much the two haplotypes differ in the sample you sequenced.

**Comment by larryns** [comment]
Gotcha, thanks!
