### ISSUE TITLE
AssertionError  in  4-processONT/processONT.sh

### ISSUE THREAD

**Issue by ZhikunWu** [marbl/verkko#109]
Hi,

When we assemble the genome using ONT ultra-long (90X) and PacBio HiFi (60X) for a plant, an error happened in the process of  ”4-processONT“:

```
$ calculate_coverage.py ../2-processGraph/unitig-unrollfa < alns-ont-filter-trim.gaf > ../4-processONT/nodecovs-ont.csv 
Traceback (most recent call last):
  File "calculate_coverage.py", line 41, in <module>
    assert nodename in node_sizes
AssertionError
```

We then print the error nodename "gapont-2-len-3071-cov-58". It indeed exist in the file "alns-ont-filter-trim.gaf", but we cannot find the nodename in file "2-processGraph/unitig-unrollfa".  Maybe there is something wrong with the process of "2-processGraph". We want to know how to fix this.

Thanks!

**Comment by skoren** [comment]
What version of verkko are you using? This looks similar to an old bug #37 which should have been resolved by recent releases.

**Comment by ZhikunWu** [comment]
I use the version 1.0 beta in bioconda.
I will try it with the update version.
Thanks!

**Comment by skoren** [comment]
Any update, were you able to run with v1.2?

**Comment by ZhikunWu** [comment]
Yes, the task can be successfully completed after updating the version.  The assembly size is larger than excepted. And it cannot separate the two phases.  Maybe it mixed partial haplotypes in the assembly. I just added the PacBio HiFi and ONT data with default parameters.  I am not sure whether it is due to the parameters selected or the low heterozygosity (0.08%) of this inbred line.

The consensus results:
```
-rw-rw-r-- 1 651K Nov  8 20:14 buildPackages.err
-rwxrwxr-x 1  443 Nov  8 20:05 buildPackages.sh
-rw-rw-r-- 1   86 Nov  8 23:40 combineConsensus.err
-rw-rw-r-- 1  734 Nov  8 23:41 combineConsensus.out
-rwxrwxr-x 1 1.7K Nov  8 23:40 combineConsensus.sh
-rw-rw-r-- 1 1.2K Nov  8 19:58 extractONT.err
-rwxrwxr-x 1 2.3K Nov  8 19:57 extractONT.sh
-rw-rw-r-- 1 2.1K Nov  8 19:58 ont_subset.extract
-rw-rw-r-- 1  63M Nov  8 19:58 ont_subset.fasta.gz
-rw-rw-r-- 1  95K Nov  8 19:58 ont_subset.id
drwxrwxr-x 1 4.0K Nov  8 23:40 packages
-rw-rw-r-- 1    0 Nov  8 20:14 packages.finished
-rw-rw-r-- 1 125M Nov  8 20:10 packages.readName_to_ID.map
-rw-rw-r-- 1 221K Nov  8 20:14 packages.report
-rw-rw-r-- 1  72K Nov  8 20:14 packages.tigName_to_ID.map
-rw-rw-r-- 1    0 Nov  8 23:40 paths-haplotype1
-rw-rw-r-- 1    0 Nov  8 23:40 paths-haplotype2
-rw-rw-r-- 1  57K Nov  8 23:40 paths-unassigned
-rw-rw-r-- 1 581M Nov  8 23:41 unitig-popped.fasta
-rw-rw-r-- 1 140K Nov  9 08:15 unitig-popped.fasta.fai
-rw-rw-r-- 1    0 Nov  8 23:41 unitig-popped.haplotype1.fasta
-rw-rw-r-- 1    0 Nov  8 23:41 unitig-popped.haplotype2.fasta
-rw-rw-r-- 1  200 Nov  9 08:15 unitig-popped.stats.txt
-rw-rw-r-- 1 581M Nov  8 23:41 unitig-popped.unassigned.fasta


```

**Comment by skoren** [comment]
The assembly size would be larger than expected since it would provide phased outputs, verkko was not designed to output pseudo-haplotypes. Why do you think it cannot separate the two phases? The empty haplotype1/2 is the expected output when no long-range phasing information is given. You can use an independent tool (like purge_dups) to separate the assembly into the two bins.
