### ISSUE TITLE
How to skip HiFi correction step after first successfully verkko run

### ISSUE THREAD

**Issue by baozg** [marbl/verkko#110]
Hi, @skoren

We have tested different coverage UL read sets for the verkko run. How to skip HiFi correction step? I am not sure which file we can move. Would you mind adding a parameter to skip these? We have different batch UL reads to test, it's better to skip time consuming correction step first.

**Comment by brianwalenz** [comment]
```
% verkko
[...]
  ALGORITHM PARAMETERS:
    --no-correction          Do not perform Canu correction on the HiFi reads.
    --no-nano                Assemble without ONT data.
[...]
```
Alternatively, you can copy (or symlink) the corrected reads (`hifi-corrected.fasta.gz`) from the original run to the new run directory before starting verkko.
```
% mkdir newrun
% cp firstrun/hifi-corrected.fasta.gz newrun/
% verkko -d newrun [....] --hifi [original hifi reads]
```
(test on something small like our ecoli exampe first)

**Comment by baozg** [comment]
Hi,

I follow the suggestion, but the second run assembly size is much smaller than the first run. I believe it was caused by the consensus step. The MBG graph is stable in these two runs. Could you help me debugging this?


Here is the command I use (with E.coli test data)

```bash

verkko -d ./firstrun --hifi hifi.fastq.gz --nano ont.fastq.gz --base-k 2001 --window 500 --min-ont-length 5000 --local-memory 256 --local-cpus 128
ln -s firstrun/hifi-corrected.fasta.gz  ./
verkko -d ./newrun --no-correction --hifi hifi-corrected.fasta.gz --nano ont.fastq.gz --base-k 2001 --window 500 --min-ont-length 5000 --local-memory 256 --local-cpus 128
```

**Comment by baozg** [comment]
It seems that `Snakefiles/7-buildPackage.sm` use uncorrected reads for building packages. I try to replace that with uncorrected HiFi fastq, and the size was the same between these two runs.

**Comment by skoren** [comment]
Yes, I think the first option (using no correction and providing the corrected reads) is not correct. The corrected reads from the previous run are homopolymers compressed so if you use them as the only input you won't get an uncompressed consensus at the end. So the correct option:

```
verkko -d ./firstrun --hifi hifi.fastq.gz --nano ont.fastq.gz --base-k 2001 --window 500 --min-ont-length 5000 --local-memory 256 --local-cpus 128
mkdir newrun
cd newrun
ln -s ../firstrun/hifi-corrected.fasta.gz
cd ../
verkko -d ./newrun --hifi hifi.fastq.gz --nano ont.fastq.gz --base-k 2001 --window 500 --min-ont-length 5000 --local-memory 256 --local-cpus 128
```

**Comment by baozg** [comment]
Thank you for the response. Now it worked.
