### ISSUE TITLE
Connection between the graph and output contigs fasta

### ISSUE THREAD

**Issue by baozg** [marbl/verkko#111]
Hi, 

Since the change of unitig name in the verkko pipeline, how can I connect the sequence to the graph? I do see the number of clusters in the graph is close to my species' chromosome number, but the number of `assembly.fasta` large contigs is twice of chromosome number. How can connect graphs with sequences to find unresolved tangles?

**Comment by skoren** [comment]
There are two files which will give the translation. If you have trio/hic, you need both the `6-rukki/*.paths.tsv` file and the `6-*/*scfmap` files. If you only have HiFi + ONT, you only need to look at the `6-*/*scfmap` file.

**Comment by baozg** [comment]
Find it! Thank you for the quick response!

**Comment by baozg** [comment]
Hi, @skoren 

Do you have suggestions for parameter tuning with these issues? I am not sure which step should I dive into. 12 chromosomes with 30 >1Mb contigs, but the graph look perfect.

**Comment by skoren** [comment]
I'm not sure what issues you mean. The output contigs without long-range phasing information will be fully phased so any large homozygous regions will break them (but look connected in the graph). Is this what you're seeing? There is no option in verkko to output a pseudo-haplotype. You could manually make a path if you'd like and generate consensus for those. See issue #85 for some info.

**Comment by baozg** [comment]
No, all my species are inbreeding lines, so the complex tangle is not broken by the heterozygous bubble. Maybe I can share the graph and data with you. By manual inspection, I think the tangle could be resolved, that's why I open #102. After that time, we decide to add more coverage UL reads, I can share the new result with verkko 1.2


By the way, I ran the verkko HiFi correction with 1.1, is it fine to start these from `hifi-corrected.fasta.gz`? I am not sure verkko 1.2 have any update for correction.

**Comment by skoren** [comment]
Ah if it's that issue, then I already have access to the data, I'll respond on that issue.
