### ISSUE TITLE
Filter long contigs

### ISSUE THREAD

**Issue by skoren** [marbl/verkko#113]
Remove contigs shorter than a threshold at the end of assembly, probably <= 100kb as a default.

**Comment by brianwalenz** [comment]
Options.  I'm guessing the third is the correct one.

1)  Filter from just the fasta and leave everything else the same.  The filtered sequences probably need to be kept around somewhere so the graph can refer to them.  Easy to do but confusing for the user.

2)  Filter from everything, regardless of connection status in the graph.

3)  Filter from everything, but only if they're not connected in the graph.  This is not significantly harder than the previous.

4) ?

**Comment by brianwalenz** [comment]
In hg00423/beta_asm_faster_rukki:

There are 10 disconnected contigs at least 100 kbp:
```
 789614 bp from utig4-1200
8963359 bp from utig4-2087
 923381 bp from utig4-2086
 735822 bp from utig4-1508
4675956 bp from utig4-2197
4670330 bp from utig4-2201
2024153 bp from utig4-2176
 927329 bp from utig4-2065
 338881 bp from utig4-1294
 711270 bp from utig4-2070
```
There are 133 disconnected contigs less than 100 kbp.  A rough histogram of the lengths:
```
  1 @  1 kbp
  3 @  2 kbp
 14 @  3 kbp
  7 @  4 kbp
  4 @  5 kbp
  6 @  6 kbp
  2 @  7 kbp
  6 @  8 kbp
 11 @  9 kbp
  4 @ 10 kbp
  8 @ 11 kbp
 11 @ 12 kbp
 12 @ 13 kbp
  5 @ 14 kbp
  5 @ 15 kbp
  6 @ 16 kbp
  3 @ 17 kbp
  3 @ 18 kbp
  3 @ 19 kbp
  2 @ 20 kbp
  5 @ 21 kbp
  4 @ 23 kbp
  2 @ 26 kbp
  1 @ 27 kbp
  1 @ 28 kbp
  1 @ 29 kbp
  1 @ 33 kbp
  1 @ 62 kbp
  1 @ 99 kbp
```

**Comment by skoren** [comment]
Done
