### ISSUE TITLE
Rename haplotype files based on input

### ISSUE THREAD

**Issue by skoren** [marbl/verkko#114]
Rename haplotype1 and haplotype2 to be maternal/paternal (based on k-mer db names) for trio mode, leave as hap1/2 for HiC and remove them completely when they're empty and no haplotypes are walked. Promote the scfmap and paths.tsv files to top level since they're the only way to translate the final assembly to the graph nodes.

**Comment by brianwalenz** [comment]
I will decide mat/pat labels based on:
* extracting the name from a properly formatted merqury meryldb name (path/<haplotype>.k\d\d.hapmer.meryl)
* OR matching 'pat'/'mat' in the meryldb name
* OR leaving as haplotype1/haplotype2

I asked @snurk  to add an option to rukki so we can label the contigs in each file properly too.
