### ISSUE TITLE
Can we use verkko to assemble genome without ont read

### ISSUE THREAD

**Issue by landifeng** [marbl/verkko#118]
Hello,
Must there be ONT reads with verkko ?
I run verkko without ont reads, and a error showd.
"No Oxford Nanopore reads (-nano) supplied."
IS there any parameter ro run verkko without ont reads but only hifi reads ?

Another question : Did the order of the hifi files matters? Will the order influence the assemble result ?
For example, are these two commands got the same reasults ? "verkko -d verkko-result --hifi 1.fastq.gz 2.fastq.gz" and "verkko -d verkko-result --hifi 2.fastq.gz 1.fastq.gz"

Thank you.

Sincerely,
Landi

**Comment by skoren** [comment]
Yes you can run with just HiFi data but verkko isn't really optimized for that use case. Keep in mind that verkko also only outputs phased assemblies so, depending on your genome heterozygosity, the nodes may be quite small. On a human, they'd only be on the order of a few hundred kb. A haploid/very homozygous genome or a very heterozygous genome would give bigger nodes.

As for stability, order should not matter though verkko can have slight variations in the final consensus output and sizes.
