### ISSUE TITLE
AssertionError in v1.2

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#119]
Hi,
I encountered the below assertion error in Verkko v1.2 (with MBG v1.0.12) in a HG002 assembly that worked with v1.1

Since the Verkko run was interrupted several times caused by problems with the HPC, I am going to restart the whole thing, maybe it's just a hiccup coming from the infrastructure problems.

```
[...]
try resolve k=2615, replaced 95 nodes with 347 nodes, unitigified 592 nodes to 212 nodes
MBG: src/UnitigResolver.cpp:168: double ResolvableUnitigGraph::getCoverage(const std::vector<PathGroup>&, size_t) const: Assertion `precalcedUnitigCoverages[unitig] > 0' failed.
```

+Peter

**Comment by skoren** [comment]
You can also try the latest MBG as well to make sure it's not an MBG issue.

**Comment by ptrebert** [comment]
Thanks, I'll try that if it fails again over the Christmas break

**Comment by ptrebert** [comment]
A rerun from scratch did not result in the same error, so it must have been some corrupted file that was not properly recognized as such by Snakemake - problem solved.
