### ISSUE TITLE
Step 4-processONT went wrong when I added the ONT reads

### ISSUE THREAD

**Issue by JChenGatersleben** [marbl/verkko#127]
Dear marbl:

I am trying to verkko to assemble a genome (~580 Mb) using Pacbio+ONT reads. **If I just used the Pacbio reads, the assembly process will be smoothly finished**. But error occured when I tried to add both Pacbio and ONT reads. 

Question description:
I created an environment for verkko
conda activate verkko

run verkko
```
/home/chenj/anaconda3/envs/verkko/bin/verkko -d assembly \
--hifi test_pseudo_chrB_pacbio_reads.fq \
--nano chrB_ONTreads.fq \
--no-correction  --threads 2 \
--local-memory 50
```
Here is the error information, the last serval sentances:
```
chmod +x ./processONT.sh
./processONT.sh > ../4-processONT/processONT.err 2>&1      
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Removing output files of failed job processONT since they might be corrupted:
4-processONT/gaps-ont.gaf, 4-processONT/nodecovs-ont.csv
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-02-28T153817.117665.snakemake.log
```

the assembly pipeline stop at Step4, so I want to figure out what's going on there
Here is the information of processONT.err
```
Step 1a
Step 2a
inserted 0 gaps
inserted 0 gaps
inserted 0 gaps
Step 2b
Step 2c
Step 2d
Step 3a
awk: cmd. line:8: (FILENAME=- FNR=4) fatal: division by zero attempted
```
apparently the error happened at the Step 3a, so I check the file processONT.sh
```
echo Step 3a
awk '{ \
        if ($2 >= 100000) { \
          sum += $2 * $3; \
          count += $2; \
        } \
     }      END \
     { \
        print sum / count; \
     }' \
  < nodecovs-ont.csv
```

I found that the file nodecovs-ont.csv is missing in the folder 4-processONT
and the file nodecovs-ont.csv was generated through
```
echo Step 2c
 /home/chenj/anaconda3/envs/verkko/lib/verkko/scripts/calculate_coverage.py gapped-unitig-unrolled-hifi-resolved.gfa \
  < alns-ont-filter-trim.gaf \
  > ../4-processONT/nodecovs-ont.csv
```
And the input file alns-ont-filter-trim.gaf is empty.

Anyway, I guess the main problem is Step 4-processONT when I add the ONT reads.

Greetings
J.Chen

**Comment by skoren** [comment]
The file was likely removed by snakemake when the job failed. It seems you have no nodes over 100kb. What does the end of buildGraph.err report in the 1-buildGraph folder and how much HiFi coverage do you have? What is the contents of the 3-align folder (ls -la to get file sizes)?

Possibly related, I noticed you're also running w/o correction. This will impact the quality of the initial HiFi graph and so it may be less contiguous than it would be with correction and could lead to having no 100kb nodes.

**Comment by JChenGatersleben** [comment]
Dear skoren:

Many thanks for providing the solution!
I found the problem, yes, it is due to no nodes over 100kb. Since I only used small data for test run, so there is no nodes over 100kb. Now  I used all the data, it works.

Thank you again.
J.Chen

**Comment by JWJ13164328557** [comment]
Why does the 129GB duplex data still report this error after I added compression？
![image](https://github.com/user-attachments/assets/d35a14cb-09ae-4a23-b7dc-14985ca80379)
