### ISSUE TITLE
MBG: Assertion `seqOff < seq.size()' failed.

### ISSUE THREAD

**Issue by elenamesga** [marbl/verkko#128]
Hello,

I successfully ran verkko on Drosophila melanogaster sample but failed on Homo Sapiens (HG002 line). 

I got the following error:

MBG: src/HPCConsensus.cpp:15: addCounts(ConsensusMaker&, const SequenceCharType&, const SequenceLengthType&, const string&, size_t, size_t, size_t, size_t, size_t, bool)::<lambda(size_t)>: Assertion `seqOff < seq.size()' failed.
./buildGraph.sh: line 41:  4515 Aborted (core dumped) 

The file with the corrected reads is not empty and also I have tried changing the version of MBG. I run it in slurm. 

Could you give me some idea?

Thanks,

Elena.

**Comment by skoren** [comment]
Have you tried running with the latest MBG v1.0.14 release? If not, try to see if that fixes the error. Otherwise, can you share your input corrected reads (or the input reads you're using for HG002)?

**Comment by elenamesga** [comment]
Thank you very much for your response,

I have used the latest version (1.0.14) and also tested with the previous one (1.0.13). The raw readings are as follows: SRR10382244, SRR10382245, SRR10382248 and SRR10382249. I merged it into a file.

Thanks,

Elena.

**Comment by skoren** [comment]
That's one of our standard test sets so something must be off with the download. Did you download the raw data or SRA format followed by conversion? I think the latter may create duplicate read IDs which would cause errors in MBG (verkko v1.3 will stop on those immediately).

**Comment by skoren** [comment]
I've downloaded both the SRA files (via fastq-dump) and the raw fastq files for the four runs above and ran verkko v1.3.1 without error. Here are the file sizes post compression for both:
```
-rw-rw-r-- 1 korens Phillippy 21134264809 Nov  2  2019 m64011_190830_220126.fastq.gz
-rw-rw-r-- 1 korens Phillippy 20764212691 Nov  2  2019 m64011_190901_095311.fastq.gz
-rw-rw-r-- 1 korens Phillippy 22095090099 Nov  2  2019 m64012_190920_173625.fastq.gz
-rw-rw-r-- 1 korens Phillippy 22054011783 Nov  2  2019 m64012_190921_234837.fastq.gz

-rw-rw-r-- 1 korens Phillippy 20745102047 Mar  6 12:16 SRR10382244.fastq.gz
-rw-rw-r-- 1 korens Phillippy 21113350247 Mar  6 12:17 SRR10382245.fastq.gz
-rw-rw-r-- 1 korens Phillippy 22084544851 Mar  6 12:20 SRR10382248.fastq.gz
-rw-rw-r-- 1 korens Phillippy 22125126853 Mar  6 12:19 SRR10382249.fastq.gz
```

So I suspect something either went wrong with the download or run somewhere before MBG. Can you share the hifi-corrected.fasta.gz file (see https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you) and check it for duplicate IDs?

**Comment by elenamesga** [comment]
Hi, sorry for the delay but I re-downloaded the samples and ran the verkko again. It is still in progress. I am sharing the file with the corrected reads but the file is very large so it will take time.

Thanks,

Elena.

**Comment by elenamesga** [comment]
Hello,

I downloaded the samples again with:

`time prefetch --max-size 5000G $i`
`time fastq-dump --outdir $i --origfmt --gzip --split-files -I $i`

Where "i" es the id of the sample (e.g SRR10382248). I send you an imagen.

<img width="837" alt="Captura de pantalla 2023-03-10 a las 8 49 34" src="https://user-images.githubusercontent.com/36620713/224255412-8f407262-7f61-4353-b4b3-fc3c465c4b11.png">

Later, I used the previous command and I obtained the same error again. I don't understand the repeated reads, at least in Illumina each id is unique. Could you tell me how you have sent the work? Have you cleaned up the readings? 

Thanks,

Elena.

**Comment by elenamesga** [comment]
Finally, verkko worked using the raw fastq files: m64011_190830_220126, m64011_190901_095311, m64012_190920_173625 and m64012_190921_234837. However, I would like to know why it did not work with the other readings. 

Thanks,

Elena.

**Comment by skoren** [comment]
I think the issue is the --origfmt, when you do that here is what I get from two example IDs:
```
% fastq-dump SRR10382249 --origfmt --gzip --split-files -I
% fastq-dump SRR10382248 --origfmt --gzip --split-files -I

% zcat SRR10382248_1.fastq.gz |head -n 1
@1
% zcat SRR10382249_1.fastq.gz |head -n 1
@1
```

Vs if you leave that out:
```
% fastq-dump SRR10382249 --gzip --split-files -I
% fastq-dump SRR10382248 --gzip --split-files -I

% zcat SRR10382248_1.fastq.gz |head -n 1
@SRR10382248.1.1 1 length=16618
% zcat SRR10382249_1.fastq.gz |head -n 1
@SRR10382249.1.1 1 length=11997
```
Then you end up with lots of duplicated IDs. As I said, verkko v1.3.1 will check for this from the start and stop immediately rather than running. I confirmed this is the case w/the above bad data now that I knew how to reproduce it.

Fastq-dump seems completely broken for original IDs on this data as far as I see. I guarantee the originally submitted IDs weren't 1,2,3,...n. You could contact SRA to tell them about this issue.
