### ISSUE TITLE
Question about step 0-correction

### ISSUE THREAD

**Issue by magspho** [marbl/verkko#129]
Hello,
I have a question in your first reads error correction (EC) step `0-correction` which generates the `hifi-corrected.fasta.gz` file. I was wondering if you do EC on homopolymer-compressed (HPC) reads and then perform microsatellite compression on the corrected reads in the following step, or if you do EC on reads that are already both HPC'ed and microsatellite-compressed. Thank you!

**Comment by skoren** [comment]
The reads are only HPC and corrected. Microsatellite compression is only internal within MBG. All subsequent steps use only HPC.

**Comment by magspho** [comment]
I see. Thank you!
