### ISSUE TITLE
UnitigResolver MBG Issue

### ISSUE THREAD

**Issue by nickgladman** [marbl/verkko#130]
Hello. Thanks so much for providing this resource to the community! I'm doing a test run on some HiFi reads and discovered this in the buildGraph.err log:

```
MBG: src/UnitigResolver.cpp:707: std::pair<UnitigGraph, std::vector<ReadPath> > resolvableToUnitigs(const ResolvableUnitigGraph&, const std::vector<PathGroup>&, const std::vector<ReadPathInfo>&): Assertion `coverages[i][j] > 0' failed.
./buildGraph.sh: line 41: 3559810 Aborted                 (core dumped) /grid/ware/home/gladman/software/verkko/bin/MBG $iopt -t 4 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --hpc-variant-onecopy-coverage 25 --do-unsafe-guesswork-resolutions --out ../1-buildGraph/hifi-resolved.gfa
```

Not sure if this is like issue #67 or if something else needs to be done. I was directed the the buildGraph.err logs after checking the snakemake log--there was a `Error in rule buildGraph:` flag in the file.

verkko output file:
```
Launching bioconda verkko bioconda 1.2
Using snakemake 7.22.0.
```

**Comment by skoren** [comment]
Since your verkko and presumably MBG aren't the latest releases, I'd first try updating both to see if the error is resolved. You should be able to resume the old assembly with the new version once it's installed from conda.

**Comment by nickgladman** [comment]
Thanks. I thought I installed the newest version from Conda, but I was mistaken. Silly mistake.

**Comment by nickgladman** [comment]
Hello. I re-installed and re-ran but still ended up with the identical error.

Here are my versions for MBG and GraphAligner:

$ MBG --version
MBG bioconda 1.0.14
Version: bioconda 1.0.14

$ GraphAligner --version
GraphAligner bioconda 1.0.17-
GraphAligner bioconda 1.0.17-
Version bioconda 1.0.17-

$ output file:
Launching bioconda verkko bioconda 1.3.1
Using snakemake 7.24.0.

**Comment by skoren** [comment]
Can you share the hifi-corrected.fasta.gz file, see https://canu.readthedocs.io/en/latest/faq.html

**Comment by nickgladman** [comment]
Hello. Sorry for the delay. I have been trying to upload the files as instructed, but I am getting an error with my ftp permissions. As soon as I resolve that I'll let you know it's been pushed to the incoming/sergek directory.

**Comment by nickgladman** [comment]
Hello again. We resolved the ftp issue. The corrected reads should be in the `incoming/sergek` folder, labeled as `ng_hifi-corrected.fasta.gz`.

**Comment by skoren** [comment]
Yes, sorry for the silence, this dropped of my radar. I'm testing the latest MBG now since there have been some fixes since this time and will see if it still crashes and update this issue.

**Comment by skoren** [comment]
@maickrau this still seems to be crashing in the latest MBG, could you take a look. The reads are in the globus share under issue130.

**Comment by maickrau** [comment]
The most recent MBG commit should fix this

**Comment by nickgladman** [comment]
@maickrau would this be release 17 of MBG? Version 1.0.14 from February 2023?

**Comment by maickrau** [comment]
The most recent MBG commit, for example [b468b37](https://github.com/maickrau/MBG/commit/b468b370d8db34bde08e7776197434bf1af3bef3). It's not in a release yet so you have to compile it from source or wait for the next release.

**Comment by skoren** [comment]
I presume this is resolved? Re-open if not.
