### ISSUE TITLE
error in rule processONT

### ISSUE THREAD

**Issue by sigau** [marbl/verkko#133]
Hi
I was trying to make a assembly from ONT + Pacbio data using verkko and get a error at the rule processONT.
Do you know how I can correct this ?
Thanks 

Gautier

[processONT.err.txt](https://github.com/marbl/verkko/files/11177070/processONT.err.txt)
[verkko_assembly.e.txt](https://github.com/marbl/verkko/files/11177071/verkko_assembly.e.txt)
[verkko_assembly.out.txt](https://github.com/marbl/verkko/files/11177072/verkko_assembly.out.txt)

**Comment by skoren** [comment]
This might be the same as #99 (at least the crash is in the same step). Can you try updating the python from https://github.com/marbl/verkko/commit/fe83d29974d98363cc665bada715234f214aa25a (you can just replace the file in the conda install) and see if it runs.

**Comment by skoren** [comment]
Idle, I'd guess resolved by the fix in #99
