### ISSUE TITLE
Trouble with update in conda 

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/verkko#134]
I have verkko v1.2 installed via conda and tried to update to 1.3.1.
Received an error regarding "python=3.1".

--------------------------------------------------------------------------------
(verkko) [geoff@arsmsswa0s22012 ~]$ verkko --version
bioconda verkko bioconda 1.2
(verkko) [geoff@arsmsswa0s22012 ~]$ conda update -c conda-forge -c bioconda -c defaults verkko
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
------------------------------------------------------------------------------------

**Comment by skoren** [comment]
I'm not sure why conda is even looking for python 3.1 as verkko requests python >3.7: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/verkko/meta.yaml

I'd try making a new clean conda environment just for verkko and installing that way: `conda create -n verkko -c conda-forge -c bioconda -c defaults verkko`
