### ISSUE TITLE
Ultra-Long ONT reads

### ISSUE THREAD

**Issue by LeoVincenzi** [marbl/verkko#135]
Dear developers,
I am currently working on a plant genome assembly of expected genome size 550-600 Mbp using both PacBio HiFi and ONT sequencing data.
I was wondering about the correct length thresholds to filter my ONT reads. I tried to keep only reads longer than 100 kb, but in this way, I remain with only 15,000 reads and coverage of 3x.
I read in the paper you cited for _A.thaliana_ ([Wang, B. et al., 2021](https://doi.org/10.1016/j.gpb.2021.08.003)) that they considered 'ultra-long' the reads longer than 50 kb. With this filtering, I would keep more than 180,000 reads with a coverage of 22x.
In your opinion, how this can influence my final assembly? Should I apply some particular parameters to my command line since I'm using shorter ONT reads? 

Thank you in advance for your help.

**Comment by LeoVincenzi** [comment]
@skoren thank you very much for the clarification. 
On the other side, for the PacBio reads, we are using CCS HiFi reads, but we were considering also reprocessing the raw data with the novel tool DeepConsensus to reduce the read error. 
Do you have experience with it or with PacBio reads processed like that? Would you suggest using those different HiFi reads to improve the Verkko final result?

**Comment by skoren** [comment]
Yes, we typically try to re-process all our data w/DeepConsensus so I'd recommend running that if you're able.
