### ISSUE TITLE
Using phasing blocks generated by hifiasm+Hi-C

### ISSUE THREAD

**Issue by ritatam** [marbl/verkko#136]
Hello developers,

I've generated verkko assemblies for a diploid fungus using nanopore duplex as --hifi and ultralong simplex as --nano. 
I want to integrate Hi-C data, so I generated haplotype-phased assemblies using hifiasm + Hi-C as suggested by this [thread](https://github.com/marbl/verkko/issues/62). 

In the manual you wrote "make sure the phase blocks are chromosome-scale and consistent within each chromosome". So does that mean I'll need to scaffold these phased hifiasm haplotigs (with other Hi-C scaffolders?), extract haplotype-specific k-mers, then feed them to verkko? Could you please give me some suggestions? I'm new to genome assembly so not sure how to move on from there. 

Thank you!

Rita

**Comment by skoren** [comment]
That documentation is a bit outdated, we've been working on natively mapping Hi-C data to the verkko graph. We haven't integrated it into the pipeline yet but you can try an early version here: https://github.com/skoren/verkkohic. Run the `gfase_wrapper.sh` script. It also requires GFAse: https://github.com/rlorigro/GFAse. To run, you need to have a folder structure like this:
```
  unphased_verkkoasm
  hifi/<all fasta/q inputs for hifi>
  ont/<all fasta/q inputs for ont>
  hic/<all fasta/q inputs for hic>
``` 
and you run it as:
```
export VERKKO=<path to verkko-v1.3.1/>
export GFASE=<path to gfase>
bash gfase_wrapper.sh  unphased_verkkoasmasm gfase_verkkoasm `pwd`  
```

One caveat with this is we've done limited testing outside of human/primates so you may encounter issues which you can report on the verkkohic GitHub page. We should hopefully have an integrated version of Hi-C in the verkko pipeline within a month.

**Comment by ritatam** [comment]
@skoren Hi Sergey, many thanks for the pointers! I've given it a try.
Just had a brief look at the results, each haplotype seems to be much smaller than expected. I'll have a further look into this and report issues on verkkohic page as you said, if any.

Thank you!
Rita

**Comment by skoren** [comment]
OK, I'll close this issue here then.
