### ISSUE TITLE
How can I convert `homopolymer-compressed.gfa` to `uncompressed.gfa`

### ISSUE THREAD

**Issue by zhangrengang** [marbl/verkko#140]
Hi, I'd like to map the gfa to the assembly, but the sequences in the gfa file are homopolymer-compressed and are hard to map with minimap2. I can find most uncompressed sequences from `assembly.*fasta` to replace the homopolymer-compressed sequences in gfa, but there are some sequences not be found. How can I deal with it? Thank you!

**Comment by skoren** [comment]
Idle
