### ISSUE TITLE
random failures (can be reproduced with supplied test dataset)

### ISSUE THREAD

**Issue by dgordon562** [marbl/verkko#141]
My experience is that verkko will generally not succeed to completion in one run.  If I restart it (without changing anything), it usually succeeds with some of the steps that had failed in the earlier run, and then it will fail in a subsequent step.  Then I will restart it and it will usually succeed in what failed in the previous run...  I can continue this process until it completes.  The results are correct--they match other runs.  

For example, prepCoverage and buildPackages each exhibit this behavior.  They may fail and if the pipeline is restarted (so "attempts" is reset), and succeed in the next run.

I have observed this behavior in different datasets, including the E. coli K12 suggested.

Computers aren't supposed to behave like this (grin).  Could there be some non-deterministic failure?  I would be happy to gather more data if you can suggest what to collect.

**Comment by skoren** [comment]
We've seen some snakemake bugs making it think steps are complete or the pipeline is done when it's not. If possible, I'd first suggest updating snakemake to the latest release (if you don't already have it).

Both those steps should be deterministic, prepCoverage is essentially a cat of a bunch of outputs from previous steps. If it keeps failing intermittently, its would be useful to have the snakemake log along with the log from the step (e.g. `prepCoverage.err`) and the slurm logs (if you're on slurm) under `batch-scripts/*<stepName>*`.

**Comment by dgordon562** [comment]
Thanks, Serge!  I will follow your advice and report back.

**Comment by dgordon562** [comment]
Here is the latest run on E.coli.  Notice *which* rules fail also appears to be inconsistent since this time prepCoverage (for example) did not fail:

1st run:                                                                                            
succeeded: checkpoint splitONT:                                                                     
succeeded: rule buildStore:                                                                         
succeeded: checkpoint configureKmers:                                                               
succeeded: checkpoint configureKmers:                                                               
succeeded: rule computeKmers:                                                                       
succeeded: rule computeKmers:                                                                       
succeeded: rule countKmers:                                                                         
failed (twice) : rule computeOverlaps:                                                              
 
So restarted.                                                                                                   
2nd run:                                                                                            
succeeded: rule combineOverlapsConfigure:                                                           
succeeded: rule combineOverlaps:                                                                    
succeeded: rule combineOverlaps:                                                                    
failed (twice): rule computeErrors:                                                                 
                                                                                                    
3rd run:                                                                                            
                                                                                                    
(notice that it didn't try to run computeErrors again)                                              
succeeded: rule fixErrors:                                                                          
succeeded: rule buildGraph:                                                                         
succeeded: rule processGraph:                                                                       
succeeded: rule indexGraph:                                                                         
succeeded: rule alignONT:                                                                           
succeeded: rule combineONT:                                                                         
succeeded: rule combineONT:                                                                         
succeeded: rule processONT:                                                                         
succeeded: rule untip:                                                                              
succeeded: rule prepCoverage:                                                                       
succeeded: rule getCoverage:                                                                        
failed: extractONT                                                                                  
                                                                                                    
4th run:                                                                                            
succeeded: rule extractONT:                                                                         
succeeded: checkpoint buildPackages:                                                                
succeeded: rule generateConsensus:                                                                  
succeeded: rule combineConsensus:       
and completed.  I checked several of the final output files and they are identical to all of the other successful runs of
verkko on the test dataset.                                                      

I am using the version of snakemake from a week ago, but I do notice there are 2 more versions since then.  Neither of
2 more recent versions indicate anything that would make a difference, but if you twist my arm, I'll reproduce this problem 
with the most recent version.

I wonder if this is not a verkko problem and not a snakemake problem either, but a problem with the interface of

**Comment by dgordon562** [comment]
I'm close to solving this and will report back.  Don't spend any time on this yet...

**Comment by dgordon562** [comment]
Solved! 

 The problem is that verrko specifies:
verkko/lib/verkko/profiles/slurm-sge-status.sh 
to be:
sacct="sacct --format State"   
on line 35.  This will work for slurm clusters where there is only 1 cluster.  But if there are multiple clusters, such as ours,
it will not.  sacct only checks the cluster it is run on.  So it will not return success and snakemake will think the job has failed.
You can now see why the failures were random and not reproducible:  it simply depends on which cluster the scheduler assigns to each job.

The following fixed the problem:
sacct="sacct --allclusters --format State"

With this fix I've run E.coli 7 times in a row all with no errors, even though the jobs are sometimes scheduled on different clusters.

Anyone else with multiple clusters will have this same problem, I think.  So how about just adding the "--allclusters" to this script?  I think that will work even for those with a single cluster.

You can close this out after reading it.   

Thanks!!!
David

**Comment by skoren** [comment]
Thanks for your troubleshooting efforts. I agree, no reason not to always include allclusters, I confirmed it works w/o error on our cluster as well.

**Comment by dgordon562** [comment]
thanks, Sergey!
