### ISSUE TITLE
asm/verkko.yml

### ISSUE THREAD

**Issue by dgordon562** [marbl/verkko#142]
Hi, Serge,                                                                                          
Sorry to bother you again.  I've been digging into verkko to find                                   
where cluster resources are set.  I've found functions.sm which                                     
defines getTimeRequest but I've found that some time limits are not                                 
set by getTimeRequest but rather set by asm/verkko.yml which                                        
apparently is rewritten with each run of verkko.  Where are the                                     
values for asm/verkko.yml defined, please?                                                          
Thanks!                                                                                             
David

**Comment by brianwalenz** [comment]
verkko.yml is created by src/verkko.sh, and all defaults are set in there.  all should have command line options to override defaults; if any are missing, let me know!

**Comment by dgordon562** [comment]
thanks, Brian!

**Comment by dgordon562** [comment]
For those who read this and might be as confused as I was, it is not (as far as I can see) src/verkko.sh but rather bin/verkko (and not verkko.sh) that has the defaults for many of the jobs and that writes asm/verkko.yml    Do you disagree, Brian?

**Comment by brianwalenz** [comment]
I will not strongly disagree; they're the same file.  `src/verkko.sh` is the location in the source code while `bin/verkko` is the installed location.  If you're installing from conda or a pre-compiled distribution, then, yes, it's `bin/verkko`.  Sorry for the confusion!

**Comment by dgordon562** [comment]
Thanks for clarifying, Brian!  Closing this out...
