### ISSUE TITLE
MBG Assertion: `left.expandedReadPosStart < left.readLength' failed

### ISSUE THREAD

**Issue by astridvincze** [marbl/verkko#145]
Hello,
I'm trying to assemble using verkko running:

`nohup /opt/Miniconda23.3/bin/verkko -d assembly --hifi /mnt/data/astrid/my_assembly/fastq_final/duplex/* --nano /mnt/data/astrid/my_assembly/fastq_final/simplex/* --mbg /opt/Miniconda23.3/pkgs/mbg-1.0.14-hdcf5f25_2/bin/MBG --graphaligner /opt/Miniconda23.3/bin/GraphAligner --mashmap /opt/Miniconda23.3/bin/mashmap &`

but any time it stops giving me the following error:

`MBG: src/MBG.cpp:1410: sortPaths(std::vector<ReadPath>&)::<lambda(const ReadPath&, const ReadPath&)>: Assertion left.expandedReadPosStart < left.readLength' failed.`

my verkko version is 1.3.1

specifically:
my Python version is 3.10.11
my snakemake version is 7.25.4
my MBG version is 1.0.14
my GraphAligner version is 1.0.17
my mashmap version is 3.0.2

Any suggestion?

**Comment by skoren** [comment]
Are you able to try building and running the latest MBG from GitHub: https://github.com/maickrau/MBG. It has several fixes and might already address this. Should be a straight drop-in replacement for the MBG packaged with verkko v1.3.1. If not, would you be able to share your hifi-corrected.fasta.gz reads with us. The FAQ here: tells you how to upload them: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by astridvincze** [comment]
I run again the command from the same folder to see what error returns me. In 1-buildGraph in buildGraph.err there is the following output:

`Reading sequences from ../hifi-corrected.fasta.gz
MBG: src/ConsensusMaker.cpp:240: std::pair<std::vector<CompressedSequence>, StringIndex> ConsensusMaker::getSequences(): Assertion maxCount > 0' failed.
Aborted (core dumped)`

**Comment by astridvincze** [comment]
I'm sorry, but the assembly has encountered an error. I thought it would work, but instead, it gave me the following error:

"MBG: src/MBG.cpp:1410: sortPaths(std::vector<ReadPath>&)::<lambda(const ReadPath&, const ReadPath&)>: Assertion left.expandedReadPosStart < left.readLength' failed."

now I share with you my hifi-corrected.fasta.gz

**Comment by skoren** [comment]
@maickrau I put the data on globus under issue145.

**Comment by maickrau** [comment]
It still seems to be an older commit, and the input data ran on the newest commit. You can check the MBG version with `MBG --version` and the newest commit should print:

```Version: Branch master commit f312a8915eca046fcd80658633f3f72c74ed5ce4 2023-05-25 12:06:39 +0300```

You might need to recompile with `make clean` and then `make all`

**Comment by astridvincze** [comment]
I run the following steps:

```
git clone https://github.com/maickrau/verkko.git
cd verkko/src
git submodule init && git submodule update
make -j32
```

but there is a problem in installing things:
[make -j32.txt](https://github.com/marbl/verkko/files/11591828/make.-j32.txt)

**Comment by astridvincze** [comment]
Fine, I did what you told (make clean and then make all) and now when I digit 
`/opt/verkko/bin/verkko --version`
it returns me 
`verkko branch master commit 5fdc6af9244185815d904ac37bbdb23f35edeeb2 2023-05-16 15:29:59 -0400`

the fact is that if I go in conda enviroment when I ask for the version it gives me:
`verkko branch master commit 5fdc6af9244185815d904ac37bbdb23f35edeeb2 2023-05-16 15:29:59 -0400`
if I am in conda enviroment and I digit only `verkko --version`
it returns me
`bioconda verkko bioconda 1.3.1`

I tried to run verkko despite the fact that it is not as you wrote above but outside of conda enviroment needs some paths to be specified: 

```
Can't find 'scripts/get_layout_from_mbg.py' in directory VERKKO = '/opt/verkko/lib/verkko/'.
Can't find MBG executable in $PATH or $VERKKO/bin/MBG.
Can't find GraphAligner executable in $PATH or $VERKKO/bin/GraphAligner.
Can't find winnowmap executable in $PATH or $VERKKO/bin/winnowmap.
```

I specified 

```
--mbg /opt/Miniconda23.3/envs/verkko/bin/MBG 
--graphaligner /opt/Miniconda23.3/envs/verkko/bin/GraphAligner 
```

but still remain 

```
Can't find 'scripts/get_layout_from_mbg.py' in directory VERKKO = '/opt/verkko/lib/verkko/'.
Can't find winnowmap executable in $PATH or $VERKKO/bin/winnowmap.
```

I tried to figure out where these files should be, but I didn't succeed

**Comment by maickrau** [comment]
Could you try compiling MBG from source, and checking that it has the right version with `MBG --version`, and then use your previous Verkko installation and giving it the compiled MBG path as a parameter.
