### ISSUE TITLE
Error during buildGraph

### ISSUE THREAD

**Issue by caonetto** [marbl/verkko#146]
Hi,
I got the following error out
```
Reading sequences from ../hifi-corrected.fasta.gz
MBG: src/ConsensusMaker.cpp:240: std::pair<std::vector<CompressedSequence>, StringIndex> ConsensusMaker::getSequences(): Assertion `maxCount > 0' failed.
Aborted (core `dumped)
```
I have installed the conda version.

Thanks!

**Comment by skoren** [comment]
Could you try the latest MBG from the repo rather than the conda release and see if it still has an error?

**Comment by caonetto** [comment]
Thanks for your quick response. I am currently running the MBG conda version 1.0.14 which seems to be the latest version of MBG in the reppo. You think there is a specific issue with the conda version?

**Comment by skoren** [comment]
There have been fixes since the conda release (see for example #130) so before investigating further, I'd like to know if your crash is already fixed by one of those changes. You should be able to build the latest MBG from source and replace the binary in verkko as suggested in #130.

**Comment by acdarby** [comment]
I think I have the same or a similar issue no output from MBG. The initial install was conda but have replaced with the latest repo and check that version is the one been used. MBG seems to be running now - what is logged in the 1-buildGraph/buildGraph.err file?

**Comment by skoren** [comment]
The logging is just the rounds of simplification performed by MBG, it's not used by the pipeline in any way.

**Comment by skoren** [comment]
Fixed by latest MBG release
