### ISSUE TITLE
Weird scaffold name

### ISSUE THREAD

**Issue by chhylp123** [marbl/verkko#149]
I'm trying to assemble HPRC Y1 samples with verkko using the trio-binning solution as follows:

> verkko --local --local-memory 376 --local-cpus 64 -d verkko_asm --hifi hifi_*fastq.gz --nano ul*fastq.gz --hap-kmers maternal_compress.k30.only.meryl paternal_compress.k30.only.meryl trio &>>verkko.log

As verkko often failed during the last consensus step, I had to run it twice. The first round for the assembly from the scratch, and the second round for the consensus. After that I could get the following assemblies: 

>assembly.fasta/assembly.haplotype1.fasta/assembly.haplotype2.fasta/assembly.unassigned.fasta

These assemblies look good in terms most of metrics. However, I'm a little bit worrying about the names of contigs/scaffolds. The contig/scaffold names all have `compress` suffixes such as `maternal_compress-0000001`. Would you please let me know if it is expected or not? Thank you in advance.

**Comment by skoren** [comment]
The haplotype names are taken from your k-mer databases so that is the source of the compass in the name.

**Comment by chhylp123** [comment]
I see. Nice to see it works. Thanks a lot.
