### ISSUE TITLE
No permissions when running the last step of verkko

### ISSUE THREAD

**Issue by chhylp123** [marbl/verkko#151]
As my verkko failed during the last consensus step, I reran it with the exactly same command lines. The initial outputs are:

>Job stats:
job                 count    min threads    max threads
>----------------  -------  -------------  -------------
>combineConsensus        1              1              1
verkko                  1              1              1
total                   2              1              1
>----------------  -------  -------------  -------------

Unfortunately, it still failed with the following errors:
> cp: preserving permissions for ‘assembly.haplotype1.fasta’: Operation not supported

Although there is still no result, I found the final assemblies should produced as follows: 
>cp -p 7-consensus/unitig-popped.haplotype1.fasta   assembly.haplotype1.fasta
cp -p 7-consensus/unitig-popped.haplotype2.fasta   assembly.haplotype2.fasta
cp -p 7-consensus/unitig-popped.unassigned.fasta   assembly.unassigned.fasta

Can I directly use `7-consensus/unitig-popped.haplotype1.fasta`, `7-consensus/unitig-popped.haplotype2.fasta` and `7-consensus/unitig-popped.unassigned.fasta`? Thanks in advance.

**Comment by skoren** [comment]
It seems your version of cp doesn't support the -p flag. What environment are you running on? The -p option is used w/in the 7-consensus step as well so I'm surprised it failed on the last step but not there while copying files in the same way. If there was no error reported in `7-consensus/combineConsensus.err` then yes, it is OK  to copy those 3 files as the final output.

**Comment by chhylp123** [comment]
I see. I will use these three files first. I was running verkko locally with `CentOS Linux release 7.8.2003 (Core)`.

**Comment by skoren** [comment]
Fixed by removing -p which seems to cause issues on certain mount points.
