### ISSUE TITLE
Difference in early verkkohic vs current verkko Hi-C integration pipeline

### ISSUE THREAD

**Issue by ritatam** [marbl/verkko#154]
Hello developers,

I opened this thread #136 about using Hi-C to phase a fungal genome a while ago, and as Sergey suggested I tried the [early verkkohic](https://github.com/skoren/verkkohic). More specifically, I used `gfase_wrapper.sh` on the unphased verkko assembly. The results turned out well - most of the chromosome-level scaffolds could be assigned to haplotypes. Now that the newest verkko allows direct Hi-C integration, I tried another run from the very beginning, but this time only two small scaffolds could be phased. 

Is there a fundamental difference in how Hi-C data is handled between those two versions? In the early verkkohic version the manual says "It runs hi-c scaffolding pipeline over the preexisting previous verkko", would it be different this time hence different results? I'm still new to genome assembly and will really appreciate it if you could provide some guidance.

Thank you very much!

**Comment by Dmitry-Antipov** [comment]
Hi,
gfase_wrapper used different method, but there should not be such a difference with results, so likely something went wrong. Can you share verkko's log (can be found in <run_folder>/.snakemake/log/ subfolder ) and phasing core logs (<run_folder>/8-hicPipeline/hicverkko.log and <run_folder>/8-hicPipeline/hic_phasing.err)?

**Comment by ritatam** [comment]
Yes sure, much appreciated!

Verkko's snakemake log:
- [2023-06-10T042439.033322.snakemake.log](https://github.com/marbl/verkko/files/11713052/2023-06-10T042439.033322.snakemake.log) The error at the end came from mergeBWA.sh's  `samtools merge` due to the older samtools version I used. I removed the -o flag and it worked (the next log file).
- [2023-06-10T154418.374742.snakemake.log](https://github.com/marbl/verkko/files/11713053/2023-06-10T154418.374742.snakemake.log)
- I also included the one in 8-hicPipeline/final_contigs/.snakemake/log:
[2023-06-10T160919.190045.snakemake.log](https://github.com/marbl/verkko/files/11713068/2023-06-10T160919.190045.snakemake.log)
- 8-hicPipeline/[hicverkko.log](https://github.com/marbl/verkko/files/11713056/hicverkko.log)
- 8-hicPipeline/[hic_phasing.err](https://github.com/marbl/verkko/files/11713057/hic_phasing.err.txt)

Sorry it's a bit messy!

**Comment by Dmitry-Antipov** [comment]
Thank you for sharing everything, (and for reminding me that -o is not supported by old samtools merge - fixed that)

Looks like something is not right with the graph, can you also share <run_folder>/assembly.homopolymer-compressed.noseq.gfa  for both new and old runs?

**Comment by ritatam** [comment]
There you go: [assembly.homopolymer-compressed.noseq.gfa.zip](https://github.com/marbl/verkko/files/11732253/assembly.homopolymer-compressed.noseq.gfa.zip) 
I'll be checking the Hi-C heatmap for the older run this week.

**Comment by Dmitry-Antipov** [comment]
Thank you!

Well, the graphs are quite similar. They are really disconnected but the coverage is high. Do you expect to see something like 16 chromosome pairs for that species? or it is just coverage gaps?

Looking on the graph, I'd suggest that majority of chromosomes are already assembled, and haplotypes are significantly more divergent than in human - currently we have no chance to see homology between sequences with less than 95% IDY. I'll add expected haplotype divergence to verkkohic's options but actually if it is the real issue you can "phase" assembled scaffolds into pairs of homologous chromosomes without using hi-c at all, using just sequence similarity.
![disconnected_fungi](https://github.com/marbl/verkko/assets/995834/23d3a119-5710-43d5-bad8-1051a136fbba)

**Comment by ritatam** [comment]
Thank you for looking into this. That makes sense.

Based on preliminary analysis I believe at least 15 out of 18 chromosome pairs were fully assembled without Hi-C. And yes, this species is known to have high haplotype divergence. I'm exploring ways to scaffold the rest with Hi-C & the other haplotype that is chromosome-level. For now I'd say the initial assembly is already looking pretty good, but I'll need to check how it's phased to avoid errors propagating down the process. 

Was just wondering why the (seemingly) different behaviours between the two Hi-C integration pipelines, and reckoned I should point it out. Considering this is still in early development, maybe it's best to wait for a release. 

Also thanks for considering adding the new feature! I'm sure it'll be very useful to some. :)

**Comment by Dmitry-Antipov** [comment]
Thank you for being our beta tester and for helpful feedback:)
