### ISSUE TITLE
verkko HIC version installation issues

### ISSUE THREAD

**Issue by HMPNK** [marbl/verkko#155]
Hi,

I could successfully install the HIC version of VERKKO on an older ubuntu 18 server, doing this:

```

> conda create --name=newVerkko -c conda-forge -c bioconda -c defaults -c anaconda python rust cxx-compiler libcantera-devel numpy samtools bwa verkko mashmap winnowmap networkx
> git clone https://github.com/maickrau/verkko.git
> cd verkko/src
> git submodule init && git submodule update
> make -j32
> 
> make sure not to use the verkko bin provided by the conda environment, but use the one in verkko/bin/verkko

```

Now I have got stuck here in the late phase of the pipeline:

> cat hic_phasing.err
> Loaded a graph with 9272 nodes and 11225 edges avg degree 2.421268 and stdev 1.201565 max is 8.429093
> Found an rDNA huge component of 1325 edges
> Removed 11 short nodes components and 2068 short nodes. New number of nodes 7204
> Median coverage is 15.8
> Loaded match info with 1342 nodes and 1199 edges
> Constant for neighbouring edges set to be  283324, for homologous edges -2833240
> Loaded hic info with 4936 nodes and 1645317 edges
> Distances counted
> Traceback (most recent call last):
>   File "/data2/verkko/lib/verkko/scripts/hicverkko.py", line 42, in <module>
>     cluster.run_clustering(noseq_gfa, matches_file, hic_file, output_dir)
>   File "/data2/verkko/lib/verkko/scripts/cluster.py", line 582, in run_clustering
>     fixUnbalanced(best_part, C, G)
>   File "/data2/verkko/lib/verkko/scripts/cluster.py", line 149, in fixUnbalanced
>     part[1 - ind].append(node)
>     ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'set' object has no attribute 'append'

Any ideas how to make it run further?

**Comment by HMPNK** [comment]
Strange...

I just restartet the pipeline and now it runs through that step where it crashed before:

> Loaded a graph with 9272 nodes and 11225 edges avg degree 2.421268 and stdev 1.201565 max is 8.429093
> Found an rDNA huge component of 1325 edges
> Removed 11 short nodes components and 2068 short nodes. New number of nodes 7204
> Median coverage is 15.8
> Loaded match info with 1342 nodes and 1199 edges
> Constant for neighbouring edges set to be  283324, for homologous edges -2833240
> Loaded hic info with 4936 nodes and 1645317 edges
> Distances counted
> Not adding homology information between utig4-5244 and utig4-5242 - neighbouring looplike something
> Not adding homology information between utig4-5242 and utig4-5244 - neighbouring looplike something
> Not adding homology information between utig4-9154 and utig4-9155 - neighbouring looplike something
> Not adding homology information between utig4-5793 and utig4-5794 - neighbouring looplike something
> Not adding homology information between utig4-3652 and utig4-2246 - neighbouring looplike something

Hope this helps

**Comment by HMPNK** [comment]
Just another question, how can I configure concurrency of "utgcns", in the "final_contigs" phase, this started running 8 jobs in parallel, but now dropped to 4 jobs. My server would have enough RAM and CPU to do 12 jobs with 8 threads in parallel.
I would like to configure it to 48 jobs with 2 threads, Is thta possible?

**Comment by skoren** [comment]
I think the code in question on line 149 should be using .add not .append as the kernighan lin function returns sets.

As for the utgcns, the memory it uses is dynamic per job, depending on the contig sizes so it may only be able to fit 4 jobs now given the memory snakemake is restricted to use (64 by default). You could increase the memory it is allowed to use via `--local-memory XX --local-cpus YY` and you could restrict each individual consensus job to 2 cores via `--cns-run 2 0 48`.

**Comment by Dmitry-Antipov** [comment]
Hi,
As @skoren  wrote, the original crash was a clear syntax error that we fixed. However, I'm interested in investigating reasons of nondeterministic behavior - did not expect that. 
Could you share with us some data required to debug? We need 
<run_folder>/8-hicPipeline/unitigs.hpc.noseq.gfa
<run_folder>/8-hicPipeline/hic.byread.compressed
<run_folder>/8-hicPipeline/unitigs.matches

**Comment by skoren** [comment]
Idle, no response and haven't seen non-deterministic behavior in our local re-runs so closing for now. Re-open if we encounter non-deterministic behavior again.
