### ISSUE TITLE
MBG: src/UnitigResolver.cpp core dumped error

### ISSUE THREAD

**Issue by nirvana693** [marbl/verkko#158]
Hello,

Thank you for such a wonderful tool. I am testing HiFi only (`--no-nano --no-correction` options) assembly using 5x of human data and encountered following core dump error at 1st step:
```
MBG: src/UnitigResolver.cpp:711: std::pair<UnitigGraph, std::vector<ReadPath> > resolvableToUnitigs(const ResolvableUnitigGraph&, const std::vector<PathGroup>&, const std::vector<ReadPathInfo>&): Assertion `coverages[i][j] > 0' failed.
Aborted (core dumped)
```
This is similar to the previous error [130](https://github.com/marbl/verkko/issues/130). I have updated the MBG to latest version
```
GraphAligner bioconda 1.0.17-
GraphAligner bioconda 1.0.17-
Version bioconda 1.0.17-
MBG bioconda 1.0.15
Version: bioconda 1.0.15
bioconda verkko bioconda 1.2
snakemake 7.28.3
```
here is the full log file.
[buildGraph_err.txt](https://github.com/marbl/verkko/files/11813593/buildGraph_err.txt)

**Comment by maickrau** [comment]
Could you share `hifi-corrected.fasta.gz`? See instructions on https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by nirvana693** [comment]
There was no `hifi-corrected.fasta.gz`, so I have uploaded the input file used (`5x_hifi.fq.gz`). Thank you

**Comment by nirvana693** [comment]
@skoren  Agreed on what you have mentioned. The test was to see if Verkko successfully works with only HiFi or Duplex dataset without any additional dataset (ULONT or HiC). For such test, what would be the minimum coverage?  Thank you.

**Comment by skoren** [comment]
We recommend 20x/haplotype which would be 40x total but 30x+ would be the minimum I'd recommend using. 

Verkko isn't really designed to work on HiFi only data though, it will not output pseudo-haplotypes so the contigs would be quite short since HiFi data is usually too short to phase over long distances (at least for human samples). Duplex-only data works better since it's longer but in this case I'd also recommend including the simplex data that did not get converted to duplex as the ONT reads.

**Comment by nirvana693** [comment]
@skoren Thank you. 

_>>Duplex-only data works better since it's longer but in this case I'd also recommend including the simplex data that did not get converted to duplex as the ONT reads._

Do you mean-- Merge both Duplex and Simplex reads, use merged reads as an input to `--hifi` or
use Duplex reads as input to `--hifi` and filter all simplex reads >=50kb or 100kb and use them along with ULONT as `--nano`

**Comment by skoren** [comment]
All the duplex data as HiFi and all the simplex and duplex (over a basic length like 5kb) as nano.

**Comment by skoren** [comment]
Idle, initial error was due to very low input coverage in HiFI data.
