### ISSUE TITLE
Compliation Error 1

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [marbl/verkko#160]
Trying to compile on CentOS:

make: *** [Makefile:829: /g/data/nm31/bin/verkko/src/build/obj/lib/libverkko.a/utility/src/align/align-parasail-driver.o] Error 1
[make.err.txt](https://github.com/marbl/verkko/files/11889012/make.err.txt)

**Comment by brianwalenz** [comment]
Use gcc9.

gcc8 doesn't appear to support qualified inline namespaces (some discussion at https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4230.html).  The error, for posterity:
```
In file included from utility/src/kmers.H:31,
                 from utility/src/kmers-v1/kmers-exact.C:23:
utility/src/kmers-v1/kmers-tiny.H:29:22: error: namespace name required before ‘inline’
 namespace merylutil::inline kmers::v1 {
                      ^~~~~~
utility/src/kmers-v1/kmers-tiny.H:29:22: error: expected ‘{’ before ‘inline’
utility/src/kmers-v1/kmers-tiny.H:29:29: error: ‘kmers’ does not name a type
 namespace merylutil::inline kmers::v1 {
                             ^~~~~
```

**Comment by theo-allnutt-bioinformatics** [comment]
[make.err.txt](https://github.com/marbl/verkko/files/11889656/make.err.txt)
Do not have gcc9 on HPC system.. tried 10.3 and got:
  = note: cc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found
          compilation terminated.


error: could not compile `proc-macro2` due to previous error
make: *** [Makefile:899: rukki/target/release/rukki] Error 101

**Comment by brianwalenz** [comment]
That's a little more mysterious.  https://stackoverflow.com/a/73516022 mentions a similar occurrence, https://users.rust-lang.org/t/cross-compilation-issue-with-yocto-meta-rust/91670; both suggest that 'cargo' (the rust compiler) is using an unexpected version of 'cc'.

I think verkko compiled, except for the rust-based 'rukki' module.  Possibly a 'rust' environment exists that needs to be loaded, or possibly gcc10 is interfering with cargo.  See if unloading gcc10 and switching back to gcc8 will work.  You can build just 'rukki' with:
```
% cd src/
% cargo build --release --manifest-path rukki/Cargo.toml
% cp -p rukki/target/release/rukki ../lib/verkko/bin/rukki
```
If the rest of verkko is installed and you don't have haplotype kmers (--hap-kmers option) or Hi-C (--hic1/--hic2 options) you don't need rukki.  Give the test case at the bottom of https://github.com/marbl/verkko a try.

This is definitely something I can't fix in verkko (or rukki) and you should probably contact the HPC staff.

**Comment by theo-allnutt-bioinformatics** [comment]
ok, got help info, But seems like MBG won't install either.. have raised issue there, but I think this is going in circles.. will use something else. thanks anyway. Will close this.

**Comment by skoren** [comment]
You can install verkko using conda so you don't have to compile it.
