### ISSUE TITLE
The efficiency of the software operation is very low

### ISSUE THREAD

**Issue by xfcypeng** [marbl/verkko#161]
The efficiency of the software operation is very low. The 400M genome has been running for nearly 6 days, and it is not known how long it will take to complete the operation.

**Comment by skoren** [comment]
A typical run a human HiFi + ONT genome requires about 5-10k cpu hours or a couple of days on a 64-core machine. So 6 days for a smaller genome is unusual. However, there's no information in your issue to provide any advice. For example, version of verkko, exact command used, coverage input, any logs indicating what it has run so far.

**Comment by skoren** [comment]
Idle, no information to troubleshoot to track down slowness supplied.
