### ISSUE TITLE
v1.4: assertionerror in create layout

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#165]
Hi,

I have one v1.4 run with the following assertion failing:

```
>>> file: createLayout.err
>>> layout error
Traceback (most recent call last):
  File "[...]/lib/verkko/scripts/get_layout_from_mbg.py", line 216, in <module>
    assert parts[0] not in node_mapping
AssertionError
```

I can share the Verkko run directory for debugging purposes, but only via Globus (push or pull).

Best,
Peter

**Comment by ptrebert** [comment]
Subfolders 2- 4- 5- transferring for two failed runs via Globus

**Comment by skoren** [comment]
I think this upload is accidentally a duplicate of #163? The counts of nodes/etc is the same in both assemblies here as the ones from the other issue. Could you double-check the upload and also include the 6-* folder if it exists in these runs?

**Comment by skoren** [comment]
Confirmed, this is the same issue as #163 so that bug fix should address this as well.

**Comment by ptrebert** [comment]
Thanks, I will check that sample as well

**Comment by ptrebert** [comment]
confirmed fixed via 3119b39

Thanks

**Comment by ptrebert** [comment]
Reopen for more debugging. I just realized that the fix did not lead to a successful run, just that no error exit code was produced at the end and the `&& touch checkfile` was thus triggered. I am going to delete some more subfolders in the Verkko run directory to check if a more substantial restart solves the issue.

**Comment by ptrebert** [comment]
I deleted all subfolders from 5- onward, and now the run completed, creating all expected output files. So, the fix should still be valid.
