### ISSUE TITLE
The assembled genome is huge

### ISSUE THREAD

**Issue by zhangkaihui1** [marbl/verkko#167]
The genome size of the species I studied was about 54M, assembled using pacbio HIFI data and ONT data, and the results showed less than 213M, with the following command verkko -d./ --hifi --nano --threads. How can I solve this problem?

**Comment by zhangkaihui1** [comment]
The species I study are haploid, 50% repetitive sequences. Coverage cannot be viewed because there is no reference genome. According to your opinion, I used the ONT and hifi data after pollution removal, and the genome size was 160M. What parameters to set or how to get rid of the excess about double the sequence. Second, how do you remove the redundant sequence in plastid genomes (like mitochondria or chloroplast) after removing the redundant sequence?

**Comment by skoren** [comment]
If the genome is indeed haploid the size should be closer to 54mb rather than the 100mb (e.g. diploid) and so there shouldn't be much redundancy to remove. Are you able to share the `assembly.homopolymer-compressed.noseq.gfa` file for the assembly? That should give some idea of where most of the sequence is coming from.

**Comment by zhangkaihui1** [comment]
Can I have your email? I don't know how to upload files on githup

**Comment by brianwalenz** [comment]
You can drag-and-drop files to attach them to the issue, or click on the text "attach files by dragging & dropping, selecting or pasting them" text at the bottom of the box where you enter comments to select files for upload.

If it is too large you can also upload to us following directions at https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you
