### ISSUE TITLE
Clarification needed for some sequencing data listed in paper/README.md

### ISSUE THREAD

**Issue by LYC-vio** [marbl/verkko#168]
Dear Authors,

Thank you for developing this wonderful tool and providing a very detailed list of the reads data involved in the published paper. However, I found that it's hard to identify the exact files used in some of the links listed in paper/README.md.

To be more specific:
> * HG002 105x HiFi:
>   * https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=
>     * m54329U_201103_231616.ccs.fastq.gz
>     * m64004_210224_230828.hifi_reads.fastq.gz
>     * m64011_190830_220126.Q20.fastq.gz
>     * m64011_190901_095311.Q20.fastq.gz
>     * m64012_190920_173625.fastq.gz
>     * m64012_190921_234837.fastq.gz
>     * m64014_210227_165255.hifi_reads.fastq.gz
>     * m64015e_210223_010616.hifi_reads.fastq.gz
>     * m64015e_210224_100310.hifi_reads.fastq.gz
>     * m64076_201013_225902.ccs.fastq.gz
>     * m64076_201016_191536.ccs.fastq.gz
>     * m64076_210310_104300.hifi_reads.fastq.gz

Some of these individual fastq files (especially those with "e" or "U") are hard to find under https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=, which seems to be the root dir of the whole database. I've tried to add the file name after "prefix=", but that didn't work.

> * HG002 85x ONT UL:
>   * https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=NHGRI_UCSC_panel/HG002/nanopore/Guppy_4.2.2/

Seems that there are multiple sets of reads under this dir (from MinION and PromethION), and I'm not sure which files that the readme refers to, or all of them should be merged and used together.

I've read through the HPRC's GitHub repo and their website, but still didn't find a clear instruction for those relatively new reads data. I'll highly appreciated it if you could give some further clarification for these two data sources listed above.

Thank you for your time and efforts

**Comment by skoren** [comment]
For the ONT full coverage dataset, you want to use all the available libraries there, including minion and promethion. For the HiFi, yes unfortunately this data wasn't generated/uploaded by us so it's a bit scattered. There's a more direct list in the supplement of the Y paper here: https://www.biorxiv.org/content/10.1101/2022.12.01.518724v1.supplementary-material (Supplementary Table 1). 

However, unless you're trying to exactly match the paper results, I'd just use the Revio dataset released by pacbio instead: https://downloads.pacbcloud.com/public/revio/2022Q4/?utm_source=Website&utm_medium=webpage&utm_term=HomoSapiens-GIAB-trio-HG002-4&utm_content=datasets&utm_campaign=0000-Website-Leads. That should get you up to 90x total.

**Comment by LYC-vio** [comment]
Thank you! It helps alot
