### ISSUE TITLE
v1.4 segfault consensus

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#174]
Hi,
I have a single case of a segfault in the consensus phase:

```
  21699 Failed with 'Aborted'; backtrace (libbacktrace):
  21700  - ALIGNED 0.0238 at    133292-142920   
  21701 ERROR:  alignment from 133293 to 142920, but tiglen is only 132087
  21702 utgcns: utgcns/unitigConsensus.C:867: bool alignEdLib(dagAlignment&, tgPosition&, char*, uint32, char*, uint32, double, bool): Assertion `aln.end <= tiglen' failed.
  21703 
  21704 Failed with 'Aborted'; backtrace (libbacktrace):
  21705 
  21706 Failed with 'Segmentation fault'; backtrace (libbacktrace):
  21707 ./packages/part026.sh: line 19: 135788 Segmentation fault      /[...]/verkko/wd/.snakemake/conda/c410c39ac1cf6bea6ae75
  21707 0999a5ce20f_/lib/verkko/bin/utgcns -V -V -V -threads 8 -import ../7-consensus/packages/part026.cnspack -A ../7-consensus/packages/part026.fasta.WORKING -C 2 -norealign -max
  21707 coverage 50 -e 0.05 -em 0.20 -EM 0 -l 3000 -edlib
  21708 
  21709 Consensus did not finish successfully, exit code 0.
```

It's v1.4 plus two bug fixes (3119b39 and 4f6a54e). As a side note, the overall run was registered by Snakemake as having failed, despite the weird `did not finish successfully, exit code 0.`

Best,
Peter

**Comment by brianwalenz** [comment]
> ERROR:  alignment from 133293 to 142920, but tiglen is only 132087

It didn't just align incorrectly, it aligned to sequence that doesn't even exist.  Neat trick, that!

Can you upload 7-consensus/packages/part026.cnspack so I can debug?

**Comment by ptrebert** [comment]
I can, but immediately only via Globus (same as for my other tickets). Does that work as well?

**Comment by skoren** [comment]
To confirm, is this a Hi-C (or any non-trio) run? I think it might be related to b5d87b0ecc4f29ac24e2c87d89241e1f39203ca7 where we didn't tell consensus which reads are ONT in that case, leading to slower and potentially worse consensus. Can you see how many ONT reads you have in this case being used for consensus, there should be a `ont_subset.id` file in one of the 7-consensus folders.

**Comment by ptrebert** [comment]
Ok. Does that bug also affect the consensus in case of an unphased assembly run (no trio, no phasing paths)?

**Comment by skoren** [comment]
No, only those that use the --paths option.

**Comment by ptrebert** [comment]
P.S.: any plans for a v1.4 bugfix release yet?

**Comment by skoren** [comment]
Yeah we plan to have one this month, I was waiting to see if #173 can also be fixed.
