### ISSUE TITLE
one of the commands exited with non-zero exit code

### ISSUE THREAD

**Issue by shiyi-pan** [marbl/verkko#175]
Hi, I run the verkko with HiFi and ONT data, but mat an error. Here is part of my logs:

```
cd 4-processONT

cat > ./processONT.sh <<EOF
#!/bin/sh
set -e

echo Step 1a
......................
......................
#FIXME parameterize
#
echo ""
echo Step 16
 /gss1/home/verkko/lib/verkko/scripts/resolve_triplets_kmerify.py \\
  normal-connected.gfa \\
  fake-ont-paths.txt \\
  fake-ont-nodecovs.csv \\
  resolve-mapping.txt \\
  100000 \\
  5 \\
  20 10 5 \\
  < fake-ont-alns.gaf \\
  > ont-resolved-graph.gfa \\
 2> ont_resolved_graph.gfa.err

echo ""
echo Step 17
 /gss1/home/verkko/lib/verkko/scripts/unroll_tip_loops.py \\
  ont-resolved-graph.gfa 3 \\
  < fake-ont-paths.txt \\
  > unrolled-ont-resolved.gfa \\
 2> unrolled-ont-resolved.gfa.err

echo ""
echo Step 18
 /gss1/home/verkko/lib/verkko/scripts/get_unroll_mapping.py \\
  ont-resolved-graph.gfa \\
  unrolled-ont-resolved.gfa \\
> unroll_mapping_2.txt

echo ""
echo Step 19
 /gss1/home/verkko/lib/verkko/scripts/unitigify.py utig2- unitig-mapping-2.txt \\
  < unrolled-ont-resolved.gfa \\
  > ../4-processONT/unitig-unrolled-ont-resolved.gfa
EOF

chmod +x ./processONT.sh

./processONT.sh > ../4-processONT/processONT.err 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job processONT since they might be corrupted:
4-processONT/gaps-ont.gaf, 4-processONT/nodecovs-ont.csv
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-07-18T111720.874922.snakemake.log
```
I checked the snakemake.log and processONT.err file and could find any problems. Could you give  me some advise ? Thank you very much.

**Comment by skoren** [comment]
What does the log for processONT.err contain?

**Comment by shiyi-pan** [comment]
Thank you for your reply. Here is my processONT.err file:

Step 1a
10000

Step 2a
inserted 10 gaps
inserted 1 gaps
inserted 0 gaps

Step 2b

Step 2c

Step 2d

Step 3a

Step 3b

Solid ont coverage 6 and hifi 23
first unique coverage estimate: 47.34968544467765
refined unique coverage estimate: 47.34968544467765
removed 77 nodes
utig1-2075
utig1-504
utig1-719
utig1-1685
utig1-1419
utig1-57
utig1-662
utig1-1050
utig1-628
utig1-810
utig1-774
utig1-2081
utig1-3053
utig1-849
utig1-1486
utig1-989
utig1-1336
utig1-181
utig1-1306
utig1-1302
utig1-782
utig1-1026
utig1-775
utig1-5888
utig1-193
utig1-199
utig1-1990
utig1-1519
utig1-1881
utig1-363
utig1-1187
utig1-754
utig1-74
utig1-1525
utig1-1786
utig1-1688
utig1-471
utig1-841
utig1-440
utig1-641
utig1-1383
utig1-2746
utig1-818
utig1-1465
utig1-1621
utig1-997
utig1-1342
utig1-995
utig1-62
utig1-1349
utig1-45
utig1-177
utig1-1871
utig1-632
utig1-813
utig1-356
utig1-41
utig1-1178
utig1-72
utig1-176
utig1-917
utig1-162
utig1-533
utig1-532
utig1-542
utig1-2181
utig1-931
utig1-1098
utig1-1308
utig1-1913
utig1-293
utig1-1334
utig1-665
utig1-7262
utig1-1414
utig1-323
utig1-1949

Step 4a

Step 4b

Step 5

Step 6

Step 7a

Step 7b

Step 8

Step 9

Step 10

Step 11
1779 nodes need covering
1468 edges need covering
1455 uncovered nodes
1454 uncovered edges

Step 12

Step 13
iteration 0 unresolved 3
iteration 1 unresolved 0
done unresolving, write graph
graph written

Step 14

Step 15a

Step 15b

Step 16

Thank you again.

**Comment by skoren** [comment]
I expect this is the same as #164, you can check the `ont_resolved_graph.gfa.err` to confirm. In that case, you would need to update verkko to the latest in tip if you compiled/installed it yourself or you could wait for the next bug fix release.

**Comment by shiyi-pan** [comment]
Thank you for your reply. 

I read the #164 and modified the resolve_triplets_kmerify.py.
Then I rerun the processONT.sh with the following script and it worked well:
./processONT.sh > ../4-processONT/processONT.err 2>&1
I got a new problem.  Is there a parameter to continue the whole program from processONT.sh step? Or I have to rerun the whole program?

Best wishes.

**Comment by skoren** [comment]
It should automatically resume since snakemake will recognize already completed jobs if you re-use the same command. You can first confirm by adding `--snakeopts --dry-run` to have it print what it will run to confirm it will resume at the 4-processONT step first, then run the original command.
