### ISSUE TITLE
Can I use verkko to assemble polypolid haplotyped genome?

### ISSUE THREAD

**Issue by kedduck** [marbl/verkko#181]
Dear developer:

Thanks for your great software. I have a question about polypolid  that may not mentioned by others.

I am doing assembly of a autoteraploid plant species. Can I use verkko to assemble polypolid haplotype genome with ONT and HiFi reads? It will produce four haplotypes?

I read the previous issue and not find somthing releted. 

Thanks!

**Comment by skoren** [comment]
Depends on the type ploidy (e.g. autotetraploid?) and similarity between them. If there is enough divergence, the HiFi and ONT data should phase the haplotypes and produce four copies in the output. However, the size of the contigs will be limited by phased length so if there are large stretches of homozygosity, the contig sizes may be short. Regions that occur in more than 1 haplotype would remain collapsed in the output as single nodes. The HiC and trio phasing would assume two partitions so it wouldn't work in case there are some regions of the genome that don't follow this. Your best option would be to look at the output gfa file and see if the graph looks like a diploid w/standard bubble chains or largely resolved with mostly single nodes or if it looks more complex.

**Comment by kedduck** [comment]
Thank you for the detailed explanation!
