### ISSUE TITLE
data recommendation

### ISSUE THREAD

**Issue by LHG-GG** [marbl/verkko#183]
Hi 

I have ~60x HiFi (Revio) parental data and only ~25x short reads for parental samples. Short reads are recommended for merqury hapmer generation. Could you suggest which data to use for phasing? 

I use the below command on 35x of HiFi data along with 30x ULONT, Verkko took almost 3 days to finish. 
`verkko -d HiFi --hifi 35x_HiFi_nodups.fq.gz --nano 30x_ULONT.fq.gz --hap-kmers /dev/null /dev/null trio --keep-intermediate --local-cpus 56 --local-memory 500 --sto-run 56 500 4 --mer-run 56 500 8 --ovb-run 56 500 24 --ovs-run 56 500 12 --red-run 56 500 4 --mbg-run 56 500 72 --utg-run 56 500 24 --ali-run 56 500 24 --pop-run 56 500 24 --utp-run 56 500 24 --lay-run 56 500 24`

which process can be benefited by increasing the threads to speed up the overall speed? 

Thank you

**Comment by skoren** [comment]
I would suggest using the HiFi data for the hapmer database as it is much higher coverage and at 25x you might have some issue discriminating heterozygous k-mers from noise in the short-read data. You can follow the same steps in the README to build the databases from HiFi data. I would also suggest inputting all ONT data, not just that over 100kbp as the shorter reads can still resolve shorter repeats, gaps, and help phasing.

As for running, the runtime for a human genome is typically 5-8k CPU hrs, depending on coverage. With 56 cores, that is in line with 3-4 days so I don't think the runtime is too out of expectation. I would suggest not specifying all the options for each step, the local memory and CPU is sufficient. Verkko/snakemake will parallelize what it can automatically without this. With your current options each job will try to use all the resources on a node even if it doesn't need it or can't use it. For example, correction might have been able to run several one-core jobs in parallel and fit into the memory but, by specifying 56 500 you've forced each individual job to reserve the whole machine.

**Comment by LHG-GG** [comment]
Thank you.
My final data would be ~95x HiFi for child, 60x parental reads and ~90x >=100kb ULONT. Do you think reads shorter than 100kb still needed in this case?

**Comment by skoren** [comment]
I would still include as much of the ONT data as you can, maybe not all but perhaps those over 20kb (longer than HiFi).

**Comment by LHG-GG** [comment]
I was thinking the same. Thank you.
