### ISSUE TITLE
Is it possible to compile this project with aarch64 cpu support?

### ISSUE THREAD

**Issue by 181802969** [marbl/verkko#184]
Is it possible to compile this project with aarch64 cpu support?

**Comment by brianwalenz** [comment]
Not presently.  It's on our list, but not a high priority.  In addition to the verkko code proper, I don't know the status of most of our dependencies.

What systems are you thinking running on?

**Comment by 181802969** [comment]
I'm trying to complie it on CentOS7 aarch64,  but seems needs lots of work to do.  Maybe I should turn to X86_64 CPU. Thanks a lot for your reply.
