### ISSUE TITLE
Query regarding assembly quality

### ISSUE THREAD

**Issue by prasad693** [marbl/verkko#195]
Hi,

I have an assembly with both hifiasm and verkko using same dataset (i.e. 40x Duplex; 30x ULONT [>=100 kb]; 30x PoreC -- PoreC converted into paired). I have assembled QV using duplex data with Yak QV (default parameters). Verkko assembly QVs are lesser than that of hifiasm while NG/NGA are much higher.
```
	Hap1	Hap2
Verkko	52.79	52.07
Hifiasm	57.81	57.57
```
To check if this is consistent, I downloaded _A. thaliana:_ assembly and hifi reads as mentioned here https://github.com/marbl/verkko/tree/master/paper

QV was calculated from YAK QV with default parameters using hifi reads
```
	A_thal
Verkko 37.38
Hifiasm	50.62
```

By default, Hifiasm does 3 rounds of error correction, I could not find similar details from Verkko/Canu and assume it to be 1 round. 

Is the difference in QV due to error correction (number of times/method) or the way assembly graphs are built? any thoughts?

Thank you

**Comment by skoren** [comment]
There was a bug in v1.4 that HiC consensus could be lower quality, if you ran that version then I suggest re-running. Trio runs or 1.4.1 are not affected. However, the difference likely nothing to do with correction. Hifiasm is more aggressively filtering short sequences from the assembly. I expect if you filter sequences below say 100 or 500kb the QVs would be comparable. As for N50, keep in mind that verkko output scaffolds as well as contigs when it can't resolve a repeat but can connect across it but hifiasm does not.
