### ISSUE TITLE
ONT-only assembly question

### ISSUE THREAD

**Issue by marija-kra** [marbl/verkko#202]
Hi, I remember seeing presentations on ONT-only Verkko assembly. If I have R10 ONT gDNA reads (presumably some will be duplex):
- can I use Verkko at all without PacBio?
- if I can, do I feed non-duplex reads to --nano and duplex reads to --hifi?
- are there recommended basecalling or other preprocessing settings/tools/approaches?
Thanks!

**Comment by skoren** [comment]
Verkko requires some high-accuracy data (hifi or duplex) so you could not input regular simplex ONT reads using the --hifi flag and simplex reads with --nano. Duplex reads are OK but you need 30+x coverage for it to work well. If you have less than this it will likely not work. If you have very high duplex coverage (over 50x), we also recommend increasing the minimum support required when building the graph from the default of 2 to 4 (`--unitig-abundance 4`).

**Comment by marija-kra** [comment]
Thank you, Sergey!
