### ISSUE TITLE
Error: combineConsensus.sh

### ISSUE THREAD

**Issue by mushroomOK** [marbl/verkko#206]
While working on my project ```verkko -d $maindir$name"/Verkko" --hifi $hifi --nano $ont --threads 120 --slurm --snakeopts "--cores 1000" --no-correction --no-nano --hic1 ${hic}1.fq.gz --hic2 ${hic}2.fq.gz --screen ./contaminant.fasta```, I encountered an issue and received the following error message:
```
./combineConsensus.sh > ../7-consensus/combineConsensus.out 2> ../7-consensus/combineConsensus.err
(one of the commands exited with a non-zero exit code; note that snakemake uses bash strict mode!)
```
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message."

Thank you for your time and consideration. I look forward to your guidance and suggestions.

Best regards,

**Comment by skoren** [comment]
The combineConsensus.err log should have more details, I expect it is related to #192 and supplying an absolute path to your contaminant.fasta file should work.

However, I wouldn't recommend using the assembly from your current command. First, we very strongly recommend read correction and disabling it will lead to sub-optimal assemblies. Second, you specified the ONT data but also --no-nano. The --no-nano option will force verkko to not use any of your ONT data for resolution. I would remove both those options and re-run the assembly from scratch.

**Comment by skoren** [comment]
I confirmed supplying the option as you've done will cause the 7-consensus/combineConsensus.sh step to crash and the commit above fixes that.
