### ISSUE TITLE
Empty "assembly.haplotype[1/2].fasta" (plant genome)

### ISSUE THREAD

**Issue by mushroomOK** [marbl/verkko#208]
Hi, while working on assembling a plant genome with Hi-C, I got empty "assembly.haplotype[1/2].fasta" and "assembly.fasta" which is twice the predicted size.

verkko -d $maindir$name"/Verkko" --hifi $hifi --threads 120 --slurm --snakeopts "--cores 1000" --no-correction --no-nano --hic1 ${hic}1.fq.gz --hic2 ${hic}2.fq.gz --screen contaminant $maindir$name"/Verkko"/contaminant.fasta

[assembly.err.zip](https://github.com/marbl/verkko/files/13200404/assembly.err.zip)

**Comment by pgrady1322** [comment]
Also just had the same issue with a mammalian genome, but included nanopore ultra-long as well.

**Comment by spoonbender76** [comment]
Had the same issue here with only HiFi and Hi-C. I tried the workaround in #170 , unfortunately it did not work for me.

**Comment by skoren** [comment]
@mushroomOK as I mentioned in your previous issue, the assembly you have is HiFi-only which isn't a use case the Hi-C phasing was tested extensively with. I suspect the node sizes were too short to be assigned confidently. I would suggest re-running from scratch but without the `--no-nano` and `--no-correct` options.

@spoonbender76 @pgrady1322 it's possible that the default parameters for Hi-C binning don't work with your genomes. @Dmitry-Antipov can suggest some parameters that can be adjusted.

**Comment by mushroomOK** [comment]
> @mushroomOK as I mentioned in your previous issue, the assembly you have is HiFi-only which isn't a use case the Hi-C phasing was tested extensively with. I suspect the node sizes were too short to be assigned confidently. I would suggest re-running from scratch but ccccccc
> 
> @spoonbender76 @pgrady1322 it's possible that the default parameters for Hi-C binning don't work with your genomes. @Dmitry-Antipov can suggest some parameters that can be adjusted.

Thanks. I will rerun without the `--no-nano` and `--no-correct` options. In addition, I got a good result by using both hifi and ont.
verkko -d $maindir$name"/Verkko" --hifi $hifi --nano $ont --threads 120 --slurm --snakeopts "--cores 1000" --hic1 ${hic}1.fq.gz --hic2 ${hic}2.fq.gz --screen contaminant $maindir$name"/Verkko"/contaminant.fasta

**Comment by skoren** [comment]
There have been quite a number of updates to HiC in verkko since this issue was originally opened so @pgrady1322 I'd recommend running with latest release (which should be available later this week).

@mushroomOK @spoonbender76 we don't recommend HiFi-only + HiC assemblies generally, especially when the diversity of the genome is low (making short nodes which HiC will have a harder time properly assigning). It may be improved with the next release but likely not too much. I'll make an enhancement on the projects page but it will be a lower development priority.
