### ISSUE TITLE
Slurm account and partition issue

### ISSUE THREAD

**Issue by rmolbrich** [marbl/verkko#209]
Hi, thanks for this workflow!

I am running into issues using the --slurm flag on our HPC. I tried using the --snakeopts and --cluster parameters to set account and partition trying avoid rejection by the scheduler. 

The description in the slurm-sge-submit.sh script seems to indicate that I am supposed to use it as follows:
--snakeopts "--default-resources slurm_account=MyAccount slurm_partition=prod --cluster \"./slurm-sge-submit.sh {threads} {resources.mem_gb} {resources.time_h} {rulename} {resources.job_id}{resources.slurm_account} {resources.slurm_partition}\"" . 

I don't understand where the script will get the correct file to execute.

**Comment by brianwalenz** [comment]
Snakemake will append the name of the script to run to the end of the `--cluster` command.

I'm not sure if snakemake will pass the `slurm_account` default-resources as the string "MyAccount" or if it will append the sbatch option needed before ("-A MyAccount").  You could also do:
```
--snakeopts '--cluster "./slurm-sge-submit.sh {threads} {resources.mem_gb} {resources.time_h} {rulename} {resources.job_id} -A MyAccount -p prod"'
```
(but not tested)

**Comment by rmolbrich** [comment]
Unfortunately that doesn't work. I get the following error:

sbatch: error: You must specify an account!
sbatch: error: Batch job submission failed: Unspecified error

If I submit the job as shown in my initial post I will get:

sbatch: error: Unable to open file MyAccount
sbatch: error: Unable to open file MyAccount

**Comment by skoren** [comment]
@brianwalenz I don't see the script using user-supplied args, even though the comments talk about it:
```
##########
#
#  We expect (as defined in the --cluster option) the first three args to be
#  as below, then any number of user-supplied args, then the name of the
#  script to run.
#
#  Since we want the user-supplied args to be at the end of the sbatch/qsub
#  arg list, and since the script to run is expected to be the last arg to
#  sbatch/qsub, we can extract the three values below and then simply pass
#  the rest of our args to sbatch/qsub.
#
n_cpus=$1; shift   #  Number of CPUs we can use
mem_gb=$1; shift   #  Exepcted memory needed, in gigabytes
time_h=$1; shift   #  Expected time needed, in hours
rule_n=$1; shift   #  Name of the rule
jobidx=$1; shift   #  Index of the job, "1" if a non-parallel job
```
we should fix/test that.

@rmolbrich The quickest way to get up and running would be to just edit the slurm-sge-submit.sh script in verkko's lib/verkko/profiles folder. This would also mean you don't have to remember to add the extra options to specify a project, assuming you want to keep using the same project for your runs in the future.

**Comment by rmolbrich** [comment]
Thanks, I wasn't aware that the '-A' is required when setting the resource.

I just ended up using the --jobscript flag and included the required lines in jobscript.sh.
