### ISSUE TITLE
Core dumped in MBG 

### ISSUE THREAD

**Issue by wangsb111** [marbl/verkko#210]
Hello ! 
     Thanks so much for providing the genome assembly tools . 
I uesd verkko (version : 1.4.1 , installed by minconda )  assembly my genome with pacbio and Utral-ONT data . I tried many times and filtered hifi reads short than 5kb, but still met the same problem in the MBG processing.
  The error message as below :
MBG: src/MsatValueVector.cpp:94: void MsatValueVector::MsatValueChunk::set(uint8_t, uint16_t): Assertion `realsize < 255' failed
./buildGraph.sh：行 41: 3146362 已放弃               （核心已转储）/data/01.Software/verkko-1.4.1/bin/MBG $iopt 
   I am Not sure what has gone wrong and appreciate your help in this regards , thank you so much .

**Comment by maickrau** [comment]
Could you please share the files `hifi-corrected.fasta.gz`, `1-buildGraph/buildGraph.err` and `1-buildGraph/buildGraph.sh` from the output folder. See https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you how to share the data

**Comment by wangsb111** [comment]
here is the verkko commod line:    xx/bin/verkko -d work_dir --no-correction --no-nano  --threads 60  --local-cpus 60 --hifi hifireads.gz  --nano  ontreads.gz .    
buildGraph.err and  buildGraph.sh  had uploaded to the ftp . hifi-corrected.fasta.gz are still under uploading 。

**Comment by wangsb111** [comment]
Hello,  hifi data file  "m64031_221114_110017.clean.5k.fasta.gz"  has been uploaded to the ftp .  actually， the hifi datas is un-corrected.

**Comment by skoren** [comment]
@maickrau I posted the reads on globus. @wangsb111 while we should fix this crash, I would strongly suggest re-running with corrected reads. We don't recommend uncorrected assembly as it will be much worse and we don't use it internally.

**Comment by wangsb111** [comment]
thank you for your efforts.   i will try to run without  prarmerers “--no-correction ” .

**Comment by wangsb111** [comment]
Hello, i have re-runned verkko without parameters  "-no-correctrion" .   the correction jobs were finished successfuliy, but  when 1-buildGraph with the "hifi-corrected.fasta.gz"  met the same problem 。 do you need the "hifi-corrected.fasta.gz " file , i can share it to the ftp .

**Comment by skoren** [comment]
Thanks for confirming it fails w/corrected reads too. I think the original reads should be enough to try to reproduce the crash locally.

**Comment by maickrau** [comment]
This seems to happen in MBG version 1.0.15 but not in the development version. Could you try compiling MBG from source and passing that to verkko by adding the parameter `--mbg /path/to/compiled/MBG`? There will also be a new release of MBG soon.

**Comment by skoren** [comment]
Idle, seems to be resolved w/new MBG version.
