### ISSUE TITLE
ZeroDivisionError: float division by zero in estimate_unique_local.py

### ISSUE THREAD

**Issue by Wwwwwwwyc** [marbl/verkko#211]
hello!
Thanks for the powerful verkko tool, but I had some minor issues while using it.

I run:
```
verkko -d test --hifi hifi.fq.gz --nano ultralong.fq.gz
```

and get the stop in 4-processONT. processONT.err is:
```
Step 1a
10000

Step 2a
inserted 0 gaps
inserted 0 gaps
inserted 77 gaps

Step 2b

Step 2c

Step 2d

Step 3a

Step 3b

Solid ont coverage 34 and hifi 18
first unique coverage estimate: 10.152409747278957
Traceback (most recent call last):
  File "/home/verkko/lib/verkko/scripts/estimate_unique_local.py", line 151, in <module>
    global_average_coverage = float(coverage_sum) / float(coverage_count)
ZeroDivisionError: float division by zero

```

**Comment by maickrau** [comment]
Hi, could you please share the output folder `4-processONT`? Here are the instructions for sharing data: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by Wwwwwwwyc** [comment]
Thanks for your help. We should have uploaded the folder, could it be seen?

**Comment by skoren** [comment]
Idle, can't reproduce locally without shared data. Re-open if you're able to share the data.
