### ISSUE TITLE
assertionerror insert_aln_gaps verkko v1.4.1

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#217]
Hi,

I have one case (out of 60+) of the following assertion failing:

https://github.com/marbl/verkko/blob/6931eb3ba11cd3e07b4af61a286268baa48b965d/src/scripts/insert_aln_gaps.py#L221

```
Step 1a
10000
Step 2a
Traceback
[...]
assert path_length > current_left_clip + current_right_clip
```

This is with Verkko v1.4.1 and the previous releases of MBG and GraphAligner (1.0.15 and 1.0.17). I try reproducing the failure with the most recent releases of MBG and GraphAligner.

Best,
Peter

**Comment by skoren** [comment]
Were you still seeing this crash with updated MBG/GraphAligner? Are these uploaded to globus?

**Comment by ptrebert** [comment]
The respective sample was updated with more HiFi data, causing a delay and the sample is thus still in the queue. I keep you posted.

**Comment by ptrebert** [comment]
Looks like the update of MBG/GraphAligner fixed that one
