### ISSUE TITLE
Rephrase the compile section of README file

### ISSUE THREAD

**Issue by jimmymcheung** [marbl/verkko#218]
First my excuse for opening an issue which should actually sit in discussion (but there’s none available). Here’s the question/problem that confused me: 

In the README file, it suggests to compile from the repo instead from the generated zip file. However, it was unclear to me if I should compile from the branch with the version tag (i.e. for the latest version switch to `v1.4.1` before compiling) or should I compile from the `master` branch. Since, newly changes that’s committed after a version release may not be validated, its would be preferable to me to compile from the tagged branch. My confusion is the branch with version tag is normally also auto-generated by github, is this sub-module issue also happens there or it is only limited to the zip file?

**Comment by skoren** [comment]
I updated the text in the readme to answer this.
