### ISSUE TITLE
how to specified the default partion,  the canu could work with "gridOptions=" -q big"" , 

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [marbl/verkko#219]
(verkko) [linfeifan@login2 05.hifi_ont]$ verkko  --slurm   -d /public/agis/yanjianbin_group/linfeifan/01.sanjianshan/01.assembly/05.hifi_ont/01.verrko/ --hifi $vcf --nano $ont --hic1 $hic1 --hic2 $hic2  --local-memory 2000 
Launching bioconda verkko bioconda 1.4.1
Using snakemake 7.32.4.
Using profile /public/home/linfeifan/miniconda3/envs/verkko/lib/verkko/profiles for setting default command line arguments.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 1000
Job stats:
job                            count
---------------------------  -------
buildGraph                         1
buildPackages                      1
buildStore                         1
combineConsensus                   1
combineONT                         1
combineOverlaps                    1
combineOverlapsConfigure           1
combineTipsONT                     1
configureFindErrors                1
configureOverlaps                  1
copyFiles                          1
correctHiFi                        1
emptyfile                          1
extractONT                         1
fixErrors                          1
generateLayoutContigsInputs        1
getCoverage                        1
hicPhasing                         1
indexBWA                           1
layoutContigs                      1
mergeBWA                           1
prepCoverage                       1
processGraph                       1
processONT                         1
runMashMap                         1
runRukkiHIC                        1
splitHIC                           1
splitONT                           1
splitTipsONT                       1
transformBWA                       1
untip                              1
total                             31

Select jobs to execute...

[Thu Dec 14 22:56:24 2023]
localrule emptyfile:
    output: emptyfile
    jobid: 24
    reason: Missing output files: emptyfile
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=/tmp

[Thu Dec 14 22:56:24 2023]
checkpoint splitHIC:
    input: /public/home/linfeifan/01.date/jjzhang/01.genome/01.raw_data/hic.all_R1.fastq.gz, /public/home/linfeifan/01.date/jjzhang/01.genome/01.raw_data/hic.all_R2.fastq.gz
    output: 8-hicPipeline/splitHIC.finished
    log: 8-hicPipeline/splitHIC.err
    jobid: 29
    reason: Missing output files: 8-hicPipeline/splitHIC.finished
    threads: 8
    resources: mem_mb=867008, mem_mib=826844, disk_mb=867008, disk_mib=826844, tmpdir=<TBD>, job_id=1, n_cpus=8, mem_gb=16, time_h=24
DAG of jobs will be updated after completion.

sbatch: error: Batch job submission failed: No partition specified or system default partition

**Comment by Jiangjiangzhang6** [comment]
hello, ask for your help, when i run the verkko with the data of hifi ,hic,and ont, but verkko show it didno't specified default partion, so how todo with it, i try the way as the canu ,but it's work,
it would be happy for my to get your reply 
thank you

**Comment by skoren** [comment]
Slurm interactions in verkko is handled by snakemake. See #209 for a couple of options, you can edit the submit script in the installation so you don't have to always set a parameter on the system. You can also pass the extra options to slurm on the command line.

**Comment by Jiangjiangzhang6** [comment]
> Slurm interactions in verkko is handled by snakemake. See #209 for a couple of options, you can edit the submit script in the installation so you don't have to always set a parameter on the system. You can also pass the extra options to slurm on the command line.

thank you for your reply , I wild try it

**Comment by skoren** [comment]
Idle, I presume resolved as was in #209? Please re-open if you encounter other issues.
