### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by snurk** [marbl/verkko#22]

**Comment by snurk** [comment]
Datasets to consider:

- chm13
- arabidopsis
- chrX mixture (chm13 + hg002, use marker-assisted-alignment subsets) 
- e.coli

**Comment by skoren** [comment]
On biowulf: 
 - CHM13 full dataset: 
 -- HiFi: /data/Phillippy/seq/chm13/pacbio/ccs/20kb/*.fastq.gz
 --ONT:/data/Phillippy/seq/chm13/nanopore/rel5.fastq.gz

 - Athal:
 -- HiFi:  /data/Phillippy/seq/benchmarks/arabidopsis_thaliana/hifi/
 --ONT:/data/Phillippy/seq/benchmarks/arabidopsis_thaliana/ont/
 -- note: the coverage is quite deep so MBG takes a while, perhaps use a downsampled set

 - ChrX subsets being generated, will update.

**Comment by skoren** [comment]
Resolved
