### ISSUE TITLE
ONT-Only Assembly with Verkko?

### ISSUE THREAD

**Issue by cahuparo** [marbl/verkko#221]
Hi @skoren ,

I am working on assembling a genome using Oxford Nanopore Technologies (ONT) R10 reads with Verkko. I have encountered a challenge with the requirement for PacBio HiFi reads (`--hifi` flag), which I do not have. My dataset consists of ONT R10 reads with ~100X coverage, and I would like to understand if it's possible to run Verkko with ONT-only reads.

### Attempts and Observations
- I have attempted to run Verkko using the `--nano` flag for the ONT reads.
- When not supplying the `--hifi` flag, Verkko produces an error indicating that PacBio HiFi reads are mandatory.
- I tried using a dummy file for the `--hifi` flag as a placeholder, but as expected, Verkko could not proceed with the assembly since the dummy file contained no valid reads.

### Questions
1. Is there a way to configure Verkko to run with only ONT reads, without the need for PacBio HiFi reads?
2. If Verkko does support ONT-only assemblies, what are the correct parameters or configuration settings I should use?
3. Are there any planned updates or workarounds that could facilitate ONT-only assemblies in Verkko? Any suggestion for another tool that can handle ONT only to produce phased assemblies? I do plan to polish the initial assembly with PE read data. 

### Relevant Details
- **Verkko Version:** verkko bioconda 1.4.1
- **Command Used:**  
`verkko -d output_1000_15_decon_pcap_8735_concatenated_reads --nano decon_pcap_8735_concatenated_reads.fastq --local-cpus 24 --local-memory 600 --max-k 15 --min-ont-length 1000 --unitig-abundance 4 --hifi dummy_hifi.fastq`

I would greatly appreciate any guidance you can provide. Thank you for your support and for developing Verkko.

Best, 

Camilo

**Comment by skoren** [comment]
Verkko doesn't support ONT-only assembly unless you have duplex reads to replace the HiFi. We've been experimenting with the new Q20+ data that ONT recently released for the human genome but I expect this doesn't describe your data type.  I'd look at flye or Shasta for ONT-only support.

**Comment by nponts** [comment]
Hi, I'm bouncing back t ask how to use Verkko with duplex data and Q20+ data, if possible :) Thank you!

**Comment by nponts** [comment]
Hi,
I tried option 1 and it seems to be going fine. Option 2 is proving more difficult to install on my system, but I'll tell you if I go somewhere with it. Thank you for your help!
