### ISSUE TITLE
processONT: "assert revnode(node) not in hairpins" 

### ISSUE THREAD

**Issue by grinning-bat** [marbl/verkko#233]
Hello! It's me again, with the same dataset as in #230
Got empty ont-resolved-graph.gfa
and error in ont_resolved_graph.gfa.err:

<pre>
resolve with edge support 20
resolve k=1001, extended 1 nodes into 2 nodes
Traceback (most recent call last):
  File "[redacted]/lib/verkko/scripts/resolve_triplets_kmerify.py", line 1032, in <module>
    resolve(node_lens, edge_overlaps, node_seqs, edges, paths_crossing, coverage, min_allowed_coverage, removable_nodes)
  File "[redacted]/lib/verkko/scripts/resolve_triplets_kmerify.py", line 732, in resolve
    (new_nodes, resolved) = resolve_hairpins(current_length, current_nodes, paths_crossing, node_seqs, node_lens, edges, maybe_resolvable, min_edge_support,
  File "[redacted]/lib/verkko/scripts/resolve_triplets_kmerify.py", line 258, in resolve_hairpins
    assert revnode(node) not in hairpins # double hairpin resolution hard to implement, so just hope it never happens
AssertionError
</pre>

>**so just hope it never happens**
It happened apparently.

Relevant files uploaded on the FTP
b995150b482fef88d7a408c83f3c001f  revnode_not_in_hairpins.tgz

UPD:
Sorry, didn't check fresh issues. Duplicate of #231

**Comment by skoren** [comment]
I was about to say, have you tried the fix from #231? If it fixes your crash I'll close both.

**Comment by grinning-bat** [comment]
Tried it. Works. Thank you!

**Comment by skoren** [comment]
Thanks for confirming.
