### ISSUE TITLE
assigning "-run" acronym to step

### ISSUE THREAD

**Issue by DustinSokolowski** [marbl/verkko#238]
Hello and thank you for the excellent tool. 

I am currently working on a _de novo_ assembly that will eventually use Hifi, nanopore and Hi-C data. I am currently testing verkko with the Hifi reads exclusively to ensure that everything is running smoothly on my system before layering in the ONT and Hi-C reads.

When I tried this, I got a "Killed" error when running buildPackages before 7-consensus, right after all of the reads are read in.
 ---
...
...
-- Loading reads from '~/m84134_240306_201715_s1.fastq':  6944767 reads.
-- Loading reads from ~/m84134_240306_201715_s1.fastq':  6945279 reads.
Killed
---

Looking at other errors, I think I need manually set the resource limits for the 7-consensus stage. This being said, I can't figure out which three-letter code is assigned to which stage in the analyis. Can you please provide this key for me? The command is more-or less default other than that I use sge and have changed the SGE submission script to be compatible with my cluster (e.g., `smp` instead of `thread`, always provide project name etc...)

`verkko -d PB_default --hifi $fqDir/m84134_240306_201715_s1.fastq --sge`

Thanks again!
Dustin

**Comment by Dmitry-Antipov** [comment]
Hi,
Yeah, we definitely need more documentation for these options..
Prefix for this stage is par_

**Comment by DustinSokolowski** [comment]
Hey! Thank you so much for the quick reply. 

If you have a moment to assign each prefix to each checkpoint, even if you just put it in a reply here, I'd be hugely appreciative. I have a lot of species/data coming in and I am expecting to use verkko a ton in the next couple years.

Thanks again!
Dustin

**Comment by Dmitry-Antipov** [comment]
Added those prefix explanation to verkko's readme.

**Comment by DustinSokolowski** [comment]
Thank you!!
