### ISSUE TITLE
Ensure reproducibility

### ISSUE THREAD

**Issue by snurk** [marbl/verkko#24]

**Comment by skoren** [comment]
Definitely some instability, in two runs of arabidopsis subset there is a difference in bubble structures. I confirmed the hifi corrected reads are identical as is the snakemake config. In the first run, Chr3 has two bubbles and is made up of 3 large contigs (beta_asm_finished, utig4-2348, utig4-2356, utig4-2361). In the second run, Chr3 is a single large node (beta_asm, utig4-2353). See attached images:
![graph_new](https://user-images.githubusercontent.com/923478/153725911-e46212de-abcc-4e31-bc9b-df7ec5c873de.png)
![graph_old](https://user-images.githubusercontent.com/923478/153725913-01283043-0107-4288-b9c5-2d0406c857dc.png)


The assemblies are in `/data/korens/test/mikko_cns/athal_subset/beta_asm*/`

**Comment by skoren** [comment]
The arabidopsis instability is resolved by the recent updates, it consistently (over 3 runs) produces an assembly without the bubbles. Will need to check CI to ensure it stays stable as well.

**Comment by skoren** [comment]
This seems to be resolved with the changes mentioned above.
