### ISSUE TITLE
unexpected operator 3-align/index.sh

### ISSUE THREAD

**Issue by rfinkers** [marbl/verkko#244]
in the folder 3-align, script index.sh (Linux ubuntu 22); the following error is thrown: 

./index.sh: 10: [: False: unexpected operator

this results in an empty diploid.index; pipeline continues as normal.

As I don't fully understand the impact of this; e.g. what is the effect of execution of the first part of the test  (diploid="--diploid-heuristic 21 31 --diploid-heuristic-cache ../3-align/diploid.index"), rather than the touch diploid.index; I have trouble know if/what the impact of this on my assembly might be. This besides the possible bug in this script.

**Comment by brianwalenz** [comment]
Ouch!  The error is the double-equal-sign `==` in `index.sh`; Ubuntu's `/bin/sh` seems particularly strict but we don't have any instances to test on.  `index.sh` is generated by `${VERKKO_INSTALL_DIR}/lib/verkko/Snakefiles/3-alignONT.sm`.  Changing `==` to `=` on lines 59 and 131 will fix the problem.

The bigger issue is that unless you ran with `--haploid`, you're assembly isn't correct.  You can recover some of the lost compute by removing (or renaming) directories `[45678]*`, `3-alignTips`, the `assembly.*` outputs and everything in `3-align` EXCEPT the `split*` files/directory.

**Comment by rfinkers** [comment]
confirmed that this workaround did do the trick.
