### ISSUE TITLE
Missing indexing in step 8-hicpipeline

### ISSUE THREAD

**Issue by rfinkers** [marbl/verkko#246]
Noticing the following message in the file: run_mashmap.err (8-hicPipeline folder); missing step in the workflow?

[mashmap::skch::Map::mapQuery] WARNING, no .fai index found for ../8-hicPipeline/unitigs.hpc.fasta, reading the file to sum sequence length (slow)

**Comment by Dmitry-Antipov** [comment]
No, there is no missing step here (and in fact counting input sequence length is really fast), just a bit misleading mashmap's warning.
