### ISSUE TITLE
adding multiple childs

### ISSUE THREAD

**Issue by sablokgaurav** [marbl/verkko#249]
would it be possible to add the multiple child data for a assembly. Such as we have the maternalreads in sample1.fastq.gz and the paternal reads in the sample2.fastq.gz and the child1 as child1.fastq.gz and the child2 as child2.fastq.gz  then building the hapmers from the parents as 

```
meryl count compress k=desiredvalue maternal.fastq output maternal.meryl
meryl count compress k=desiredvalue paternal.fastq  output paternal.meryl
# after making the hapmers from the parents
# running the assembly as 
verkko -d haplotypes --hifi child*.fastq --hap-kmers parentaladd maternaladd trio  --haplo-divergence desiredvalue 
```
thank you,
Gaurav

**Comment by skoren** [comment]
I'm not sure if you mean multiple child reads for the Meryl DBs or input to verkko? Both support multiple fastq inputs as wildcards, For example, meryl supports multiple input fastq, see the documentation on building DBs here: https://github.com/marbl/merqury/wiki/1.-Prepare-meryl-dbs#2-build-k-mer-dbs-with-meryl. Then, you'd run `hapmers.sh` (https://github.com/marbl/merqury/wiki/1.-Prepare-meryl-dbs#3-build-hap-mer-dbs-for-trios). The `--haplo-divergence` parameter isn't needed for trio markers.

**Comment by sablokgaurav** [comment]
@skoren thank you and this clarifies. I meant for the verkko. As per the protocol says that passing on the maternal and the paternal to the hapmers and then using the child for the assembly with maternal and paternal hapmers. I build the maternal and paternal hapmers and then used those hapmers while using the child reads as input to the verkko. kindly let me know. thank you a lot. I am writing a control flow and also a nextflow to add to this. alles best, gaurav

**Comment by skoren** [comment]
I'm not sure which documentation you're referring to. Is the child data Illumina/short read? Those are never input to verkko, they're only used to generate the hapmers. If the child data is HiFi then yes, it would be input to verkko and could also be used when generating hapmers.

**Comment by sablokgaurav** [comment]
@skoren thank you. The documentation i am referring to is the one with the child data. if the child data is not there then the files that will go into the verkko will be the *.only.*meryl and with the child data, it goes with the *.hapmer.*. thank you for the discussion. gaurav

**Comment by skoren** [comment]
Right, if there is no child short-read data you can use HiFi from the child instead which should almost always be available if you're running verkko. Alternatively, you can skip the child input to `hapmers.sh` and it will generate the *only*meryl folders instead. In either case, the child data given to meryl isn't directly input to assembly, it's only used to construct the meryl databases that then go into the assembly.

**Comment by sablokgaurav** [comment]
@skoren I did an alternative approach also which i thought. I took the hapmers corrected reads from the merqury and put them into the hifiasm and at the same time verkko. Please see the stats below as it is still running. 
```
maternalpaternalcorrected.log:[M::ha_ct_shrink::2825.590*1.79] ==> counted 2280910 distinct minimizer k-mers
maternalpaternalcorrected.log:[M::ha_pt_gen::3818.254*1.83] ==> counted 23792352 distinct minimizer k-mers
maternalpaternalcorrected.log:[M::ha_ct_shrink::3818.653*1.83] ==> counted 18683603 distinct minimizer k-mers
maternalpaternalcorrected.log:[M::ha_pt_gen::4775.646*1.86] ==> indexed 704641025 positions, counted 18683603 distinct minimizer k-mers
maternalpaternal.log:[M::ha_ct_shrink::1916.143*1.85] ==> counted 2294903 distinct minimizer k-mers
maternalpaternal.log:[M::ha_pt_gen::2944.189*1.86] ==> counted 35316758 distinct minimizer k-mers
maternalpaternal.log:[M::ha_ct_shrink::2944.904*1.86] ==> counted 19527647 distinct minimizer k-mers
maternalpaternal.log:[M::ha_pt_gen::3870.837*1.89] ==> indexed 685979913 positions, counted 19527647 distinct minimizer k-mers
```
indexed positions have been improved and basically the graph will improve. I wrote a new graphindexer, which will fetch those indexed position from the graph. Will put all these with the details here. I think the assembly will improve considerably.

**Comment by skoren** [comment]
Sorry I don't follow what your alternative approach is. At least in verkko, the marker information isn't used in building the graph, it's only used for the final resolution so changing markers won't change the graph. Changing the input reads would change the graph but I'm not sure what you mean by hammer corrected reads since Merqury doesn't correct reads.

**Comment by sablokgaurav** [comment]
@skoren thank you and i can explain a little bit. I am aware that the marker information is not used in building the graph, i read the complete paper and also the code first and yes changing the input reads would change the graph, so what i did was first build the hapmers using the Merqury and then used that for the input into the hifiasm. Merqury outputs a hifi.corrected.reads. I am waiting for the run to finish so that i can see and send you the complete one to have a look.

**Comment by skoren** [comment]
I think you're mixing tool names, hifiasm wouldn't be compatible with merqury DBs, it relies on yak instead. Either way, switching out the correction algorithm in the assembler is unlikely to improve results. All hifi assemblers have some form of built-in correction and are tuned to work best with their own output. Since the original issue is resolved, I'll go ahead and close this issue. Feel free to leave a comment with your final results.

**Comment by sablokgaurav** [comment]
@skoren Yes i will let the run complete and will pot is up if something comes out of that. Yes, it relies on yak for the building of the kmers and i have used that also and separated the haplotigs and it worked well so do the verkko. thank you for this discussion, it was quite learning from this. best regards,gaurav
