### ISSUE TITLE
Is v2.1 available in bioconda?

### ISSUE THREAD

**Issue by chunlinxiao** [marbl/verkko#253]
Hi,

I had the following error when I tried to install the latest v2.1:

conda install -c conda-forge -c bioconda  verkko==2.1

PackagesNotFoundError: The following packages are not available from current channels:

  - verkko==2.1
  
Is v2.1  available yet in bioconda?

thanks

**Comment by skoren** [comment]
No, see the note on the release page: https://github.com/marbl/verkko/releases. Bioconda's test pipeline has been down for an extended time so no packages could get updates (https://github.com/bioconda/bioconda-recipes/issues/41025). It finally got resolved earlier today so I expect verkko will become available in the next couple of days. I'll update the release page then.
