### ISSUE TITLE
ZeroDivisionError in unroll_simple_loops.py

### ISSUE THREAD

**Issue by ASUQ** [marbl/verkko#254]
I am facing an error at 5-untip, line 53 in untip.sh, which is ZeroDivisionError in unroll_simple_loops.py.

Here is the output in stderr (unitig-mapping-3a.txt)
```
Traceback (most recent call last):
  File "/Conda-envs/verkko/lib/verkko/scripts/unroll_simple_loops.py", line 51, in <module>
    avg_coverage = long_coverage_cov_sum / long_coverage_len_sum
ZeroDivisionError: float division by zero
```

The input I used is ONT data with the `--hifi` option and hic data with the `--hic` option.

```
Verkko: v2.1 (from bioconda)
CentOS Linux release 8.5.2111
Linux version 4.18.0
Conda version 23.9.0
Mamba version 1.5.6
```

**Comment by skoren** [comment]
That error means you have no long nodes in your assembly, essentially nothing assembled. What is the exact ONT input data you're using (flow cell, duplex/simplex, coverage)?

**Comment by ASUQ** [comment]
Actually before getting an error, there were bunches of outputs in unitig-mapping-3a.txt
```
utig3a-202831	>utig1-196716<utig1-196717:0:0
utig3a-202832	>utig1-199328<utig1-199329:0:0
utig3a-202833	>utig1-206867<utig1-206868:0:0
utig3a-202834	>utig1-25323<utig1-25324:0:0
utig3a-202835	>utig1-37996<utig1-37997:0:0
Traceback (most recent call last):
  File "/Conda-envs/verkko/lib/verkko/scripts/unroll_simple_loops.py", line 51, in <module>
    avg_coverage = long_coverage_cov_sum / long_coverage_len_sum
ZeroDivisionError: float division by zero
```

The dataset I used was ONT simplex read.
Since I don't have hifi reads, I might use different assembler.

Thank you.

**Comment by skoren** [comment]
Yes, verkko is not designed for simplex data, it needs a high accuracy read set as the `--hifi` input. You could try herro (https://github.com/lbcb-sci/herro) aka dorado correct (https://github.com/nanoporetech/dorado?tab=readme-ov-file#read-error-correction) which should allow you to input the corrected reads as `--hifi` and the standard simplex reads as `--nano`. If you try that and encounter errors in verkko, please open a new issue.
