### ISSUE TITLE
Help doc clarification

### ISSUE THREAD

**Issue by dmacguigan** [marbl/verkko#256]
Hello,

In the "Getting Started" section of your GitHub page, you state:

> For HERRO corrected reads, provide the corrected reads with the --hifi option and the uncorrected reads as --nano

I'm a bit confused by the wording. Does this mean the user supplies the same uncorrected read dataset with `--nano` that was corrected with HERRO? Doesn't that mean you're effectively double counting each read?

Thanks for your help,
Dan

**Comment by skoren** [comment]
Yes, that's right, you'd supply the reads before correction to `--nano`. 

The nano and hifi reads are used in different parts of the resolution for verkko so they wouldn't get double-counted. The nano reads are used to extend phasing and fill gaps after the hifi reads. For this, we prefer the original reads in case there were any phase switches introduced during correction or if some reads were shortened/removed and created a gap. This is done on the hifi-simplified graph and any reads fully contained in a node are ignored. The nano reads are only used for consensus where they have filled in a gap.

**Comment by dmacguigan** [comment]
Thanks for the clarification!
