### ISSUE TITLE
FASTA output format incompatible with gVolante

### ISSUE THREAD

**Issue by dmacguigan** [marbl/verkko#259]
Hello,

I am attempting to feed the verkko assembly FASTAs into [gVolante ](https://gvolante.riken.jp/) to generate some quality stats (because I am lazy). Unfortunately, I keep getting a message: `Error: invalid file`. I get this error for all assembly files (assembly.fasta and assembly.haplotype[1/2].fasta)

gVolante works perfectly fine with all other FASTA file I've ever tried. Is there something unique about verkko's FASTA format?

Thanks for your help,
Dan

**Comment by skoren** [comment]
Nothing special about the fasta, it is on a single line (not wrapped) like is common with fasta files. You could try running fold first, something like `cat assembly.fasta |fold -c > assembly.folded.fasta` and see if that works with gVolante.

**Comment by dmacguigan** [comment]
So strange. The main assembly (assembly.fasta) uploads, but not when gzipped. The haplotype assemblies don't work uncompressed or gzipped. I also tried folding the fastas, but no luck.

They seem to be running fine with CLI BUSCO, so perhaps this is a gVolante problem.

**Comment by skoren** [comment]
Yes that is strange, if you find out something we can change in verkko's output that fixes the issue, please let us know.
