### ISSUE TITLE
TabError in file <string>, line 97:

### ISSUE THREAD

**Issue by WengangXbio** [marbl/verkko#262]
Hi developer,
Thank you for your development of the useful assembler. I came across error reported when I try to run verkko  in my terminal as below. I install snakemake and verkko through conda, 

 the snakemake verison is 7, 

gcc is 9, 

python is 3.12.3 

verkko is 1.4.1

```
(snakemake_env) [yzwl_zhangwg@mgt19 verkko]$ verkko -d verkko_YL  --hifi PB-hifi.fastq.gz  --nano ONT-UL.fastq.gz
Launching bioconda verkko bioconda 1.4.1
Using snakemake 7.32.4.
TabError in file <string>, line 97:
inconsistent use of tabs and spaces in indentation (<string>, line 97)
  File "/share/home/yzwl_zhangwg/.conda/envs/snakemake_env/lib/python3.12/tokenize.py", line 580, in _generate_tokens_from_c_tokenizer
  File "/share/home/yzwl_zhangwg/.conda/envs/snakemake_env/lib/python3.12/tokenize.py", line 576, in _generate_tokens_from_c_tokenizer
```
Would be appreciate if you can help me on this, many thanks!

**Comment by skoren** [comment]
Doesn't look like a verkko error to me, your environment python/snakemake is not functioning correctly, see https://github.com/snakemake/snakemake/issues/2459. I'd suggest using python 3.11 and updating to a newer verkko since you are on 1.4.1 which is two releases behind.

**Comment by skoren** [comment]
I confirmed this is an issue with your outdated version of verkko. When I check snakefmt on v1.4.1 Snakefile I get:
```
% git checkout v1.4.1
% snakefmt Snakefile
  File "<string>", line 97
    colorscsv   = 'assembly.colors.csv'
                                       ^
TabError: inconsistent use of tabs and spaces in indentation
```
However, when I update to the 2.1 version it is fine:
```
% git checkout v2.1
% snakefmt Snakefile
[INFO] Writing formatted content to Snakefile
[INFO] All done 🎉
```
