### ISSUE TITLE
Error in rule combineConsensus:

### ISSUE THREAD

**Issue by wsd2345** [marbl/verkko#265]
Error in running hifi, ont, hi-c data.
 Can you help me check?
![微信截图_20240620221309](https://github.com/marbl/verkko/assets/171265396/6cdd6ef2-64e3-497c-a6ec-acbc36b1b3ac)

**Comment by skoren** [comment]
To help we need more details on your run. What is the version of verkko you're running? What is the command and input data you used? What's the contents of `combineConsensus.*` and `screen-assembly.*`

**Comment by wsd2345** [comment]
version : verkko2.1

command : verkko -d verkko_G30136 --hifi /public1/home/scf1179/cgq/genome/ccs-test.fastq.gz --nano /public1/home/scf1179/cgq/genome/ont-test.fastq.gz --hic1 /public1/home/scf1179/cgq/genome/Unknown_BB742-02H0001_good_1.fq.gz --hic2 /public1/home/scf1179/cgq/genome/Unknown_BB742-02H0001_good_2.fq.gz

data : hifi、ont、hi-c

The file is as follows
[file.zip](https://github.com/user-attachments/files/15916678/file.zip)

**Comment by skoren** [comment]
Looks like you ran out of space:
```
% cat combineConsensus.err
cp: error writing ‘../7-consensus/unitig-popped.fasta’: Disk quota exceeded
```

**Comment by wsd2345** [comment]
thank you
