### ISSUE TITLE
ERROR in combineConsensus

### ISSUE THREAD

**Issue by KANGYUlab** [marbl/verkko#267]
Hi, when i run verkko :
verkko -d ont_herro-nocorr  --hifi herro/porechopped.fa.gz --nano ont.fa.gz --hap-kmers M.hapmer.meryl P.hapmer.meryl trio --threads 64 --local --local-memory 200 --no-correction

It stopped at 7-consensus combineConsensus, reported:
ERROR: contig M.hapmer-0004259 is empty.
ERROR: piece piece000019 missing from gapped contig P.hapmer-0004316.

Did the parameter setting "--no-correction" cause the problem?

Thank you  so much.

**Comment by Dmitry-Antipov** [comment]
Hi,
It should not be related.
Which version of verkko do you use? There was an issue in verkko2.0 with this symptoms, but it should be fixed in verkko2.1

**Comment by KANGYUlab** [comment]
Yes, it run in verkko2.0, I will try again. Thank you.

**Comment by Dmitry-Antipov** [comment]
Please reopen this issue if you see the same in 2.1

**Comment by gdroc** [comment]
Hi,
I used the last version (2.1).
When I run verkko (Hic mode) with
 verkko --cleanup --threads 32   -d results/C45_410/assembly/verkko/ --hifi data/C45_410.fastq.gz --hic1 data/DTG_OmniC_974/DTG_OmniC_974_CKDL240006666-1A_22JKVWLT3_L8_R1.fastq.gz --hic2 data/DTG_OmniC_974/DTG_OmniC_974_CKDL240006666-1A_22JKVWLT3_L8_R2.fastq.gz  --slurm  --snakeopts " --cores 200 --cluster './slurm-sge-submit.sh {threads} {resources.mem_gb} {resources.time_h} {rulename} {resources.job_id} -p agap_long'"

I have got an error (8-hicPipeline/final_contigs/7-consensus/combineConsensus.err) 
ERROR: contig contig-0000782 is empty.

Snakemake process was at the end
[Mon Jul 15 01:10:14 2024]
localrule cnspath:
    input: 6-layoutContigs/unitig-popped.layout, 6-layoutContigs/unitig-popped.layout.scfmap, 7-consensus/unitig-popped.fasta, 7-consensus/unitig-popped.haplotype1.fasta, 7-consensus/unitig-popped.haplotype2.fasta, 7-consensus/unitig-popped.unassigned.fasta
    output: assembly.homopolymer-compressed.layout, assembly.fasta
    jobid: 0
    reason: Missing output files: assembly.fasta, assembly.homopolymer-compressed.layout; Input files updated by another job: 7-consensus/unitig-popped.fasta, 7-consensus/unitig-popped.haplotype2.fasta, 6-layoutContigs/unitig-popped.layout.scfmap, 7-consensus/unitig-popped.haplotype1.fasta, 7-consensus/unitig-popped.unassigned.fasta, 6-layoutContigs/unitig-popped.layout
    resources: mem_mb=2890, mem_mib=2757, disk_mb=2890, disk_mib=2757, tmpdir=/tmp

[Mon Jul 15 01:10:19 2024]
Finished job 0.
500 of 500 steps (100%) done
Complete log: .snakemake/log/2024-07-14T062408.640509.snakemake.log

When I look at the final results
assembly.haplotype1.fasta and assembly.haplotype2.fasta are empty

What could I try to correct the problem?
Regards
Gaetan
