### ISSUE TITLE
Error of 4-processONT

### ISSUE THREAD

**Issue by YouxinZhao** [marbl/verkko#268]
I am using R10 ONT data corrected with dorado（SUP）herro model to assemble the genome. 
Two jobs all stopped for error of 4-processONT.

ont_resolved_graph.gfa.err
![image](https://github.com/marbl/verkko/assets/95477328/058368da-4753-41f1-bb3d-3774e279ba6b)

**Comment by YouxinZhao** [comment]
Verkko V2.1

**Comment by YouxinZhao** [comment]
![image](https://github.com/marbl/verkko/assets/95477328/f70fc0e0-fe59-4154-85c1-e5d9f14262e8)

**Comment by YouxinZhao** [comment]
ont_resolved_graph.gfa.err:
https://github.com/marbl/verkko/assets/95477328/abe7e101-ebab-4f2f-a419-4d6a531af523

**Comment by YouxinZhao** [comment]
The files were uploaded.
https://figshare.com/articles/dataset/Verkko_error/26308852

**Comment by maickrau** [comment]
Commit [7248729](https://github.com/marbl/verkko/commit/72487299dff0b56aedfc4600f31eed32a12fa1cf) in master branch should fix this bug

**Comment by skoren** [comment]
I presume this is fixed? It should be part of the next release which should be available in the next couple of weeks.
