### ISSUE TITLE
assembly[1,2] empty

### ISSUE THREAD

**Issue by gdroc** [marbl/verkko#269]
Hi,
I used the last version (2.1).
When I run verkko (Hic mode) with
```
 verkko --cleanup --threads 32   -d results/C45_410/assembly/verkko/ --hifi data/C45_410.fastq.gz --hic1 data/DTG_OmniC_974/DTG_OmniC_974_CKDL240006666-1A_22JKVWLT3_L8_R1.fastq.gz --hic2 data/DTG_OmniC_974/DTG_OmniC_974_CKDL240006666-1A_22JKVWLT3_L8_R2.fastq.gz  --slurm  --snakeopts " --cores 200 --cluster './slurm-sge-submit.sh {threads} {resources.mem_gb} {resources.time_h} {rulename} {resources.job_id} -p agap_long'"
```

I have got an error (8-hicPipeline/final_contigs/7-consensus/combineConsensus.err) 
`ERROR: contig contig-0000782 is empty.`

Snakemake process was at the end
[Mon Jul 15 01:10:14 2024]
```
localrule cnspath:
    input: 6-layoutContigs/unitig-popped.layout, 6-layoutContigs/unitig-popped.layout.scfmap, 7-consensus/unitig-popped.fasta, 7-consensus/unitig-popped.haplotype1.fasta, 7-consensus/unitig-popped.haplotype2.fasta, 7-consensus/unitig-popped.unassigned.fasta
    output: assembly.homopolymer-compressed.layout, assembly.fasta
    jobid: 0
    reason: Missing output files: assembly.fasta, assembly.homopolymer-compressed.layout; Input files updated by another job: 7-consensus/unitig-popped.fasta, 7-consensus/unitig-popped.haplotype2.fasta, 6-layoutContigs/unitig-popped.layout.scfmap, 7-consensus/unitig-popped.haplotype1.fasta, 7-consensus/unitig-popped.unassigned.fasta, 6-layoutContigs/unitig-popped.layout
    resources: mem_mb=2890, mem_mib=2757, disk_mb=2890, disk_mib=2757, tmpdir=/tmp

[Mon Jul 15 01:10:19 2024]
Finished job 0.
500 of 500 steps (100%) done
Complete log: .snakemake/log/2024-07-14T062408.640509.snakemake.log
```
When I look at the final results
assembly.haplotype1.fasta and assembly.haplotype2.fasta are empty

What could I try to correct the problem?
Regards
Gaetan

_Originally posted by @gdroc in https://github.com/marbl/verkko/issues/267#issuecomment-2227963362_

**Comment by gdroc** [comment]
I have a look at combineConsensus.sh
  awk < ../6-layoutContigs/unitig-popped.layout.scfmap \
    'BEGIN {
       FS="[ \t]+"; OFS="\t";
     }
     ($1 = "path") && ($2 ~ /^haplotype1-[0-9]+$/)    { print $2 > "./paths-haplotype1"; }
     ($1 = "path") && ($2 ~ /^haplotype2-[0-9]+$/)    { print $2 > "./paths-haplotype2"; }
     ($1 = "path") && ($2 ~ /^unassigned-[0-9]+$/) { print $2 > "./paths-unassigned"; }'

And after this, paths-haplotype1 and paths-haplotype2 are empty, the file unitig-popped.layout.scfmap 
 grep "path" ../6-layoutContigs/unitig-popped.layout.scfmap|head -5
path contig-0000001 utig4-0
path contig-0000002 utig4-1
path contig-0000003 utig4-10
path contig-0000004 utig4-100
path contig-0000005 utig4-1000

Neither the haplotype or unassigned appear

**Comment by skoren** [comment]
Is this a continuation of a run you started with v2.0? If so, you have to remove the full 8-hicPipeline/final_contigs folder and re-run with 2.1 from that point. If not, I don't think you're running v2.1 but an older release. What does `verkko --version` report? 

If there was an error during the run, the assembly output isn't the final result so you can't use it to check the phasing results and shouldn't expect the haplotype[12] to be non-empty.

**Comment by gdroc** [comment]
I run it from scratch.
Damned!, I think you are right it seems that I used version 1.4.1!!!
verkko  --version
bioconda verkko bioconda 1.4.1

I used this command for install:
conda install -c conda-forge -c bioconda -c defaults verkko

I don't check after, but if I understand, I need to specify a version ?

**Comment by gdroc** [comment]
I  try to use singularity  using this container https://depot.galaxyproject.org/singularity/verkko%3A2.1--h45dadce_0
But when I run with the same command
singularity exec verkko.sif verkko   --cleanup --threads 32   -d C45_410  --hifi data/C45_410.fastq.gz --hic1 data/DTG_OmniC_974/DTG_OmniC_974_CKDL240006666-1A_22JKVWLT3_L8_R1.fastq.gz --hic2 data/DTG_OmniC_974/DTG_OmniC_974_CKDL240006666-1A_22JKVWLT3_L8_R2.fastq.gz --cns-run 4 32 24 --ovs-run 1 96 12  --slurm  --snakeopts " --cores 200 --cluster './slurm-sge-submit.sh {threads} {resources.mem_gb} {resources.time_h} {rulename} {resources.job_id} -p agap_long'"

I have got an error 

[Mon Jul 15 17:15:40 2024]
rule buildStore:
    input: /home/drocg/scratch/genomeassembly_with_verkko/data/C45_410.fastq.gz
    output: 0-correction/hifi.seqStore
    log: 0-correction/buildStore.err
    jobid: 9
    reason: Missing output files: 0-correction/hifi.seqStore
    resources: mem_mb=86029, mem_mib=82044, disk_mb=86029, disk_mib=82044, tmpdir=<TBD>, job_id=1, n_cpus=1, mem_gb=4, time_h=4

Error submitting jobscript (exit code 1):

Without any more explanation. 
Do you have an idea on how can I configure slurm using verrko in singularity mode ?

**Comment by skoren** [comment]
You shouldn't need to specify a version if conda installed the new version, the install might have had an error on your system or there is another verkko in your path that is older and is found before the conda version. 

We didn't build the singularity container and I don't have experience with how it interacts with slurm. I think in that case you'd probably want to run on a single node instead.
