### ISSUE TITLE
Issue with SplitONT using Dorado v5 and herro V1

### ISSUE THREAD

**Issue by DustinSokolowski** [marbl/verkko#271]
Hello and thank you for the excellent tool.

We have previously used verkko to generate a _de novo_ assembly using PB hifi reads, R10 ONT reads, and trios. We recently updated the basecalling to use dorado v5 (wf-dna_r10.4.1_e8.2_400bps_sup@v5.0.0) with correction using herro V1. Since then, the identical pipeline no longer works as  verrko seems to be unable to recognize and index the outputted fastq file from herro (see the final lines from the error attached). Have you come across this issue before and if so, do you know how we can address it?

Thanks again for all your support,
Dustin

[SplitONT final line err.txt](https://github.com/user-attachments/files/16369631/SplitONT.final.line.err.txt)

**Comment by skoren** [comment]
From the log it looks like the fastq input is invalid, it can't find a read name and it seems like it's being recognized as a fasta (because it starts with a ">") but then it has fastq lines in the error log. How was this file generated? Are you able to share the file?

**Comment by DustinSokolowski** [comment]
Hey!

I'm sorry for the slow reply. I think you are right and am re-running herro before I bother you any further. I'll update if the problem persists and thank/close if the issue was me inputting an incomplete/corrupted herro file.

**Comment by skoren** [comment]
Were you able to resolve this?

**Comment by DustinSokolowski** [comment]
Hello! 

Sorry for getting back to you so slowly, The issue was with the herro-correction and not with verkko. Thanks again for your continued support!

Best,
Dustin
