### ISSUE TITLE
error of 4-processONT

### ISSUE THREAD

**Issue by JWJ13164328557** [marbl/verkko#273]
how to save it?
![image](https://github.com/user-attachments/assets/c5044813-94e4-4cce-8000-0ba85bf532d5)

fast i think  OFS is error
![image](https://github.com/user-attachments/assets/aec8c8c3-7476-40a5-972f-c237ae80bf2f)
so I changed OFS
![image](https://github.com/user-attachments/assets/fce320c3-4cb5-4f37-9cff-64006f3b3220)
but it will make mistakes in the next step

**Comment by skoren** [comment]
The OFS is correct, it's likely related to having no nodes over 100kb, see #127. What is your input data (type, coverage, genomes size)?

**Comment by JWJ13164328557** [comment]
I used duplex, ONT, and porec data

**Comment by JWJ13164328557** [comment]
Thank you very much！！！！！！！！

**Comment by JWJ13164328557** [comment]
![image](https://github.com/user-attachments/assets/ed569d8d-ac78-4d94-9305-89bb80ce3036)
Why does the 129GB duplex data still report this error after I added compression

**Comment by skoren** [comment]
This looks like there is no graph here at all, no edges and no sequence. What is the exact command you're running with and what coverage do you expect the duplex data to be for the genome?

**Comment by JWJ13164328557** [comment]
verkko -d /data/liux/ONT_data/tmp/GL/Genomic/verkko --hifi /data/liux/ONT_data/tmp/duplex/duplex_merge.fastq.gz  --nano /data/liux/ONT_data/tmp/2024.7.4.fastq.gz  --porec /data/liux/ONT_data/data/10-Pore-C/20240408-Pore-C-001_001-1.fastq.gz --threads 50 ,my genomic is 700M

**Comment by skoren** [comment]
So it should be 100+x? It seems this duplex data is not high quality. Have you tried counting k-mers and running genome scope on the duplex data to confirm genome size/quality?  Are you able to share it with us?

**Comment by JWJ13164328557** [comment]
The genome size is known，Can I use only ONT and porec data?

**Comment by JWJ13164328557** [comment]
I have not attempted to calculate k-mers and run genome ranges on dual data to confirm genome size/mass

**Comment by skoren** [comment]
If you have recent ONT (R10) data, you can potentially run dorado correct (aka HERRO) and use the corrected reads as HiFi + the uncorrected reads as ONT inputs to verkko (see the README for details). Still would recommend sharing the duplex data if you're able with us and/or checking the genome scope output on the k-mers from duplex data to see what is going on with it.

**Comment by JWJ13164328557** [comment]
<img width="364" alt="image" src="https://github.com/user-attachments/assets/f064e45b-2f9f-4f4d-a5c3-8278c7aff67f">
I re extracted the duplex reads from the duplex data as hifi input,but it seems that the data volume is not enough

**Comment by JWJ13164328557** [comment]
![image](https://github.com/user-attachments/assets/94c184d7-61c5-4575-a905-4a4af3865162)
After using the UL data corrected by Herro, it became normal and I was able to obtain the assembly results smoothly. Thank you very much, teacher
