### ISSUE TITLE
How to maximize the number of computing nodes 

### ISSUE THREAD

**Issue by changhan1110** [marbl/verkko#275]
Hi,

I am using a large server cluster (SGE) with more than 50 nodes to run Verkko computations. Each node is equipped with 72 CPUs and ample memory. **I’m trying to figure out how to utilize all 50 nodes effectively.**

I understand that specifying certain resource options, such as --ali-run, allows a node to maximize its computing power. However, these options don’t control the number of nodes used when the Verkko scheduler submits jobs.

My goal is to optimize resource usage and reduce computation time by fully utilizing all available nodes. 
Unfortunately, I’ve noticed that the Snakemake job scheduler often submits only a few jobs, even when there are enough nodes to handle them simultaneously. For instance, only two jobs are submitted for alignONT despite the availability of many nodes.

Thanks,
Changhan

**Comment by skoren** [comment]
It's possible you're hitting a limit on the number of jobs because the partitioning isn't creating more than two jobs because you don't have that much ONT data. It is possible to decrease the reads per partition (see `--split-bases/--split-reads` flags) but honestly I don't think it's worth the effort. There's a cost to spinning up a job and loading the index so if you partition it too much you'll just be limited by that anyway.

**Comment by changhan1110** [comment]
Thank you for the reply! It did not take too much time to run whole the process with my test dataset.

I still do not understand why all the multiple jobs cannot be submitted to all the available nodes.
Even though my data is small, my alignONT jobs are more than 100, but snakemake allows only 2 job submission simultaneously.

**Comment by skoren** [comment]
It should submit more jobs, we routinely run verkko on our slurm cluster with hundreds of jobs submitted. The default verkko limit is set to 1000 jobs in slurm so unless that's been changed via command-line or something is wrong with the slurm config, it should submit all the jobs it can.

**Comment by skoren** [comment]
Idle, no local observation of verkko limiting number of jobs submitted unless snakemake explicitly told to reduce max.
