### ISSUE TITLE
Error in the nested 8-hicPipeline

### ISSUE THREAD

**Issue by changhan1110** [marbl/verkko#276]
Hi,

I encountered an error in the very last step of `asm_sge/8-hicPipeline/final_contigs/8-hicPipeline/hic_scaff.sh` 
(not in `asm_sge/8-hicPipeline/hic_scaff.sh`! 
`asm_sge/8-hicPipeline/hic_scaff.sh` finished without error)

hic_scaff.err
```
Traceback (most recent call last):
 File "/home/kogic/miniconda3/envs/verkko/lib/verkko/scripts/rdna_scaff.py", line 75, in <module>
     short_arm_paths_ids = sf.get_arm_paths_ids(telomere_locations_file, G, paths, rdna_nodes, 100000, 5000000, False)
 File "/gpfs/home/kogic/miniconda3/envs/verkko/lib/verkko/scripts/rdna_scaff_functions.py", line 213, in get_arm_paths_ids
    aux_tel_nodes, G = get_telomeric_nodes(telomere_locations_file, old_G)
 File "/gpfs/home/kogic/miniconda3/envs/verkko/lib/verkko/scripts/rdna_scaff_functions.py", line 146, in get_telomeric_nodes
    if int(parts[2])+20000 > G.nodes[graph_node + '+']['length']:
 File "/home/kogic/miniconda3/envs/verkko/lib/python3.9/site-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
KeyError: 'haplotype1_unused_utig4-26166+'
```

I found the nested 8-hicPipeline uses the same source code used in the parental 8-hicPipeline directory, which probably made error while handling different input files; `asm_sge/8-hicPipeline/unitigs.telo` and 'asm_sge/8-hicPipeline/final_contigs/8-hicPipeline/unitigs.telo' 

Thanks,
Changhan

**Comment by skoren** [comment]
The only steps in final_contigs should be 5, 6, and 7. Nothing else. So this step shouldn't exist and isn't suprising that it failed but I'm not sure how it got to running it. I've seen the final_contigs mess up and try to re-run the assembly when files in the initial run are moved or removed, confusing snakemake's progress tracking. Usually that fails very quickly though. 

What was your verkko command, version, and snakemake version? I would suggest removing the entire final_contigs folder, running verkko with `--snakeopts touch` to update the timestamps for all the files, and re-starting the same pipeline you did initially to see what it tries to run. If it says anything besides things related to layout/consensus, it is not running correctly.

**Comment by changhan1110** [comment]
My verkko command was 
```
verkko -d asm_sge --hifi /path/to/hifi*.fa.gz --nano //path/to/ul.fastq.gz --hic1 /path/to/hic1_library.fq.gz --hic2 /path/to/hic2_library.fq.gz --sge --snakeopts "--cores 1000"
```

I will report the result of your suggestion.

**Comment by skoren** [comment]
Idle
