### ISSUE TITLE
hapmer.meryl' appears to be built using non-homopolymer compressed kmers

### ISSUE THREAD

**Issue by luanelandau** [marbl/verkko#277]
Hello, 

I am trying to run verkko with trios, but I think I have problems with meryl. I am not sure which step of the process the problem is.

First, I have used 
```
cat ../HG01944/*.fastq.gz > HG01944.fastq.gz
cat ../HG01945/*.fastq.gz > HG01945.fastq.gz
cat ../HG01946/*.fastq.gz > HG01946_SR.fastq.gz 
```
for the parents and child short reads. Then I am running 
```
meryl count compress k=30 threads=32 memory=900 HG01946_SR.fastq.gz output child_compressed.k30.meryl
meryl count compress k=30 threads=32 memory=900 HG01944.fastq.gz output maternal_compressed.k30.meryl
meryl count compress k=30 threads=32 memory=900 HG01945.fastq.gz output paternal_compressed.k30.meryl
```
and 
```
/projects/academic/omergokc/Luane/softwares/merqury/trio/hapmers.sh maternal_compressed.k30.meryl paternal_compressed.k30.meryl child_compressed.k30.meryl
```
and it seems to be working, when I run:
meryl print paternal_compressed.k30.hapmer.meryl | head

Found 1 command tree.

PROCESSING TREE #1 using 20 threads.
  opLessThan
    paternal_compressed.k30.hapmer.meryl
    print to (stdout)
ACACACACACACACACACACACTGTGACGC	6
ACACACACACACACACACACATCGCGTGTA	18
ACACACACACACACACACACATCGTACGTG	22
ACACACACACACACACACACATGCTCGAGT	10
ACACACACACACACACACACATGCTCGTCT	6
ACACACACACACACACACACATGCTGAGCG	8
ACACACACACACACACACACATGTGCTAGC	14
ACACACACACACACACACACAGAGCGCGTA	7
ACACACACACACACACACACAGAGTCGTGC	20
ACACACACACACACACACACAGTACACGCT	13

But I am having problems when running verkko:
```
Meryl database '/projects/academic/omergokc/Luane/HG01946/verkko/maternal_compressed.k30.hapmer.meryl' appears to be built using non-homopolymer compressed kmers.
Meryl database '/projects/academic/omergokc/Luane/HG01946/verkko/paternal_compressed.k30.hapmer.meryl' appears to be built using non-homopolymer compressed kmers.
```
my meryl is installed through conda and it is up to date:

meryl --version
meryl 1.4.1

Any ideas on what could be happening here? Thank you so much. 

I am attaching the .out file: 
[verkko_aug22.out.txt](https://github.com/user-attachments/files/16801933/verkko_aug22.out.txt)

**Comment by skoren** [comment]
Verso's check is looking at the dump and reporting that message it it has "AA" in the text, that's the only way to trigger the message so indeed the files provided to verkko aren't in HPC space. I suspect the issue is the path to the DB you're giving verkko isn't the same as the dump command above. What happens if you run: `meryl print /projects/academic/omergokc/Luane/HG01946/verkko/maternal_compressed.k30.hapmer.meryl | head`?

**Comment by luanelandau** [comment]
(herro) luanejan@vortex-future:/projects/academic/omergokc/Luane$ meryl print /projects/academic/omergokc/Luane/HG01946/verkko/maternal_compressed.k30.hapmer.meryl | head

Found 1 command tree.

PROCESSING TREE #1 using 20 threads.
  opLessThan
    /projects/academic/omergokc/Luane/HG01946/verkko/maternal_compressed.k30.hapmer.meryl
    print to (stdout)
ACACACACACACACACACACATACTGACGA	12
ACACACACACACACACACACATAGCGCTCT	12
ACACACACACACACACACACATCTGACTGC	6
ACACACACACACACACACACATCTGCGTCA	15
ACACACACACACACACACACATGCTCATCG	11
ACACACACACACACACACACATGCGTGTAT	14
ACACACACACACACACACACAGTACGCTCT	18
ACACACACACACACACACACAGTCGTATGT	20
ACACACACACACACACACACTACTGTCGCT	8
ACACACACACACACACACACTACGTATCAT	10

I will try to change to full path for all the input files, but im not sure what's going on.

**Comment by skoren** [comment]
Are you able to share the databases you're providing to verkko with us? It should be OK to tar.gz the full folder.

**Comment by luanelandau** [comment]
I included the full path for each of the input files and it seems like it is running normally. I am not sure why it was not reading the file that is in the same folder, but this helped. Thank you!
