### ISSUE TITLE
For --nano, use pass only? or pass and fail? 

### ISSUE THREAD

**Issue by JohnUrban** [marbl/verkko#278]
Hi all,

Thanks for the great tool (and everything in the past too).

I am helping someone with an assembly.

We have HiFi, ONT UL reads, and Hi-C.

I plan to use all 3 with Verrko.

Other than comparing the results to HiFiAsm, I really want to avoid generating many assemblies for this project, and more interested in minimizing work by following best practices.

Thus, my question above:
For the --nano option for ONT ultra-long reads, should I restrict the reads to use "pass" only? or should I also include reads that fail? 

I will say that in the past, using all reads (not just pass) with assemblers like Canu actually worked out better than just the "pass" reads. Hence why I am asking.

Thanks again!

Best,

John

**Comment by skoren** [comment]
We haven't done a lot of benchmarking with this. However, we typically pass everything and let the alignments sort it out so I'd say pass everything.

**Comment by JohnUrban** [comment]
Alright. Simple. I will just use all the reads. That was my intuition anyway from using Canu 100s of times. Using all reads usually had a slight edge probably because there is just more data. The only assembler this wasn't true for if I remember correctly was Flye (and long ago, smartdenovo ).
