### ISSUE TITLE
Release 2.2 in BioConda

### ISSUE THREAD

**Issue by gq1** [marbl/verkko#279]
When the new release can be in BioConda?
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/verkko/meta.yaml
Thanks.

**Comment by skoren** [comment]
It always takes about a week to propagate the release into conda as it takes times to test the build and have it approved. The pull request is https://github.com/bioconda/bioconda-recipes/pull/50475 so you can track it.

**Comment by kevfengler227** [comment]
verkko-2.2 is there now
