### ISSUE TITLE
Not running final consensus since no rukki paths are available!

### ISSUE THREAD

**Issue by JohnUrban** [marbl/verkko#283]
Hi all,

Thanks for all the tools and support over the years.

I recently installed Verkko 2.2 with conda.

I am trying to get it to run in both --grid and --local modes on a SLURM cluster.

So far neither have finished.

The local mode was throwing this error:
```
verkko --local --local-memory 275 -d asm --hifi ${HIFI} --nano ${ULONT} --hic1 ${HICR1} --hic2 ${HICR2}

Launching release v2.2
Using snakemake 7.32.4.
Building DAG of jobs...
LockException:
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/central/groups/carnegie_poc/jurban/data/hydra/assemblies/verkko/bortvin-only/01-default/nogrid/asm
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.
ERROR!, HiC/Pore-C phasing failed, look above for error message.
Not running final consensus since no rukki paths are available!
Verkko logging for failed commands: 

```

I then found out about `--snakeopts "--unlock"` on a different issue thread, so ran it with that, and I got this:
```
verkko --snakeopts "--unlock" --local --local-memory 275 -d asm --hifi ${HIFI} --nano ${ULONT} --hic1 ${HICR1} --hic2 ${HICR2}

Launching release v2.2
Using snakemake 7.32.4.
Unlocking working directory.
Not running final consensus since no rukki paths are available!
```

The grid mode was failing with the same message about rukki. I tried relaunching a few times, most recently with `--snakeopts touch` which I read about on a another issue thread, but it seems to be throwing the same errors. I will attach the first 2 SLURM output files in case they are helpful (too big to copy paste).
[01-slurm-43666930.out.txt](https://github.com/user-attachments/files/16936548/01-slurm-43666930.out.txt)
[02-slurm-43684559.out.txt](https://github.com/user-attachments/files/16936549/02-slurm-43684559.out.txt)

Notably the rukki message is in both:
```
01-slurm-43666930.out.txt:  Not running final consensus since no rukki paths are available!
02-slurm-43684559.out.txt:  Not running final consensus since no rukki paths are available!
```

But also a lot of:
```
Error in rule buildGraph:
...
...
Error executing rule buildGraph on cluster (jobid: 7, external: 43674725, jobscript: /central/groups/carnegie_poc/jurban/data/hydra/assemblies/verkko/bortvin-only/01-default/grid/asm/.snakemake/tmp.30kjyq3h/verkko.buildGraph.7.sh). For error details see the cluster log and the log files of the involved rule(s).
...
Error in rule buildPackages:
...
Error executing rule buildPackages on cluster (jobid: 20, external: 43676600, jobscript: /central/groups/carnegie_poc/jurban/data/hydra/assemblies/verkko/bortvin-only/01-default/grid/asm/.snakemake/tmp.30kjyq3h/verkko.buildPackages.20.sh). For error details see th
e cluster log and the log files of the involved rule(s).

```

Any guidance on how to overcome would be appreciated.

Is the rukki problem as simple as installing rukki ( https://github.com/marbl/rukki )?

I can confirm that there is no "rukki" in the conda environment -- e.g. trying to do tab completion.

And I could not find any files with rukki in their name in `/path/to/anaconda3/envs/verkko/`.

Very naive question -- how does one install rukki?

Many thanks as always.

Best,

John

EDITED: added "no" to "there is rukki in the conda environment"
--> "there is no rukki in the conda environment"

**Comment by skoren** [comment]
There isn't a problem with rukki in this run, it's reporting that it can't generate the final consensus because the initial scaffolding/consensus steps failed. I expect rukki is installed in verkko/lib/bin which isn't in the path but verkko knows where to find it. I'm not sure how the folder ended up locked, that usually only happens if you kill the snakemake script or the node it's running on fails, otherwise it cleans up after a failure. Either that or the local run was launched while the slurm run was still going.

It looks like the buildPackages (which loads all the reads into memory) is getting Killed on your cluster. Requesting more memory explicitly should help, try adding `--par-run 1 100 24`, that should request 100gb for the same job and re-launch and see if it completes then.

**Comment by JohnUrban** [comment]
Ok - just getting back to this today.

- Rukki not the problem. Got it
- I can confirm that rukki is included here: `./anaconda3/envs/verkko/lib/verkko/bin/rukki`
- "Either that or the local run was launched while the slurm run was still going."
   -- I had both the grid run and local run going at the same time, but they were on different nodes... 
   -- Is that not possible? Only one run at a time?
- `--par-run 1 100 24` -- I will try this, and report back. I am re-launching the job anew though.

**Comment by skoren** [comment]
Sounds good, re "-- I had both the grid run and local run going at the same time, but they were on different nodes..." do you mean different assemblies? They can't share the same `-d folder` otherwise it should be fine to run multiple runs.

**Comment by JohnUrban** [comment]
Different assemblies, yes; not the same `-d folder`. 
So then that wouldn't be why the lock was happening. Still a mystery I guess.

**Comment by JohnUrban** [comment]
Thanks for getting back so fast. Okay - great that it is done. 

I will also note that I was told to expect a 300 Mb across 15 chromosomes. 

If I were to use something like YaHS to further Hi-C scaffold, would you recommend using the haplotype assemblies separately?

And is it default to expect "haplotype 1" to be better in some way (e.g. higher BUSCO completeness) than haplotype 2? 
(I guess I am still thinking about it as "primary" vs "associated" like in the days of old.)

I am assuming at the moment that when the researchers inevitably ask, "So which file should we use as our reference genome?", that I could tell them to just use `assembly.haplotype1.fasta` for most of the standard needs -- e.g. ChIP-seq analyses. Is that acceptable? Seems like forward-looking would be to use some GFA approach, but for now they will be using the more traditional single reference genome approaches.

**Comment by skoren** [comment]
Given that you have an assembly, I think this is resolved? Please re-open if I'm incorrect.

**Comment by JohnUrban** [comment]
You're right. The original issue is for sure resolved. Thanks again.
