### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by handesome** [marbl/verkko#284]
Hi!when I download verkko from the release.I got the error
```
$ make -j 8
g++: fatal error: no input files
compilation terminated.
g++: error: unrecognized command line option ‘-std=c++2a
Makefile:375: 
Makefile:376: Unable to compile OpenMP programs with with:
```
could anyone give some advice?

**Comment by skoren** [comment]
It looks like you have an incorrectly configured compiler on your system. It's easier to install with conda which handles the compilation for you instead.

**Comment by skoren** [comment]
Idle, looks like a compiler version issue.
