### ISSUE TITLE
Computing resource utilization is very low

### ISSUE THREAD

**Issue by sh0rt2l0ng** [marbl/verkko#285]
Hello Verkko team, we are recently trying to test the nanopore-only T2T workflow with verkko on a r5.16xlarge instance. But from our observation, verkko persistently has a low utilization of the available computing resources for each task with snakemake. May we know if there is a recommended way to boost the performance via any parameters or configuration? Any guideline for this would be appreciated. Thanks!
![image](https://github.com/user-attachments/assets/f8376cbb-7c7c-40c4-b84e-2c88058edd18)

**Comment by sh0rt2l0ng** [comment]
Hi Verkko team, I am not sure if there is any recommendation on how to optimize the cores used by time-consuming steps so that the assembly can be accelerated. I tried to increase those 'cpus' numbers in verrko script to maximum local cpus and 'mem' to 0 for all steps and but got segment dump.

**Comment by skoren** [comment]
Verkko defaults to 64gb on a local node and not all the cores so you want to set those with `--local-memory` and `--local-cpus` to whatever is available. Snakemake will then schedule the right number of jobs for each parallel task to utilize those. There will still never be perfect parallelization, there are single-threaded steps in the computation (for the utgcns the alignment of reads is parallel but the final consensus has to be called by a single thread).

**Comment by sh0rt2l0ng** [comment]
Thanks a lot! We did set --local-memory and --local-cpus according to available resources. But yes, as you said, the utilization is still high. And it seems we are entering the final consensus step. Really hope we can optimize the performance further in future.
![image](https://github.com/user-attachments/assets/d3048ab4-e779-4d5e-830c-dca173750b5a)

**Comment by skoren** [comment]
Idle, improved detection of local resources.

**Comment by tfogler** [comment]
Hi MarBL, I have been experiencing similar issues with my run. My command is `nohup verkko -d asm --hifi *.fastq.gz --nano *.fq.gz --threads 32 --sto-run 32 128 24 --ovb-run 32 128 24 ...... --fhc-run 32 128 24 &`; basically all steps set to maximum local cpus and maximum memory, but snakemake would only assign 1 cpu to each step. What's more, it failed in the computeErrors step. I tried to increase the resources used but it would either have the same behavior or fail.

Screenshots:
Compute Errors Logfile
![image](https://github.com/user-attachments/assets/b3330254-76c0-4cf3-b7be-32205bd9fa88)

StdOut [n_cpus is 32]
![image](https://github.com/user-attachments/assets/cc2f7097-742a-467f-aad1-f5b0c841952d)

![image](https://github.com/user-attachments/assets/639109d2-e14f-49b6-99dd-7df5c0100ae9)

**Comment by AndreaGuarracino** [comment]
@skoren I have the same problem. I installed `verkko` 2.2.1 via `conda` and after getting extremely long runtime, I noticed that, for example, `GraphAligner` only ran with 1 thread.

**Comment by skoren** [comment]
Some steps are only supposed to use one thread or are limited by system memory. You can compare the request/snakemake info for the job to the utilization you see. Graphaligner indexing is only single-threaded but the alignments aren't so it's quite possible your run is working correctly. The runtime varies by sample and input coverage.

**Comment by tfogler** [comment]
@skoren I resolved this issue by running with the --local_cpus option, rather than n_cpus. 

```
nohup verkko --threads 32 --local-cpus 32 \
-d asm --hifi *.fasta.gz --nano *.fq.gz &
```

**Comment by skoren** [comment]
Thanks @tfogler, I think the 2.2.1 version should auto-detect the local CPU so it shouldn't be necessary to set the local cpus anymore.

**Comment by tfogler** [comment]
FYI, I am using the conda distribution of v 2.2.1. In my case it didn't auto-detect local cpus.

________________________________
