### ISSUE TITLE
Chromosome 9 assembles worse with Verkko 2.2

### ISSUE THREAD

**Issue by tbenavi1** [marbl/verkko#286]
Hello,

With Verkko 2.2, we get T2T length sequences for nearly all the chromosomes for our sample. However, we noticed that for chromosome 9, the assembly phasing was actually worse. Previously using the same data (with Verkko 2.1 I believe), the centromere region was not fully resolved and was in multiple pieces. However the chromosome arms were complete and phased. With 2.2, the centromere region is in one complete piece and phased. However, the chromosome arms are now no longer phased. See the bandage plot below:

![chr9_graph](https://github.com/user-attachments/assets/f2803f77-69ce-4bef-b7e9-c6f5d0a2d24f)

Perhaps the phasing is having some issues now that the long centromere of chromosome 9 is resolved? Thanks for any insights. I'd be happy to provide any more information/data to help debug this issue.

**Comment by Dmitry-Antipov** [comment]
Hi,
Could you share

assembly.homopolymer-compressed.noseq.gfa
assembly.colors.csv
8-hicPipeline/hicverkko.log
8-hicPipeline/hic_phasing.err
8-hicPipeline/hic.byread.compressed

**Comment by tbenavi1** [comment]
Hello, I have uploaded the files here: https://drive.google.com/drive/folders/1F2NHim9ZNsI92lKe9M6MU3VScjlsMspe?usp=drive_link

Please let me know if you are able to download them. Thanks for looking into the issue.

**Comment by Dmitry-Antipov** [comment]
Downloaded, and already know what happened.
chr9-related nodes has significantly different coverage in this assembly, and I found a bug related to such cases just after v2.2 was released.

So, you can just reinstall verkko from current master or replace lib/verkko/scripts/cluster.py in your verkko installation with current version (https://github.com/marbl/verkko/blob/master/src/scripts/cluster.py)

**Comment by tbenavi1** [comment]
Thank you so much! I'll use the new version. I have a question about the lower coverage. Is this due to some way that the data is processed? I did align the ONT reads to T2T chm13 and noticed that the coverage was slightly lower for chromosome 9 than the others. The average mapq was also lower.  What is the reason for the significant difference in coverage for the verkko nodes? Anyway, it doesn't much matter if the issue is fixed. Thanks.

**Comment by Dmitry-Antipov** [comment]
Do you use Revio HiFi? We noticed problems with revio on chr9 in multiple datasets, related to the sequence content. @skoren can clarify exact reason better.

**Comment by skoren** [comment]
The coverage/dropout only affects HiFi data not ONT. The reason seems to be 24 hour movies bias against molecules that need longer to sequence which affects the HSat on chr9 and, to a lesser extent, chr16. The 30hr movies mostly correct for this dropout. The reason you're seeing a lower coverage when mapping ONT to chr9 in CHM13 is that CHM13 has a large duplication of the chr9 region that probably isn't present in your sample, leading to lower coverage.

**Comment by tbenavi1** [comment]
Hello, I replaced my version of lib/verkko/scripts/cluster.py. However, I was wondering if there would be a way to restart the assembly from only the first step that needs to be rerun? That way I can avoid rerunning everything. When I did a dry run with snakemake, it said there was nothing to be done. Is there some file I can delete, or some way to force a rerun? Thanks for any advice.

**Comment by Dmitry-Antipov** [comment]
You can delete all fastas in the results folder, 8-hicPipeline/final_contigs/ and 8-hicPipeline/*.tsv 
There should be something like 
```
job                     count    min threads    max threads
--------------------  -------  -------------  -------------                                                                               
HiC_rdnascaff               1              8              8                                                                               
hicPhasing                  1              8              8
prepareScaffolding          1              8              8
runRukkiHIC                 1              8              8         
scaffoldMergeBWA            1              8              8
scaffoldPrefilterBAM        1             24             24         
total                       6              8             24         
``` 
as a result of dry run, bug relates to hicPhasing stage.

Just in case - verkko runs snakemake pipeline twice with hi-c (consensus in final_contigs folder), so rerunning just ./snakemake.sh from the assembly folder will be not enough. You should use verkko.sh to rerun after dry-run checks.

**Comment by tbenavi1** [comment]
Hello, after changing the cluster.py file, I still get exactly the same assembly.fasta file. Some of the intermediate 8-hicPipeline/*.tsv files are different. I have also uploaded all the new files to this folder:   https://drive.google.com/drive/folders/18wzVMNXxxyOs7fCEQjDNQ27BpUxviN7l?usp=drive_link Let me know if there is anything else you need from me. Thank you.

**Comment by Dmitry-Antipov** [comment]
Hi,
According to the new assembly.colors,csv, phasing now worked correctly.

Could you also share rukki.paths.tsv and scaffolding.log from 8-hicPipeline accomplished with verkko's console output? If it was not saved,  most recent log files in ./snakemake/logs/ and 8-hicPipeline/final_contigs/.snakemake/logs/ will work instead.

**Comment by tbenavi1** [comment]
I just added the new files to the same folder. Thanks.

**Comment by Dmitry-Antipov** [comment]
Paths are also correct - according to them chr9 should be T2T or close to T2T. I do not see anything suspicious in logs also

Current assumption is that something went wrong with copying files outside of snakemake.

Can you check, are assembly.fasta in <assembly_dir> and in <assembly_dir>/8-hicPipeline/final_contigs/ same? 
also could you add 8-hicPipeline/final_contigs/6-layoutContigs/unitig-popped.layout.scfmap, 8-hicPipeline/final_contigs/6-layoutContigs/consensus_paths.txt and 8-hicPipeline/rukki.paths.gaf to the shared folder?

**Comment by tbenavi1** [comment]
I checked that the two files are identical with "diff -s":
```
Files assembly.fasta and 8-hicPipeline/final_contigs/assembly.fasta are identical
```

I added the new files to the folder.

**Comment by Dmitry-Antipov** [comment]
Are you sure that you clean 8-hicPipeline/final_contigs/ completely prior to the rerun?

I'm asking since 8-hicPipeline/final_contigs/6-layoutContigs/consensus_paths.txt should be identical to 8-hicPipeline/rukki.paths.gaf (it is copied in verkko.sh if 8-hicPipeline/final_contigs/6-layoutContigs/ does not exist), but according to both file content and timestamps it seems that consensus_paths.txt was generated by previous run.

May I ask to try to reproduce it once again? Delete  all fastas in the assembly results folder, 8-hicPipeline/final_contigs/ completely (you can leave 8-hicPipeline/*.tsv this time - they are already OK), rerun verkko.sh redirecting its output to stdout and stderr to a file and check whether consensus_paths.txt is different to rukki.paths.gaf? Files are copied before snakemake pipeline, so if you see that consensus_paths.txt is created and is not same to rukki.paths.gaf, pipeline can be terminated.

**Comment by tbenavi1** [comment]
I moved the entire folder 8-hicPipeline/final_contigs/ to 8-hicPipeline/final_contigs_old/ prior to rerunning. But I will try to reproduce with your steps above.

**Comment by tbenavi1** [comment]
Thank you, this fixed my issue. I am not sure why it didn't work the first time.
