### ISSUE TITLE
Verkko+Hi-C performance problems on complex graphs (datasest without ultralong ONT)

### ISSUE THREAD

**Issue by tbenavi1** [marbl/verkko#287]
Hello, 

I have a couple of samples where we ran verkko 2.1 assemblies with no problem, but with verkko 2.2 they have errors on the hicPhasing step. Specifically, when I check the output of 8-hicPipeline/hic_phasing.err, it says that the job was killed. So, I ran with --fhc-run 8 512 24 --shc-run 8 512 24 to increase the memory. After rerunning, the assembly still failed to complete, and I am having difficulty figuring out what went wrong. There is a 26GB scaffolding.log file which I can upload if you think it will be useful. Thanks for any suggestions.

**Comment by Dmitry-Antipov** [comment]
Hi,
Can you share verkko's console output? If it was not saved to file , two snakemake log files will work  .snakemake/log/*.snakemake.log and 8-hicPipeline/final_contigs/.snakemake/log/*.snakemake.log

**Comment by tbenavi1** [comment]
[2024-09-13T054140.633180.snakemake.log](https://github.com/user-attachments/files/17017362/2024-09-13T054140.633180.snakemake.log)
And there is no final_contigs folder in 8-hicPipeline.

**Comment by Dmitry-Antipov** [comment]
According to that log looks like scaffolding is still running (and so no final_contigs is normal)
If corresponding job 12607296 crashed or finished, can you send us scaffolding.log with DEBUG lines excluded (grep -v DEBUG scaffolding.log)? It shouldn't be huge.

If it is still running, let's just wait.

**Comment by tbenavi1** [comment]
I see. It must have gotten canceled because it ran past the time limit. Here is the log with DEBUG lines excluded. 
[scaffolding.nodebug.log](https://github.com/user-attachments/files/17017556/scaffolding.nodebug.log)

**Comment by Dmitry-Antipov** [comment]
Seems that your assembly graph has way more nodes than we used to. "ScaffoldGraph - Total nodes 160544"
Usually in human-sized assemblies we see just couple thousands of nodes. Which species are you assembling? And do you use ONT reads or it is HiFi + Hi-C assembly?

I'll either add some optimizations or add "no scaffolding" option (in v2.1 we had only phasing with hi-c and not scaffolding), but complexity of graph already says that you likely will not get decent assembly.

For now you can run verkko with phasing-generated paths excluding scaffolding: ./bin/verkko --paths <prebious assembly>/8-hicPipeline/prescaf_rukki.paths.gaf  --assembly <previous assembly> -d <new output dir> --hifi  <> --ont <>

**Comment by tbenavi1** [comment]
That makes sense. For this sample, the data is quite poor. It is a human assembly. We have HiFi (30x) + Hi-C + ONT (only 7x, and the N50 read length is 7kbp).

**Comment by Dmitry-Antipov** [comment]
Well, as soon as you have decent hifi data, _short_ ONT reads should be quite useless. So although recipe with phasing-generated paths that I suggested above should work, I do not expect to achieve decent assembly. For now  I'd actually try hifiasm first for hifi + hi-c combo - we didn't spend a lot of time optimizing verkko on such datasets.

But anyway, thank you for pointing on the performance problem!

**Comment by tbenavi1** [comment]
Thank you!

**Comment by Dmitry-Antipov** [comment]
For the recent 2.2.1 release we've improved scaffolding performance on fragmented assembly graphs (HiFi + Hi-C or HiFi + Hi-C + short ONT like in this case). However, I'd still not consider verkko as a first choice tool for the assemblies without ONT data because of the lack of testing.

**Comment by tbenavi1** [comment]
Hello, with version 2.2.1, the assembly was finally able to finish with no problems. However, the assembly is much worse than when assembling the data with version 2.1. In particular, a lot more sequence is in assembly.unassigned.fasta than previously.

**Comment by Dmitry-Antipov** [comment]
Thank you for checking, that's not what I would expect.

Is the assembly less contiguous (N50-like metrics) too? Or just more contigs are unassigned? 
Can you share
 8-hicPipeline/prescaf_rukki.paths.tsv
8-hicPipeline/scaff_rukki.paths.tsv
8-hicPipeline/hicverkko.colors.tsv
8-hicPipeline/unitigs.hpc.noseq.gfa
from both assemblies? Those files should be relatively small.

**Comment by tbenavi1** [comment]
Hello,

The assembly is less contiguous. Here is the previous Nchart: 
![BLPt0001 verkko Nchart](https://github.com/user-attachments/assets/83ee369b-39cb-4839-b7b6-98e6ec0133ca)

Here is the current Nchart:
![BLPt0001 verkko Nchart](https://github.com/user-attachments/assets/bc4a5209-f833-4653-af38-7b100ba58449)

I unfortunately don't have the files above for the old assembly (though I can regenerate them if that would be helpful). Our cluster deletes files from scratch every 30 days. I have uploaded the new versions of those files here https://drive.google.com/drive/folders/1KFKzCtvmdFreMHiN2rEJZp3Ze9is9KOO?usp=sharing

**Comment by tbenavi1** [comment]
Oh, and I should also note that the Ncharts above are only from the haplotype1 and haplotype2 reads. Any other reads are not included.

**Comment by tbenavi1** [comment]
I don't have anything remaining from the older run. I'll kick it off with verkko 2.1 and send you the files when I have them. I added the files you requested from the current run.

**Comment by tbenavi1** [comment]
Hello, I am running this sample with verkko 2.1. However, I received the following error in 8-hicPipeline/run_mashmap.err:
```
---Running MashMap
/tgen_labs/barthel/software/miniforge3/envs/verkko2.1/bin/mashmap: error while loading shared libraries: libblis.so.4: cannot open shared object file: No such file or directory
```

I installed verkko with
```
conda create -n verkko2.1 -c conda-forge -c bioconda -c defaults verkko=2.1
```

I was able to resolve the issue with
```
conda install conda-forge::blis
```

I just wanted to let you know in case it was something that needed to be fixed. I'll finish the assembly and upload the files soon.

**Comment by tbenavi1** [comment]
The verkko 2.1 assembly finished, but the results look similar to the verkko 2.2 assembly and are not the same as my previous verkko 2.1 assembly. However, one difference is that in the latest assemblies I gave the herro corrected ONT reads as hifi. So, to summarize: 
Previous verkko 2.1 assembly = didn't give herro corrected ONT reads as hifi reads, less sequence in unassigned.fasta.
Current verkko 2.1 assembly = gave herro corrected ONT reads as hifi reads, more sequence in unassigned.fasta.
Current verkko 2.2 assembly = gave herro corrected ONT reads as hifi reads, more sequence in unassigned.fasta. 
Let me know if you want any more files from me. Thanks.

**Comment by skoren** [comment]
Are there R9 or R10 herro corrected reads? The reads can introduce noise in the initial graph which harms resolution. You can see if this happened by comparing the end of the `1-buildGraph/buildGraph.err` log file to check for node/edge counts, N50, and total graph bases with herro data and without. You can likely adjust the `--unitig-abundance` parameter to reduce the recurrent noise in the graph (see #289) if that is the cause of the issue.

**Comment by Dmitry-Antipov** [comment]
So likely the decrease happened not between the versions but because of admixturing herro reads.
I'd expect them to be of quite low quality because of low ONT coverage and length.

Also what is the Hi-C coverage? I see very few links from pretty long nodes..

**Comment by tbenavi1** [comment]
It is R10 herro corrected reads. I'll look into your suggestions @skoren. The Hi-C coverage for this sample is 15.5x, so definitely lower coverage. I think the decrease in quality due to admixing herro reads makes sense.
