### ISSUE TITLE
Verkko using Nanopore reads？

### ISSUE THREAD

**Issue by handesome** [marbl/verkko#292]
Hi！Could Verkko only using ONT reads or hi-fi reads?If possible, how to use the single reads to assmbly chromosomes .Thanks!!

**Comment by skoren** [comment]
You can't provide regular ONT simplex data as input to verkko. If you have recent R10 data, you can try HERRO correction and running verkko with those corrected reads as the --hifi input (the uncorrected can be input as --nano), see README for info. I wouldn't recommend this for R9 data.

**Comment by handesome** [comment]
Thank you for quick reply! i got it!
