### ISSUE TITLE
PoreC and trio run together

### ISSUE THREAD

**Issue by KANGYUlab** [marbl/verkko#293]
Hi,
when I run verkko v2.2.1 : 
`verkko -d verkko2.2.1  --hifi hifi_reads.fa.gz  --nano nano.fq.gz  --hap-kmers m.hapmer.meryl p.hapmer.meryl trio  --porec poreC.fastq `
report:
"Both --hic1/--hic2 or --porec cannot be specified at the same time as trio information, please only specify ont"
PoreC and trio cannot work at the same time in verkko v2.2.1, is it right ?

**Comment by skoren** [comment]
It was never supported and would crash if ran that way. Verkko 2.2.1 just explicitly forbids this immediately to avoid crashing later. It is possible to chain together a trio run followed by Pore-C for scaffolding manually but doing that requires copying/symlinking the internals of verkko's output and so isn't generally recommended. I'd suggest instead using Pore-C and then using the trio to sort the haplotypes at the end and use it for validation.

**Comment by skoren** [comment]
I'm going to close this since this is the expected functionality and we do not currently allow mixing Hi-C + trio data for a run. We have a separate feature request issue (#193) to track allowing this combination in the future.
