### ISSUE TITLE
verkko using both hifi reads and herro-corrected ONT reads

### ISSUE THREAD

**Issue by DustinSokolowski** [marbl/verkko#296]
Hello!

Thank you for your continued support with this tool. I see that we should use the herro-corrected ONT reads in the `--hifi` slot, but I also have hifi data.

Do you know if verkko would play nicely with the `--hifi` input being `cat hifi.fq.gz ONT-herro.fq.gz > Q20.fq.gz` or would you recommend a different way to include both reads within `--hifi` ?

Best,
Dustin

**Comment by skoren** [comment]
Yes, you can do that or specify each file individually (verkko accepts arbitrary numbers of hifi or ONT input files). See #289 for some considerations about changing parameters if you end up with high coverage from the combo of data types.

**Comment by DustinSokolowski** [comment]
Hey Sergey,

Thank you for the fast and thorough answer. I am running verkko with both options to compare. I'll re-open if I see something unusual that I think may be helpful to you.

Dustin
