### ISSUE TITLE
Commercial License

### ISSUE THREAD

**Issue by sh0rt2l0ng** [marbl/verkko#299]
Dear Verkko author, just want to clarify what kind of license is currently applied to Verkko. Do we need any commercial license in order to use it for profit? Thanks!

**Comment by skoren** [comment]
Verkko itself is public domain being a govt work. Some of the dependencies have their own licensing. For example, Canu is GPL2 while MBG is MIT. I don' think any of the licenses preclude commercial use but all the packages and dependencies should have a README.license or similar if you want to confirm
