### ISSUE TITLE
Do the ONT data and hifi data have to come from the same sample?

### ISSUE THREAD

**Issue by heziqing** [marbl/verkko#300]
Hello, I just have HiFi data, but I could download published ONT data for the same species. Can I use this data to assist in assembling?

**Comment by skoren** [comment]
I would not recommend using ONT data from a different individual. The ONT reads are used to phase the HiFi graph as well as resolve repeat copy number/etc and this will vary between individuals.

**Comment by heziqing** [comment]
OK, Thanks for your reply!
