### ISSUE TITLE
Assembly graph in non-hpc space

### ISSUE THREAD

**Issue by diego-rt** [marbl/verkko#302]
Hey there,

Is there a way to obtain the assembly graph in non-hpc space? 

I am aware one could take the hpc graph and substitute the sequences and node names according to the fasta file and scfmap file, but this is not ideal since some unitigs can be missing from the assembly.fasta file and the CIGAR/overlaps of the L entries in the GFA file would be incorrect. 

I would like to use this graph to align ONT reads to it using GraphAligner.

Thanks a lot in advance!

**Comment by skoren** [comment]
It is possible to translate the GFA using the consensus for graph nodes. Look at this script from our deprecated Hi-C support pipeline: https://github.com/skoren/verkkohic/blob/master/uncompress.sh. You'd want to use the combined.fasta sequence in 7-consensus and verkko should be run w/o trio or Hi-C information so each node gets its own sequence. This GFA will have non-perfect overlaps with full cigar strings which many GFA tools (like bandage) don't handle.

If you're only trying to map via GraphAligner, you can map uncompressed reads to a compressed graph, GraphAligner handles this for you. This is how it is used within verkko already. Verkko also allows you to generate consensus for custom paths in the graph you produce yourself. Take a look at the `--paths` option on the README.

**Comment by diego-rt** [comment]
Great, thanks a lot! Do you know if GraphAligner can handle those overlaps/CIGARs? 

I am trying to correct my ONT reads by aligning to the assembly graph and outputting the corrected reads using GraphAligner. Afterwards assembling using hifiasm or verkko with large k's is yielding better resolved assemblies in some cases (satellites). I guess this is somehow analogous to hifiasm's integer graph but using verkko. Hifiasm can't handle large satellites because of a hard cap on k-mer multiplicity (4096). So far I have been aligning to a manually generated MBG graph, but this graph is obviosuly much less resolved than verkko's, so I expect better results if I could align to verkko's graph.

Do you have any experience with an approach like this?

**Comment by skoren** [comment]
I'm not sure, you probably want to check on the GraphAligner GitHub page about that. There have been tools to correct via graph alignment, for example LJA uses this to improve the HiFi reads before assembly.

**Comment by diego-rt** [comment]
Indeed it seems like GraphAligner also doesn't accept full CIGAR strings in its overlaps, so I guess I'll try to clean up the graph and see if I can get it to work. Although if the graph ends up being similarly complex to the raw MBG one I guess there is not much point. 

However, while doing so I realised that the compressed graph and the uncompressed graph generated by `uncompress.sh` differ in a small number of links. As in, before uncompressing I used to have 1 component and now I have 2. Is it expected to lose links during the uncompression process?

Many thanks once again!

**Comment by diego-rt** [comment]
Yes you are right, I guess I'll stick to the MBG graph and try to tune GraphAligner's settings as greedily as possible. 

Thanks a ton for all your advice!

**Comment by diego-rt** [comment]
Hi,

Sorry one last thing. I can't seem to get verkko to build the paths starting from an existing assembly. It seems to want to re-run everything. I noticed that in your latest commits you implemented something in this direction. What would be the way to get this to work on verkko 2.2.1 ?

Since the process was run on a scratch filesystem, the original read files dont exist anymore and therefore I would like to provide the same files again rather than tracking them down from the yaml file.

```
(verkko221) [diego.terrones@clip-m2-1 paths]$ verkko --assembly verkko_graph_correction_hybrid --paths paths.txt --hifi reads/graph_correction_hybrid/ONT_reads.graph_corrected.clipped.fa.gz --nano reads/ont_reads.fastq.gz -d manual_paths
Launching release v2.2.1
Using snakemake 7.32.4.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 152
Rules claiming more threads will be scaled down.
Provided resources: mem_gb=1448
Job stats:
job                            count
---------------------------  -------
alignONT                           1
buildGraph                         1
buildPackages                      1
buildStore                         1
cnspath                            1
combineConsensus                   1
combineONT                         1
combineTipsONT                     1
correctHiFi                        1
extractONT                         1
fixErrors                          1
generateLayoutContigsInputs        1
indexGraph                         1
layoutContigs                      1
processGraph                       1
processONT                         1
splitONT                           1
splitTipsONT                       1
untip                              1
total                             19

Select jobs to execute...

[Fri Nov 22 23:37:48 2024]
rule buildStore:
    input: /scratch-cbe/users/diego.terrones/dorado_correction/chr2_005/241119/paths/reads/graph_correction_hybrid/ONT_reads.graph_corrected.clipped.fa.gz
    output: 0-correction/hifi.seqStore
    log: 0-correction/buildStore.err
    jobid: 7
    reason: Forced execution
    resources: tmpdir=/tmp, job_id=1, n_cpus=1, mem_gb=4, time_h=4


[Fri Nov 22 23:37:48 2024]
checkpoint splitONT:
    input: /scratch-cbe/users/diego.terrones/dorado_correction/chr2_005/241119/paths/reads/ont_reads.fastq.gz
    output: 3-align/splitONT.finished, 3-align/splitONT.ids
    log: 3-align/splitONT.err
    jobid: 10
    reason: Forced execution
    resources: tmpdir=/tmp, job_id=1, n_cpus=1, mem_gb=8, time_h=96
DAG of jobs will be updated after completion.
```

**Comment by skoren** [comment]
Snakemake relies on timestamps so if the asm folder was copied without `-p` or if the input sequence have newer timetamps than the assembly then it wouldn't work as snakemake thinks all the assembly results are outdated. In your log it says the input file timestamp is newer than the original run. The original asm isn't touched when you run `--paths`, it makes copies of some relevant files and runs in a new folder.

**Comment by diego-rt** [comment]
Yes you are totally right. I fixed that but even then I could not get verkko to resume properly. 

In case it is useful for anyone, this is how I got it to resume nicely and go straight to `--path` computation when restarting the run at a new location.

```
#fix timestamps
verkko -d ${assembly} --hifi ${assembly}/reads/hifi_reads.fasta.gz --nano ${assembly}/reads/ont_reads.fastq.gz --local --local-memory ${task.memory.toGiga()} --local-cpus ${task.cpus} --snakeopts "--touch --forceall"

#copy assembly to manual_paths manually since it reruns everything when verkko handles it
cp -p -r ${assembly} manual_paths
rm -rf manual_paths/6-layoutContigs/
rm -rf manual_paths/7-consensus/
rm -rf manual_paths/assembly.*

#generate custom paths
verkko --assembly ${assembly} --paths ${paths} -d manual_paths --hifi ${assembly}/reads/hifi_reads.fasta.gz --nano ${assembly}/reads/ont_reads.fastq.gz --local --local-memory ${task.memory.toGiga()} --local-cpus ${task.cpus}
```
