### ISSUE TITLE
Combine PoreC phasing of Verrko and GFAse

### ISSUE THREAD

**Issue by caspargross** [marbl/verkko#305]
Hi, 

I am currently investigating different phasing approaches with PoreC for a Nanopore only assembly (Duplex/Herro + UL).
In [this](doi.org/10.1038/s41576-024-00718-w) recent review by Heng Li and Richard Durbin I stumbled over the following sentence:

> Verkko can optionally take GFAse phasing and phase entire chromosomes 

What is implied by this and how does this work? Is there a pipeline available somwhere that I could look at?
I am aware of two options at the time: A) Just use the PoreC phasing integrated in Verkko B) Decompress and rename the Verkko graph and phase with GFAse. Is there another way to do it?

Thanks, Caspar

**Comment by skoren** [comment]
I would recommend the native Pore-C integration which you can just run by providing the data to verkko with the rest of your inputs. The GFAse pipeline is older and doesn't support scaffolding, only phasing.
