### ISSUE TITLE
Contig names in custom paths

### ISSUE THREAD

**Issue by diego-rt** [marbl/verkko#307]
Hey again,

Is there a way to define the name of the contigs derived from custom paths? My path file is of the form:

```
hap1	>utig4-0>utig4-4<utig4-2	HAPLOTYPE1
hap2	>utig4-1>utig4-4<utig4-3	HAPLOTYPE2
```

But somehow the sequence names in the output are contig-000001, etc and not "hap1". Is there a way such that verkko names these sequences according to the names provided in the path file? I assumed this was possible since the readme says this file should take the form `name >utig4-1<utig4-2 HAPLOTYPE1` so I don't know if I'm doing something wrong.

Along similar lines, do you know of any solution for automatically determining a valid path between two nodes? I've been manually deriving some using bandage but was wondering if you know of any automated solution to derive arbitrary pseudohaplotype paths. 

Many thanks as always!

**Comment by skoren** [comment]
The names come from the scfmap file in the 6-layoutContigs file. If you update the `path XX XX` lines to use your final name and re-run the consensus, it should update the names. There's also a utility script in verkko that will rename contigs `python <path to verkko>/lib/verkko/scripts/fasta_combine.py rename <output fasta> <name map> <input fasta>` which you can pass the names from the scfmap file again to rename back to your original names in the paths.gaf.
