### ISSUE TITLE
Estimate and request memory dynamically

### ISSUE THREAD

**Issue by skoren** [marbl/verkko#34]
Currently fixed at 160g which is too much for many cases. Use graph size to estimate memory needed to indexing and request dynamically.

**Comment by skoren** [comment]
Some other steps that request a large memory amount and could be dynamic are:
consensus partitioning - size of input HiFi data
consensus - based on depth and largest contig size

others requesting >=64gb but not clear if we can predict size
MBG construction
layout construction
utg/utp stepas

**Comment by skoren** [comment]
Indexing addressed in 7a3ab0eb5ea8b26717b51f486de1ca76c44e3a15. Rest remain

**Comment by oushujun** [comment]
Is that a way to set local memory? In the verkko script it is set to a small value.

```
grid="local"
local_cpus=all
local_mem=64
```

**Comment by skoren** [comment]
No, this is related to the grid job requests. Local resources already have parameter, `--local-memory` and `--local-cpu`.

**Comment by skoren** [comment]
With latest changes, the only things not parameterized are MBG construction and package building (which should be linear in read size)

**Comment by skoren** [comment]
MBG should require 1/3 of input read size.

**Comment by skoren** [comment]
Done
