### ISSUE TITLE
MBG: Assertion `fwHash != bwHash' failed

### ISSUE THREAD

**Issue by oushujun** [marbl/verkko#48]
Hello,

I encountered an error with one of the dataset I am testing. Other runs are fine. I tried with both `--slurm` and local execution and have the same error:

>[Sun Feb 13 15:20:40 2022]
Error in rule buildGraph:
    jobid: 4
    output: 1-buildGraph/hifi-resolved.gfa, 1-buildGraph/hifi_nodecov.csv, 1-buildGraph/paths.gaf
    log: 1-buildGraph/buildGraph.err (check log file(s) for error message)
    shell:
        
### 1-buildGraph/buildGraph.err 

>MBG bioconda 1.0.8
Parameters: k=1001,w=100,a=1,u=2,t=8,r=15000,errormasking=collapse-msat,endkmers=no,blunt=no
Collecting selected k-mers
Reading sequences from ../hifi-corrected.fasta
MBG: src/HashList.cpp:116: std::pair<std::pair<long unsigned int, bool>, __int128 unsigned> HashList::addNode(VectorView<short unsigned int>, VectorView<short unsigned int>): Assertion `fwHash != bwHash' failed.
./buildGraph.sh: line 39: 21142 Aborted                 (core dumped) /data/mschatz1/oushujun/bin/miniconda3/envs/asm/bin/MBG $iopt -t 8 -k 1001 -r 15000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --out ../1-buildGraph/hifi-resolved.gfa

Do I need to filter the HiFi data? Thanks!

Shujun

**Comment by maickrau** [comment]
This was a bug in MBG. Could you try compiling the latest version of [MBG](https://github.com/maickrau/MBG) (commit [d04c73b](https://github.com/maickrau/MBG/commit/d04c73bee483bdd1db8322da8289450bc2c6ddcc)) and then when running Verkko give it the path to the compiled MBG binary as a parameter: `--mbg /path_to_mbg/bin/MBG`

**Comment by oushujun** [comment]
This is an MBG issue, but I still cannot compile MBG on my HPC. Is that an updated MBG available on conda?

**Comment by skoren** [comment]
Yes, there is a new version of MBG on conda

**Comment by oushujun** [comment]
Great! Will try it out today.
