### ISSUE TITLE
beta2: MBG Assertion fail canTrimRecursive

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#57]
Hi,
in Verkko beta2 (via bioconda), the following assertion fails during the initial graph construction:
```
MBG: src/UnitigResolver.cpp:2111: bool canTrimRecursive(ResolvableUnitigGraph&, std::vector<PathGroup>&, std::pair<long unsigned int, bool>, size_t): Assertion `overlap < resolvableGraph.unitigs[pos.first].size()' failed.
./buildGraph.sh: line 39: 76075 Aborted
/[path_omitted]/bin/MBG $iopt -t 4 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --out ../1-buildGraph/hifi-resolved.gfa
```
As usual, I can share debug data via Globus.

Best,
Peter

**Comment by maickrau** [comment]
Could you share the hifi-corrected.fa via Globus

**Comment by ptrebert** [comment]
I am transferring the data now to `T2T:/Verkko_test-data/github-issue-57/`
There seems to be a bottleneck at the moment, so that may take a while; I'll notify you when it's done

**Comment by ptrebert** [comment]
@maickrau transfer complete

**Comment by ptrebert** [comment]
yes, it's 1.0.9 (as installed as Verkko beta2 dependency during the Conda installation routine, I would assume?). I am submitting the test run to our cluster.

**Comment by maickrau** [comment]
This works now with the most recent MBG commit

**Comment by ptrebert** [comment]
@maickrau great; is there a timeline when the fix will be available in a release version?
