### ISSUE TITLE
WorkflowError problem in running verkko

### ISSUE THREAD

**Issue by wzboy1984** [marbl/verkko#61]
Hi,

When I ran verkko with sge support, I encountered the following WorkflowError. What should I do to fix the problem?

```
WorkflowError:
Error formatting custom jobscript /home/wangz/miniconda3/envs/verkko/lib/verkko/profiles/./jobscript.sh: value for 'workflow' not found.
Make sure that your custom jobscript is defined as expected.

My command lines are:
conda activate verkko
export VERKKO=/home/wangz/miniconda3/envs/verkko/bin/
verkko --hifi 45x.ccs.fasta --nano 45x.ont.fasta --threads 32 -d asm2 --sge
```

**Comment by skoren** [comment]
I'm going to guess you're running snakemake 7+ and the old release because the new one isn't in conda yet. Either switch to snakemake 6 or update to the latest release (either from compiling from code or waiting for the conda update).

**Comment by wzboy1984** [comment]
snakemake version: 7.3.8
verkko version: bioconda verkko bioconda 1.0 beta2

**Comment by skoren** [comment]
Right, so like I said above. The beta2 release isn't compatible with snakemake 7, you need to either update to v1.0 or downgrade to conda 6.

**Comment by wzboy1984** [comment]
Hi,
I installed verkko release v1.0 by compiling codes in [verkko-v1.0.tar.gz](https://github.com/marbl/verkko/releases/download/v1.0/verkko-v1.0.tar.gz).

The verkko didn't work yet. I got annother error information: 
> ...
> Select jobs to execute...
> 
> [Wed Apr 20 12:19:35 2022]
> localrule emptyfile:
>     output: emptyfile
>     jobid: 18
>     reason: Missing output files: emptyfile
>     resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp
> 
> 
> [Wed Apr 20 12:19:35 2022]
> rule buildStore:
>     input: /export/personal1/wangz/human_t2t/verkko/45x.ccs.fasta
>     output: 0-correction/hifi.seqStore
>     log: 0-correction/buildStore.err
>     jobid: 7
>     reason: Missing output files: 0-correction/hifi.seqStore
>     resources: mem_mb=264839, disk_mb=264839, tmpdir=/tmp, job_id=1, n_cpus=1, mem_gb=4, time_h=4
> 
> Error submitting jobscript (exit code 1):
> ...

My snakemake version is 7.3.8. 
When I ran the latest verkko of master branch (3ec75e9), I got the above same error information.
When I downgrade snakemake to version 6.8.2 by conda, I got similar error information as above.

**Comment by wzboy1984** [comment]
I changed script slurm-sge-submit.sh and slurm-sge-status.sh, and verkko seems to run well.

The $SGE_CELL is null in my bash environment, I changed it to $SGE_ROOT.
Also I changed the qsub command line: changed thread to smp, changed memory to vf.
