### ISSUE TITLE
Using Hi-C reads

### ISSUE THREAD

**Issue by Tierhon** [marbl/verkko#62]
Hi,
I just wanted to clarify an aspect or two regarding using Hi-C reads. You write "Preliminary support is available for read sets binned by haplotype from another method, such as [PGAS](https://github.com/daewoooo/SaaRclust) and Strand-Seq or [DipAsm](https://github.com/shilpagarg/DipAsm) and Hi-C." My understanding is that DipAsm creates a draft assembly, maps reads to it and uses HapCUT2 and WhatsHap to phase reads. These reads can then be output into different partitions. Would maternal.fofn then contain (HiFi?) reads from one partition, and paternal.fofn from the other? The Hi-C reads would then mostly be used to get chromosome scale phasing on the draft assembly, and not directly in any particular way?

Thank you.

Ole

**Comment by Tierhon** [comment]
Hi Sergey,
I've been thinking a bit on this. Could I generate these haplotype-specific k-mers based on the haplotype-resolved assemblies that hifiasm generates? Basically do something like this:
meryl threads=10 count compress k=21 default.hic.hap1.p_ctg.fa output hap1.meryl
meryl threads=10 count compress k=21 default.hic.hap2.p_ctg.fa output hap2.meryl

meryl difference  hap1.meryl hap2.meryl output only_hap1.meryl
meryl difference  hap2.meryl hap1.meryl output only_hap2.meryl

And those those last two meryl databases as input to verkko. Would that work?

Thank you.

Ole

**Comment by skoren** [comment]
Yes that would, in fact this is how we currently use Hi-C data as well. It results in a pretty clean coloring so you could try running verkko both with the data specified as `trio` or `hic` and compare results in terms of switch error/continuity/errors to see which is better.

**Comment by tinyfallen** [comment]
> Yes that would, in fact this is how we currently use Hi-C data as well. It results in a pretty clean coloring so you could try running verkko both with the data specified as `trio` or `hic` and compare results in terms of switch error/continuity/errors to see which is better.

Hi dear developer,

I have finished a verkko run using ont and hifi reads as I did not understand how to prepare the input Meryl database until I looked into this issue. So I would like to rerun the pipeline with it. Could you please give me some suggestions about how to reuse the output in the first run, thanks!

And you may add some description about the application of Hi-C data to README if you catch some time when you would like to. That may be very helpful to someone having Hi-C data but confusing about how to use it.

Best~

**Comment by skoren** [comment]
The verkko snakemake pipeline should be smart enough to re-generate the assembly with this information if you run in the same folder but add the DBs. Make sure to make a backup copy of your results though and first run with `--snakeopts "--dry-run"` to make sure it is running the right things (it should re-run steps 6- onwards).

As for documentation, this isn't our official Hi-C solution but an interim one while we work on better integration so I don't want to add it to the documentation. We should have a better solution by the end of this year.

**Comment by tinyfallen** [comment]
Many thanks for your great works! I will try it as you said.

Best~
