### ISSUE TITLE
Can't find 'bin/meryl-lookup' 

### ISSUE THREAD

**Issue by oushujun** [marbl/verkko#65]
I built verkko [3ec75e9](https://github.com/marbl/verkko/commit/3ec75e9d473339ad56315e009813ee5e5fcaac12) from source and try to run it with slurm. I am not using the trio mode but seems like it's trying to look up the meryl module: 

Command:
`nohup ~/bin/verkko/bin/verkko -d asm0228 --hifi Pacbio_Col-0.q20.fastq.gz --nano Nanopore_Col_0_guppy6_sup_model.fq --threads 90 --ali-run 17 192 72 --slurm &`

Error code:
```
 Verkko module path: /home/sou6/bin/verkko/lib/verkko/

Can't find 'bin/meryl-lookup' in directory VERKKO = '/home/sou6/bin/verkko/lib/verkko/'.
```

I found `meryl` is in the directory VERKKO, so I softlink it and it seems to resolve the complain:
```
cd /home/sou6/bin/verkko/lib/verkko/
ln -s meryl meryl-lookup
```

**Comment by brianwalenz** [comment]
It is definitely being built for me.  That program was a recent addition, so I suspect something didn't get updated or recompiled to 3ec75e9.  Try updating submodules and recompiling:
```
cd src
git submodule update --recursive
make clean
make > make.out 2>&1
```
if meryl-lookup persists in not appearing in lib/verkko/bin/ first check that the files in there were actually recompiled (the time stamp should be updated to the present time), then post make.out.

**Comment by skoren** [comment]
The updated recipe is integrated in conda now so you should be able to upgrade from there. Make sure you are getting build v3 and have version 1.0 (not beta2).
