### ISSUE TITLE
MBG: Assertion `resolvableGraph.unitigLength(newUnitigs[i].first[0].first) < resolvableGraph.unitigLength(newUnitigs[i].second)' failed

### ISSUE THREAD

**Issue by oushujun** [marbl/verkko#67]
Hello,

I am using `verkko bioconda 1.0` and run it locally. I run it with all default parameters:
`verkko -d asm0428 --hifi Tanz-1.q20.fastq.gz --nano Nanopore_Tanz_all_reads_Guppy6_Sup_model.fq --threads 48`

Errors in `1-buildGraph/buildGraph.err`
>try resolve k=1319, replaced 21 nodes with 161 nodes, unitigified 271 nodes to 133 nodes
try resolve k=1320, replaced 24 nodes with 199 nodesMBG: src/UnitigResolver.cpp:765: void replacePathNodes(ResolvableUnitigGraph&, std::vector<PathGroup>&, const std::vector<std::pair<std::vector<std::pair<long unsigned int, bool> >, long unsigned int> >&): Assertion `resolvableGraph.unitigLength(newUnitigs[i].first[0].first) < resolvableGraph.unitigLength(newUnitigs[i].second)' failed.
./buildGraph.sh: line 39: 67899 Aborted                 (core dumped) /home/sou6/bin/MBG/bin/MBG $iopt -t 8 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --out ../1-buildGraph/hifi-resolved.gfa

Is it due to the MBG version included in the conda recipe?

Thanks,
Shujun

**Comment by oushujun** [comment]
$ verkko --version
bioconda verkko bioconda 1.0

$ MBG --version
MBG Branch master commit de2b7e859e9710259f199830ec6a18643d1435ae 2022-04-27 12:02:30 +0200
Version: Branch master commit de2b7e859e9710259f199830ec6a18643d1435ae 2022-04-27 12:02:30 +0200

$ GraphAligner --version
GraphAligner Branch master commit 6bd37e23a300b1ca684891fc39ebfe0072286b9c 2022-04-19 21:23:17 +0200
GraphAligner Branch master commit 6bd37e23a300b1ca684891fc39ebfe0072286b9c 2022-04-19 21:23:17 +0200
Version Branch master commit 6bd37e23a300b1ca684891fc39ebfe0072286b9c 2022-04-19 21:23:17 +0200

**Comment by maickrau** [comment]
This is a bug in the current MBG master version. You can try running with MBG version 1.0.10

**Comment by skoren** [comment]
Yes, I was going to say, neither MBG nor GraphAligner look like they're installed from Conda, those should report versions like:
```
% GraphAligner --version
GraphAligner bioconda 1.0.16
GraphAligner bioconda 1.0.16
Version bioconda 1.0.16

% MBG --version
MBG bioconda 1.0.10
Version: bioconda 1.0.10
```

You can explicitly control which MBG/GraphAligner is used by verkko using the --mbg and --graphaligner options

**Comment by oushujun** [comment]
I see. It may picked up the old versions. Let me reinstall and retry. Thanks!

**Comment by oushujun** [comment]
Issue resolved. Thanks!
