### ISSUE TITLE
Negative coverage in ONT coverage file

### ISSUE THREAD

**Issue by skoren** [marbl/verkko#70]
In a test using PacBio subreads instead of ONT UL data, verkko crashed in process ONT. Partially fixed by 62359407525cfaf13a691d42a16509aa867b1f37 and 9d902c4ef9d6fc09f851cc64ebcdfd851985515d. However, looking at the ONT coverages, there are some negative values:
```
node    length  coverage
utig1-684       13720   -556.5600583090408
utig1-24158     1783    -192.76051598429612
utig1-24220     2829    -146.33439377872023
utig1-20530     1042    -120.13819577735123
utig1-18489     31003   -111.3799954843081
utig1-13269     42341   -91.88318650952921
utig1-23843     9073    -82.08343436570036
```

The asm is in `/data/Phillippy/projects/verkko/rainbowsmelt/beta_asm/`

**Comment by maickrau** [comment]
fixed in [dea63bc](https://github.com/marbl/verkko/commit/dea63bc3ad74c4b3878a22431b3842b8e3f554bf)
