### ISSUE TITLE
Error with buildGraph

### ISSUE THREAD

**Issue by wharvey31** [marbl/verkko#75]
Hello,

We are running verkko pretty routinely for samples with ONT and HiFi data, but one sample ran into this bug with the rule buildGraph:

The last few lines of 1-buildGraph/buildGraph.err are below

```
try resolve k=1574MBG: src/UnitigResolver.cpp:1802: ResolutionResult resolve(ResolvableUnitigGraph&, const HashList&, size_t, std::vector<PathGroup>&, const phmap::flat_hash_set<long unsigned int>&, size_t, bool): Assertion `newEdgeNodes.count(std::make_pair(pos, after)) == 1 || newEdgeNodes.count(std::make_pair(reverse(after), reverse(pos))) == 1' failed.
./buildGraph.sh: line 39: 30886 Aborted                 /path/to/envs/verkko/bin/MBG $iopt -t 4 -k 1001 -r 15000 -R 4000 -w 100 --kmer-abundance 1 --unitig-abundance 2 --error-masking=collapse-msat --output-sequence-paths ../1-buildGraph/paths.gaf --out ../1-buildGraph/hifi-resolved.gfa
```

Any help would be greatly appreciated!

**Comment by skoren** [comment]
I think this is the same as #63. Try compiling the latest MBG from GitHub (https://github.com/maickrau/MBG) and running verkko with that version instead (provide `--mbg=/full/path/to/mbg` as an option).

**Comment by wharvey31** [comment]
Thanks so much! I will give it a try!

**Comment by wharvey31** [comment]
Issue resolved! Thanks so much!
