### ISSUE TITLE
Adding ONT results in smaller output assembly

### ISSUE THREAD

**Issue by olekto** [marbl/verkko#77]
Hi,
we got some ONT reads for the salmon I was working on in  #63. The resulting assembly.fasta is smaller with ONT reads than without. Both BUSCO and Merqury confirms that the ONT-assembly is smaller. First this:
```
3.9G 1-buildGraph/hifi-resolved.gfa                     66M 4-processONT/combined-edges-uniques.gfa                     2.8G 4-processONT/unitig-unrolled-ont-resolved.gfa   2.8G 5-untip/unitig-normal-connected-tip.gfa
3.9G 2-processGraph/gapped-hifi-resolved.gfa           4.0G 4-processONT/connected.gfa                                  2.8G 4-processONT/unrolled-ont-resolved.gfa          2.8G 5-untip/unitig-popped-unitig-normal-connected-tip.gfa
3.9G 2-processGraph/gapped-once-hifi-resolved.gfa      3.9G 4-processONT/gapped-once-unitig-unrolled-hifi-resolved.gfa   91M 5-untip/combined-edges-1.gfa                     92M 6-layoutContigs/combined-edges.gfa
3.9G 2-processGraph/gapped-twice-hifi-resolved.gfa     3.9G 4-processONT/gapped-unitig-unrolled-hifi-resolved.gfa        92M 5-untip/combined-edges-final.gfa                1.4M 6-rukki/unitig-popped-unitig-normal-connected-tip.noseq.gfa
3.9G 2-processGraph/unitig-unrolled-hifi-resolved.gfa  4.0G 4-processONT/normal-connected.gfa                           2.8G 5-untip/connected-tip.gfa
4.0G 2-processGraph/unrolled-hifi-resolved.gfa         2.8G 4-processONT/ont-resolved-graph.gfa                         2.8G 5-untip/popped-unitig-normal-connected-tip.gfa
```
I don't know the exact order here, but the graph goes from 4G to 2.8G after adding ONT. I tried reading the commits and issues, but couldn't find one explicitly dealing with this. I also tried compiling the repository, but our system might have some issues with some compatibilities (binutils vs gcc), so it was not an easy fix. 

BUSCO without ONT:
```
	--------------------------------------------------
	|Results from dataset actinopterygii_odb10        |
	--------------------------------------------------
	|C:95.1%[S:10.2%,D:84.9%],F:2.5%,M:2.4%,n:3640    |
	|3461	Complete BUSCOs (C)                       |
	|372	Complete and single-copy BUSCOs (S)       |
	|3089	Complete and duplicated BUSCOs (D)        |
	|91	Fragmented BUSCOs (F)                     |
	|88	Missing BUSCOs (M)                        |
	|3640	Total BUSCO groups searched               |
	--------------------------------------------------
```
BUSCO with ONT:
```
	--------------------------------------------------
	|Results from dataset actinopterygii_odb10        |
	--------------------------------------------------
	|C:91.9%[S:17.7%,D:74.2%],F:2.0%,M:6.1%,n:3640    |
	|3344	Complete BUSCOs (C)                       |
	|643	Complete and single-copy BUSCOs (S)       |
	|2701	Complete and duplicated BUSCOs (D)        |
	|73	Fragmented BUSCOs (F)                     |
	|223	Missing BUSCOs (M)                        |
	|3640	Total BUSCO groups searched               |
	--------------------------------------------------
```
Merqury spectra without ONT:
![verkko_only_hifi_hifidb spectra-asm fl](https://user-images.githubusercontent.com/1632235/168479260-d9ce3438-c6ae-464e-93fe-e0cf931ea4e5.png)

Merqury spectra with ONT:
![verkko_asm_hifidb spectra-asm fl](https://user-images.githubusercontent.com/1632235/168479232-33c3d555-8e5f-4146-ac22-5fdddf4c027a.png)

Assembly stats without ONT:
```
# scaffolds: 98678
Total scaffold length: 6142782228
Average scaffold length: 62250.78
Scaffold N50: 129295
Scaffold auN: 431178.86
Scaffold L50: 10769
Largest scaffold: 8589823
Total contig length: 6136059649
Average contig length: 62129.76
Contig N50: 128957
Contig auN: 313520.87
Contig L50: 10968
Largest contig: 6021823
```

Assembly stats with ONT:
```
# scaffolds: 18758
Total scaffold length: 4325416259
Average scaffold length: 230590.48
Scaffold N50: 434193
Scaffold auN: 651315.93
Scaffold L50: 2699
Largest scaffold: 7840372
Total contig length: 4322345500
Average contig length: 229997.63
Contig N50: 433545
Contig auN: 635051.00
Contig L50: 2728
Largest contig: 7840372
```

The haploid genome is around 3 Gbp, so the assembly without ONT is approximately double the haploid size (which we want) while the one with ONT reads lack around 1.6 Gbp. 

So the assembly with ONT reads is smaller, lacks ONT reads and lack k-mers which are found only in the reads. Is this a known issue? If it is fixed after the 1.0 release, I will have to try to compile the repository again or wait for 1.1.

We can share the ONT reads (and I've already shared the HiFi reads with you). The coverage in ONT reads is around 18x. Would that be an issue? We had hoped to use ONT to patch gaps and connect contigs, not to generate equal amounts or more compared to HiFi. 

Thank you.

Sincerely,
Ole

**Comment by skoren** [comment]
The ONT coverage may be the issue. There are thresholds for filtering nodes w/o ONT coverage in the graph and the defaults might be too high given your coverage. We typically use 40-50x ONT coverage. @maickrau might have some suggestions on what parameters could be changed to avoid this and/or if this can be disabled.

**Comment by maickrau** [comment]
It's most likely the ONT coverage. Most of the relevant parameters aren't currently exposed to the command line interface so you can change them in the snakefiles.

Command line parameters:
`--pop_min_allowed_cov 2 --pop_resolve_steps "5 3 2"`
this is the minimum ONT coverage required to not remove nodes during ONT resolution and probably responsible for a large part of the missing sequence, and the thresholds for solid k-mers supported by ONT

ONT gap filling:
https://github.com/marbl/verkko/blob/master/src/Snakefiles/4-processONT.sm#L74 switch the 3 to 2
https://github.com/marbl/verkko/blob/master/src/Snakefiles/4-processONT.sm#L78 switch the 5 to 3
this will use less ONT coverage for filling gaps

ONT resolution:
https://github.com/marbl/verkko/blob/master/src/Snakefiles/4-processONT.sm#L245 switch the 30 to 5
this will make the resolution more careful about not leaving out nodes / edges supported by ONT

These are guesses and other numbers might work better but this should be a decent enough starting point

**Comment by Tierhon** [comment]
Hi Mikko and Sergey.

These specific options helped a bit. The GFA increased from 2.8 GB to 3.5 GB. The hifi-resolved.gfa is 3.9 GB, so there is still something being lost. 

I guess I can take a look at  nodecovs-ont.csv  for instance to see how much coverage is found in different nodes. As it is now, you would expect some ONT coverage in all nodes based on HiFi reads? 

By the way, it doesn't look like pop_min_allowed_cov and pop_resolve_steps are exposed as command line parameters. I had to edit the verkko file to change these.

Thank you.

Ole

**Comment by maickrau** [comment]
The nodecovs-ont.csv might be informative. Usually some fraction of coverage is lost when aligning (due to low quality / too short reads) so the effective coverage will be lower than 18x. You can also try switching to even lower required ONT coverage with:

`--pop_min_allowed_cov 0`
https://github.com/marbl/verkko/blob/master/src/Snakefiles/4-processONT.sm#L245 switch 30 (or 5) to 1

This will almost completely forbid the ONT resolution from removing nodes. It might also lead to a less resolved assembly.

**Comment by oushujun** [comment]
I also experience this issue. The input ONT reads have over 50x of coverage. Adding ONT results in less than half the size of HiFi-based assembly. The `4-processONT/nodecovs-ont.csv` has lots of 0s and an average of 0.523324. Also, the `assembly.ont-coverage.csv` file has an average coverage of 2.8544. Does this mean most ONT reads were filtered out?

Shujun

**Comment by skoren** [comment]
@oushujun if you have 50x coverage but only 3x aligns, something is very off about those reads. Are they older ONT data or from another individual? Do you have any estimate of what the identity of these reads is?

**Comment by oushujun** [comment]
@skoren yeah something is really off. The ONT data are generated by PromethION R9 with the SQK-LSK109 chemistry. I am not sure how old is too old. One thing that may cause the issue, HiFi data were from pooled plants, ONT may also be (to be determined by the collaborator), but still, only 3x aligned is too strange.

**Comment by skoren** [comment]
Pooled samples could cause issues, especially if they're diverged enough and the HiFi graph is very split up since there are so many haplotypes. You could try relaxing the ONT alignment parameters with `--seed-max-length 1000 --min-score 1000 --min-identity 0.75` and see if more reads align.

**Comment by skoren** [comment]
This should be addressed by recent changes to dynamically set coverage and never drop larger nodes due to low coverage.
