### ISSUE TITLE
Add CLR support

### ISSUE THREAD

**Issue by skoren** [marbl/verkko#79]
For cases where no ONT is available but old CLR data is or reads that failed Q20 HiFi conversion, add an `--clr` option to verkko. Several of the settings aren't parameterized and would be useful for low coverage ONT data (see #77) so parameterize those as well.

 Current best practices to include into snakemake are
```
--seed-max-length 1000 --min-score 1000 --min-identity 0.75
```

Parameterized in snakemake but not promoted to command line, useful for low ONT coverage, perhaps can be auto-set based on observed mapping coverage
- pop_min_allowed_cov set to -1 for CLR
- pop_resolve_steps set to 3 2 2 for CLR

To parameterize:
- Step 1a: chop mis-assemblies 10 20 defaults; used 20 0 for CLR
- Step 2a: insert gaps two step of 3 50; 5 1500 defaults; used 2 50 and 3 1500 for CLR
- Step 11: 30 coverage default; used 1 10 for CLR

**Comment by sadikmu** [comment]
Hi, 

I couldn't find the step1a-11 options to modify the parameter to try verkko with Hifi + reads that did not make it to HiFi (<Q20) adding in --clr.  Thank you.

**Comment by skoren** [comment]
Those are within the 4-processONT/processONT.sh script, you have to modify it and re-run by hand before resuming the pipeline.

**Comment by skoren** [comment]
Going to close this as it is not a high development priority. Interested users can adjust the parameters as described above. However, the general the benefit is limited since CLR still has issues with similar regions to HiFi (lower coverage) and the reads are often too short to resolve the gap (if they come from the same HiFi prep). The consensus with low-coverage CLR reads is also low quality.
