### ISSUE TITLE
Error: one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!

### ISSUE THREAD

**Issue by zou-yawen** [marbl/verkko#84]
Dear verkko：
       I had met something wrong with running verkko.when I run with the command below using the test example on the  verkko is rigth ,but when I use the similar command to analyze the human sequence, something is wrong.
      test  example command  : `verkko -d /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko_test/asm --hifi /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko_test/hifi.fastq.gz --nano /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko_test/ont.fastq.gz --snakeopts "-j 50 -k --restart-times 1 --cluster 'sbatch   -p 64c512g --ntasks-per-node 1 --parsable --mem-per-cpu 40000'" --slurm`
      human sequence command  ： `verkko -d /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko --hifi /dssg/home/acct-aemyxy/aemyxy/data/chm13/hifi_20kb/*.fastq.gz --nano /dssg/home/acct-aemyxy/aemyxy/data/chm13/nanopore/nanpore_100x.fastq.gz --snakeopts "-j 50 -k --restart-times 1 --cluster 'sbatch   -p 64c512g --ntasks-per-node 1 --parsable --mem-per-cpu 40000'" --slurm`
   the error is below,every time I restart the command above , the error occured in diifferent step ,sometimes 0-correction,sometimes 1-buildGraph.
   **cat > ./aligned046.sh <<EOF
#!/bin/sh
set -e

/dssg/home/acct-aemyxy/aemyxy/miniconda3/envs/verkko/bin/GraphAligner -t 24 -g ../2-processGraph/unitig-unrolled-hifi-resolved.gfa -f ../3-align/split/ont046.fasta.gz -a ../3-align/aligned046.WORKING.gaf \\
  --seeds-mxm-cache-prefix ../3-align/graph \\
  --seeds-mxm-length 30 \\
  --seeds-mem-count 10000 \\
  --bandwidth 15 \\
  --multimap-score-fraction 0.99 \\
  --precise-clipping 0.85 \\
  --min-alignment-score 5000 \\
  --hpc-collapse-reads \\
  --discard-cigar \\
  --clip-ambiguous-ends 100 \\
  --overlap-incompatible-cutoff 0.15 \\
  --max-trace-count 5 \\
&& \\
mv -f ../3-align/aligned046.WORKING.gaf ../3-align/aligned046.gaf
EOF

chmod +x ./aligned046.sh

./aligned046.sh > ../3-align/aligned046.err 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 16877508

Error executing rule alignONT on cluster (jobid: 607, external: 16877508, jobscript: /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko/.snakemake/tmp.auc7cnf4/verkko.alignONT.607.sh). For error details see the cluster log and the log files of the involved rule(s).
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-07-06T081534.001127.snakemake.log**
    I don`t know how solve the problem;could you please help me

**Comment by zou-yawen** [comment]
I just restart the command ,the error happend again.
**EOF

chmod +x ./buildGraph.sh

./buildGraph.sh > ../1-buildGraph/buildGraph.err 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 16881677

Error executing rule buildGraph on cluster (jobid: 4, external: 16881677, jobscript: /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko/.snakemake/tmp.vzr_27us/verkko.buildGraph.4.sh). For error details see the cluster log and the log files of the involved rule(s).
Trying to restart job 4.
Select jobs to execute...**

**Comment by skoren** [comment]
Those seem like errors from different steps, one is from the buildGrpah and the other from ONT alignments which should only happen if buildGraph succeeded. What's the error reported in buildGraph.err or 3-align/aligned046.err?

**Comment by zou-yawen** [comment]
> Those seem like errors from different steps, one is from the buildGrpah and the other from ONT alignments which should only happen if buildGraph succeeded. What's the error reported in buildGraph.err or 3-align/aligned046.err?

Thank you for your replay.  Sorry,I run the command again,this time it happend in another step;

**cat > ./000001.sh <<EOF
#!/bin/sh
set -e

#  Parameters from '0-correction/overlap-jobs/000001.params':
#    $params

/dssg/home/acct-aemyxy/aemyxy/miniconda3/envs/verkko/lib/verkko/bin/overlapInCore \\
  -t 8 \\
  -k 28 \\
  -k ../../0-correction/hifi.ignoremers \\
  --hashbits 25 \\
  --hashload 0.8 \\
  --maxerate  0.01 \\
  --minlength 2000 \\
  $params \\
  -o ../../0-correction/overlap-jobs/000001.ovb.WORKING \\
  -s ../../0-correction/overlap-jobs/000001.stats \\
  ../../0-correction/hifi.seqStore \\
&& \\
mv -f ../../0-correction/overlap-jobs/000001.ovb.WORKING ../../0-correction/overlap-jobs/000001.ovb
EOF

chmod +x ./000001.sh

./000001.sh > ../../0-correction/overlap-jobs/000001.err 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message**



0-correction/overlap-jobs/000001.err  is below,error show no 0-correction/hifi.ignoremers files; I check it, no such file. But I have seen this file at the begining ; I don`t know why it`s disappear.


**Initializing 8 work areas.
Loading reference reads 1-44137 inclusive.
Loading 44137 reads and 639961878 bases from range 1-44137 inclusive.
Loading        1 <     4567 <    44137 -   10.35% - 0.02 GB^MLoading        1 <     9134 <    44137 -   20.69% - 0.04 GB^MLoading        1 <    13701 <    44137 -   31.04% - 0.07 GB^MLoading        1 <    18268 <    44137 -   41.39% - 0.09 GB^MLoading        1 <    22835 <    44137 -   51.74% - 0.11 GB^MLoading        1 <    27402 <    44137 -   62.08% - 0.13 GB^MLoading        1 <    31969 <    44137 -   72.43% - 0.15 GB^MLoading        1 <    36536 <    44137 -   82.78% - 0.18 GB^MLoading        1 <    41103 <    44137 -   93.13% - 0.20 GB^MLoading        1 <    44137 <    44137 -  100.00% - 0.21 GB
Build_Hash_Index from 1 to 44137

Found 44137 reads with length 640006015 to load; 0 skipped by being too short; 0 skipped per library restriction
String_Ct:           0/       44137  totalLen:       16944/   642103166  Hash_Entries:       16884/   563714457  Load: 0.00%
HASH LOADING STOPPED: curID           44137 out of        44137
HASH LOADING STOPPED: length      640006015 out of    642103166 max.
HASH LOADING STOPPED: entries     503727436 out of    563714457 max (load 71.49).
Failed to open '../../0-correction/hifi.ignoremers' for reading: No such file or directory**

**

**Comment by skoren** [comment]
Your snakemake seems awfully confused, it keeps backing up steps and failing on already completed steps, presumably because some input file got already cleaned up. I've seen strange behavior from snakemake before like this when you have manually touched/changed a file in the assembly folder. 

So, don't try to re-launch the run since it will likely just do the wrong thing and won't help until you address the original issue anyway. If you have the logs in the 3-align step still, post the failed one here `3-align/aligned046.err`. If you don't, run the `3-align/aligned046.sh` step by hand and post its output.

**Comment by zou-yawen** [comment]
> Your snakemake seems awfully confused, it keeps backing up steps and failing on already completed steps, presumably because some input file got already cleaned up. I've seen strange behavior from snakemake before like this when you have manually touched/changed a file in the assembly folder.
> 
> So, don't try to re-launch the run since it will likely just do the wrong thing and won't help until you address the original issue anyway. My guess is your fixed memory request (`--mem-per-cpu 40000`) caused graph aligner to run out of memory, snakemake manages memory for you and you shouldn't set limits this way. If you have the logs in the 3-align step still, post the failed one here `3-align/aligned046.err`. If you don't, run the `aligned046.sh` step by hand from inside the `3-align` folder and post its output.

Thanks a lot.Maybe there is something wrong with our cluster. In our cluster, if don`t use    "--mem-per-cpu 40000"to set the memory ,it`ll stop because of out of memory.Accordinng to you advice,I adjust it  to "--mem-per-cpu 300000";  the memory should be  enough.In addition ,running the `aligned046.sh` step by hand,it seems to be rigth,the error file is below.
 
**GraphAligner bioconda 1.0.16-
GraphAligner bioconda 1.0.16-
Load graph from ../2-processGraph/unitig-unrolled-hifi-resolved.gfa
Build MUM/MEM seeder from the graph
Build alignment graph
MEM seeds, min length 30, max count 10000
Seed cluster size 1
Extend up to 5 seed clusters
Alignment bandwidth 15
Clip alignment ends with identity < 85%
X-drop DP score cutoff 33333
Backtrace from 5 highest scoring local maxima per cluster
write alignments to ../3-align/aligned046.WORKING.gaf
Align
Alignment finished
Input reads: 150001 (58360819bp)
Seeds found: 2664457
Seeds extended: 255
Reads with a seed: 385 (13997486bp)
Reads with an alignment: 51 (1273725bp)
Alignments: 77 (1322849bp) (8748 additional alignments discarded)
End-to-end alignments: 0 (0bp)**


Now my command is **verkko -d /dssg/home/acct-aemyxy/aemyxy/workspace/chm13/verkko_test3 --hifi /dssg/home/acct-aemyxy/aemyxy/data/chm13/hifi_20kb/SRR11292120.2.fastq.gz --nano /dssg/home/acct-aemyxy/aemyxy/data/chm13/nanopore/nanpore_100x.fastq.gz --snakeopts " -j 20 -k --restart-times 1 --latency-wait 300 --cluster 'sbatch   -p 64c512g --ntasks-per-node 1 --parsable --mem-per-cpu 300000 '" --slurm**.   
The error I mention above don`t happen again.I have  question why aligned*.sh  only run one after another in one job in our cluster, is it normal that these script don`t run in different job in parallel

**Comment by skoren** [comment]
OK so the original error is resolved. The jobs certainly can run more than one at a time, that's handled by snakemake not verkko. Snakemake will submit as many as it's allowed to by your core settings (20 jobs in your case). I'd guess the overly large memory request you made is preventing slurm from scheduling more than one at a time due to limited resources. As I said, I would run without specifying the memory limit explicitly. If one step has memory issues, you can increase the memory just for that step not for all jobs you're submitting.

**Comment by ndierckx** [comment]
I had the same error above, for me I think it was because of an old python version (2.7.4), with 3.7.4. I do not have the problem anymore

**Comment by zou-yawen** [comment]
> OK so the original error is resolved. The jobs certainly can run more than one at a time, that's handled by snakemake not verkko. Snakemake will submit as many as it's allowed to by your core settings (20 jobs in your case). I'd guess the overly large memory request you made is preventing slurm from scheduling more than one at a time due to limited resources. As I said, I would run without specifying the memory limit explicitly. If one step has memory issues, you can increase the memory just for that step not for all jobs you're submitting.

Thank you very much.I`ll try to run  without specifying the memory limit explicitly.How much time you finish the verkko on t2t genome assamble

**Comment by zou-yawen** [comment]
> I had the same error above, for me I think it was because of an old python version (2.7.4), with 3.7.4. I do not have the problem anymore



> > OK so the original error is resolved. The jobs certainly can run more than one at a time, that's handled by snakemake not verkko. Snakemake will submit as many as it's allowed to by your core settings (20 jobs in your case). I'd guess the overly large memory request you made is preventing slurm from scheduling more than one at a time due to limited resources. As I said, I would run without specifying the memory limit explicitly. If one step has memory issues, you can increase the memory just for that step not for all jobs you're submitting.
> 
> Thank you very much.I`ll try to run without specifying the memory limit explicitly.How much time you finish the verkko on t2t genome assamble



> I had the same error above, for me I think it was because of an old python version (2.7.4), with 3.7.4. I do not have the problem anymore

**Comment by zou-yawen** [comment]
> I had the same error above, for me I think it was because of an old python version (2.7.4), with 3.7.4. I do not have the problem anymore
Thank you very much.My python version is 3.10.5,I`ll try to run it use the 3.7.4.How much time you finish the verkko on t2t genome assamble
