### ISSUE TITLE
how to  gain consensus sequence

### ISSUE THREAD

**Issue by zhoudreames** [marbl/verkko#85]
In the resulting assembly.homopolymer-compressed.gfa files, can I gain the consensus sequence if I know the appropriate path（red path）？
![image](https://user-images.githubusercontent.com/54714639/179221088-536156ef-7724-4ebe-9588-1c90b8981559.png)

**Comment by skoren** [comment]
By the way, your path looks invalid, there's no connection between the pink node at the top left and the purple node so you can't exit the loop that way. You'd likely need to traverse the bottom right loop first, then the top left twice. Have you actually phased/confirmed the right order of the non-duplicated nodes somehow to make sure the repeat is correctly reconstructed?

**Comment by zhoudreames** [comment]
> By the way, your path looks invalid, there's no connection between the pink node at the top left and the purple node so you can't exit the loop that way. You'd likely need to traverse the bottom right loop first, then the top left twice. Have you actually phased/confirmed the right order of the non-duplicated nodes somehow to make sure the repeat is correctly reconstructed?

thank for your reminder， I try to get the consensus sequence for the specified path， with this code:
```
verkko -paths 6-layoutContigs/consensus_paths.txt -assembly assembly.homopolymer-compressed.gfa
```
but there is no such option， That‘s why？
![image](https://user-images.githubusercontent.com/54714639/179327958-c80a6e0d-d51c-4a76-9d07-237644bfbcb7.png)

**Comment by skoren** [comment]
The assembly option should be the folder not just the gfa file. The options should have two dashes, like `--paths` and `--assembly`. You still need to provide the -d for the output of the consensus and the path to the hifi reads you used for the original assembly. The ONT reads are re-used from the assembly path.

**Comment by zhoudreames** [comment]
> The assembly option should be the folder not just the gfa file. The options should have two dashes, like `--paths` and `--assembly`. You still need to provide the -d for the output of the consensus and the path to the hifi reads you used for the original assembly. The ONT reads are re-used from the assembly path.

I'm still a little confused, First, I edited the consensus_paths.txt
```
utig4-15        >utig4-15
utig4-4 >utig4-4
utig4-1 >utig4-1
utig4-6 >utig4-6
utig4-7 >utig4-7
utig4-8 >utig4-8
utig4-16        >utig4-16
utig4-2 >utig4-2
utig4-1 >utig4-1
utig4-5 >utig4-5
utig4-10        >utig4-10
utig4-11        >utig4-11
utig4-13        >utig4-13
utig4-14        >utig4-14
utig4-4 >utig4-4
utig4-1 >utig4-1
utig4-6 >utig4-6
utig4-7 >utig4-7
utig4-9 >utig4-9
utig4-16        >utig4-16
utig4-3 >utig4-3
utig4-1 >utig4-1
utig4-5 >utig4-5
utig4-10        >utig4-10
utig4-12        >utig4-12
utig4-13        >utig4-13
utig4-0 >utig4-0
```
Then, I put the raw assembly.homopolymer-compressed.gfa into new folder(mkdir tmp),look like this：
![image](https://user-images.githubusercontent.com/54714639/179335670-23f54e5b-0f56-4246-ac56-baa0fd058172.png)
finally, I run the verkko,tmp folder contains only assembly.homopolymer-compressed.gfa, and the consensus_paths.txt  files was edited by myself.
```
verkko -d tmp --hifi chr13:2000000_20000000.HiFi.fastq --nano chr13:2000000_20000000.ONT.fastq --paths consensus_paths.txt --assembly tmp
```
I try it,but no success, I don't know how to do it, can you provide my more detail operation? thanks again.

**Comment by skoren** [comment]
As I said, the assembly parameter is the previous full run of verkko where the graph and nodes you want to generate consensus are. It has to have the full verkko structure (e.g. the 6- and 7- folders), don't make a new folder, reuse the existing run.

**Comment by zhoudreames** [comment]
> As I said, the assembly parameter is the previous full run of verkko where the graph and nodes you want to generate consensus are. It has to have the full verkko structure (e.g. the 6- and 7- folders), don't make a new folder, reuse the existing run.

Thanks, I rerun the verkko following your suggestion:
```
verkko -d tmp --hifi chr13:2000000_20000000.HiFi.fastq --nano chr13:2000000_20000000.ONT.fastq --paths consensus_paths.txt --assembly chr13
```
The chr13 folder is the previous resulting files generated by verkko:
```
verkko -d chr13 --hifi chr13:2000000_20000000.HiFi.fastq --nano chr13:2000000_20000000.ONT.fastq 
```
but the resulting assembly.fasta not was a complete sequence, instead of contain of many gaps.
![image](https://user-images.githubusercontent.com/54714639/179355614-837fa952-d15c-402a-b573-f4de846555fc.png)
I have assigned a suitable path to untie this tangle, but the resulting sequence is incomplete, Do I have any problems with those steps?

**Comment by skoren** [comment]
Your paths were all single nodes, I assumed this was a test not the actual path you wanted a consensus for. You need to give a path in gaf format (https://github.com/lh3/gfatools/blob/master/doc/rGFA.md) in consensus_paths.txt. 

So
```
utig4-15        >utig4-15
```
means the node is just utig4-15 in the forward (5' to 3') orientation. 
```
utig4-15        <utig4-15
```
would be the node in reverse complement (3' to 5') orientation. Then
```
mat_from_utig4-2114	>utig4-435<utig4-9195[N222184N]>utig4-9196<utig4-2747<utig4-2746<utig4-2389<utig4-2110>utig4-2108>utig4-2114	MATERNAL
```
Means take node utig4-435 in fwd strand, utig4-9195 in reverse, put in a 222,184 bp gap of Ns, utig4-9196 fwd, and so on.

**Comment by zhoudreames** [comment]
I got it, thanks~
