### ISSUE TITLE
Support for PBS

### ISSUE THREAD

**Issue by ndierckx** [marbl/verkko#88]
I saw there is support for SGE, Slurm and LSF; but does it also work for PBS submission systems?

**Comment by brianwalenz** [comment]
It does not currently support PBS, but adding that shouldn't be difficult.  Verkko uses two auxiliary scripts, one to submit a job to the cluster, the other to check if the job is running or finished.

The submit script takes a path to a script to run and limits on memory and cpu to use.  It needs to return the scheduler job ID.  (It also does some bookkeeping for debugging, like saving the script that runs and redirecting job output.)

The status script takes a job ID and returns "success" if the job finished successfully, "failed" if it failed, or "running" if the job is pending or running.

Happy to help, but I don't know enough PBS to do it all myself.

https://github.com/marbl/verkko/blob/master/src/profiles/slurm-sge-submit.sh
https://github.com/marbl/verkko/blob/master/src/profiles/slurm-sge-status.sh

**Comment by ndierckx** [comment]
Ok thanks, I will have a look if I can do it, I am not that familiar with PBS either so...
