### ISSUE TITLE
Generating arbitrary pseudohaplotypes

### ISSUE THREAD

**Issue by skagawa2** [marbl/verkko#90]
What is the best way to generate hifiasm-like primary contigs from the results of verkko? For reference, we generated an assembly with only HiFi reads because we don't have ONT reads. I saw #59 and I ran purge_dups, but I'm not completely sure how that will stitch together haplotype blocks into a primary assembly. For our project, we don't _need_ a completely phased assembly since we don't have phasing information.

Thanks!

**Comment by skoren** [comment]
Verkko doesn't currently have a way to pull out pseudo-haplotypes. The only option would be if you were to generate these paths from the graph yourself. That said, I don't think verkko is great for your specific use case, HiFi-only and no long-range phasing information.

**Comment by skagawa2** [comment]
Makes sense. Thank you for your quick reply!
