### ISSUE TITLE
Doesn't verkko install from github need rust installed?

### ISSUE THREAD

**Issue by jelber2** [marbl/verkko#91]
As far as I can tell, for the full installation of verkko (at least as of 898b706) from github needs perhaps a recent version of rust installed for compiling [rukki](https://github.com/marbl/rukki)

**Comment by skoren** [comment]
It does, it's listed as a requirement on the v1.0 release: https://github.com/marbl/verkko/releases/tag/v1.0 which was the first version to integrate rukki. I see the install version was ambiguous as it didn't list compilation requirements, only runtime requirements (e.g. you don't need rust after you build the binary like gcc) but I added the compilation requirements to the readme.
