### ISSUE TITLE
slrum problem

### ISSUE THREAD

**Issue by zhoudreames** [marbl/verkko#92]
I can successfully run the test data on the local machine
```
verkko -d test --hifi ./ecoli_hifi_subset24x.fastq.gz --nano ./ecoli_ont_subset50x.fastq.gz --threads 90 
```
However, there are some errors when with --slurm parameter:
```
verkko -d test --hifi ./ecoli_hifi_subset24x.fastq.gz --nano ./ecoli_ont_subset50x.fastq.gz --threads 90  --slurm
```
the errors:
```
Launching bioconda verkko bioconda 1.0 ...
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 1000
Job stats:
job                            count    min threads    max threads
---------------------------  -------  -------------  -------------
buildGraph                         1              4              4
buildPackages                      1              8              8
buildStore                         1              1              1
combineConsensus                   1              1              1
combineONT                         1              1              1
combineOverlaps                    1              1              1
configureFindErrors                1              1              1
configureOverlaps                  1              1              1
correctHiFi                        1              1              1
emptyfile                          1              1              1
extractONT                         1              8              8
fixErrors                          1              1              1
generateLayoutContigsInputs        1              1              1
getCoverage                        3              1              1
layoutContigs                      1              1              1
prepCoverage                       1              1              1
processGraph                       1              1              1
processONT                         1              1              1
splitONT                           1              1              1
untip                              1              1              1
verkko                             1              1              1
total                             23              1              8

Select jobs to execute...

[Thu Jul 28 22:47:37 2022]
localrule emptyfile:
    output: emptyfile
    jobid: 18
    reason: Missing output files: emptyfile
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp


[Thu Jul 28 22:47:37 2022]
checkpoint splitONT:
    input: /gxn/Mzhou2/15.Verkko/test/./ecoli_ont_subset50x.fastq.gz
    output: 3-align/split/splitONT.finished
    log: 3-align/splitONT.err
    jobid: 12
    reason: Missing output files: 3-align/split/splitONT.finished
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp, job_id=1, n_cpus=1, mem_gb=8, time_h=96
Downstream jobs will be updated after completion.

Submitted job 12 with external jobid '819759'.

[Thu Jul 28 22:47:38 2022]
rule buildStore:
    input: /gxn/Mzhou2/15.Verkko/test/./ecoli_hifi_subset24x.fastq.gz
    output: 0-correction/hifi.seqStore
    log: 0-correction/buildStore.err
    jobid: 7
    reason: Missing output files: 0-correction/hifi.seqStore
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp, job_id=1, n_cpus=1, mem_gb=4, time_h=4

Submitted job 7 with external jobid '819760'.
[Thu Jul 28 22:47:38 2022]
Finished job 18.
1 of 23 steps (4%) done
sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection to host:localhost:6819: Connection refused
sacct: error: Sending PersistInit msg: Connection refused
sacct: error: Problem talking to the database: Connection refused

```
That`s why? thanks~

**Comment by skoren** [comment]
This doesn't look like a verkko error but an issue with your slurm system. It seems the daemon that's supposed to be monitoring jobs/reporting statuses is failing or refusing connections. You'd need to check with your cluster IT staff to see what's going on.

**Comment by skoren** [comment]
The workflow doesn't matter, it is just calling sacct which is failing. Sacct is a standard part of slurm (https://slurm.schedmd.com/sacct.html) so that's what I'd look into.

**Comment by zhoudreames** [comment]
thanks,I known

**Comment by jinhua2024** [comment]
Dear skoren,
Greetings! I am jinhua, currently utilizing the Verkko software for genome assembly. I have run into a problem during its execution and am seeking your guidance.
The command I employed is as follows:
#!/bin/bash
#SBATCH --job-name=verkko1   
#SBATCH --output=/osmgfs10000/home/wujinhua/log_error_202502/verkko1.log
#SBATCH --error=/osmgfs10000/home/wujinhua/log_error_202502/verkko1.error.txt        
#SBATCH --ntasks=1               
#SBATCH --cpus-per-task=20        
#SBATCH --mem=150G            
#SBATCH --time=1000:10:00           
#SBATCH --partition=teacher        
#SBATCH --nodelist=computer-node02    

source ~/miniconda3/bin/activate
conda activate verrko_env
verkko -d /verrko_hifi/fmp4274_verkko \
  --hifi/PB/CCS/FMP4274_hifi_merge.fq.gz \
  --hic1 /FMP4274_1_clean.fq.gz  \
  --hic2/FMP4274_2_clean.fq.gz \
  --no-nano \
  --ref /LW.genome.fa \
--slurm --snakeopts '--cluster "./slurm-sge-submit.sh {threads} {resources.mem_gb} {resources.time_h} {rulename} {resources.job_id} --partition=teacher --account=wujinhua --qos=teacher"'

Subsequently, the following error messages appeared:
Submitted job 22 with external jobid '2597'.
[Thu Apr 24 03:35:11 2025]
Finished job 14.
1 of 27 steps (4%) done
sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection to host:localhost:6819: Connection refused
sacct: error: Sending PersistInit msg: Connection refused
sacct: error: Problem talking to the database: Connection refused
Job 2596 not known (yet) by slurm; will return 'running' by default.
sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection to host:localhost:6819: Connection refused
sacct: error: Sending PersistInit msg: Connection refused
sacct: error: Problem talking to the database: Connection refused
Job 2597 not known (yet) by slurm; will return 'running' by default.
sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection to host:localhost:6819: Connection refused
sacct: error: Sending PersistInit msg: Connection refused
sacct: error: Problem talking to the database: Connection refused
Job 2596 not known (yet) by slurm; will return 'running' by default.

I would like to inquire whether you have any solutions for this situation, or if there are any command - parameter adjustments needed. Your time and assistance are greatly appreciated! I am looking forward to your reply.
Yours sincerely,
jinhua

![Image](https://github.com/user-attachments/assets/d26a41f7-cb0b-4e4d-ac1a-8f46ed35909e)

**Comment by skoren** [comment]
@jinhua2024 the issue isn't with verkko but your slurm cluster. Verkko (or more accurately snakemake) uses a polling mechanism to check job status using squeue. In your case this command keeps failing. This should be OK as long as it's transient as verkko assumes no return means the job is still running. If it never returns though verkko would be stuck waiting for a finished job. You'd have to check with your cluster manager why the squeue command is returning the error message and if they have suggestions to troubleshoot it.

**Comment by jinhua2024** [comment]
Thank you for your prompt response and clarification.
In my case, the error message keeps appearing throughout the process. I would like to ask if it is safe to continue running the pipeline and simply ignore these recurring errors. Or would these persistent errors eventually cause the pipeline to become stuck or produce unreliable results?
Your guidance on whether to proceed despite the ongoing error messages, or if further troubleshooting is necessary, would be greatly appreciated.
Thank you again for your help.

**Comment by skoren** [comment]
The error itself is OK and won't cause issues for the pipeline nor corrupt the output. Did the snakemake log show any jobs completing successfully and returning done? That would confirm it's transient and once jobs finish, your cluster is properly signaling their completion. 

If the error is persistent and never goes away it would cause the pipeline to get stuck. It would mean you'd have to kill the main verkko job and unlock the working directory (`--snakeopts --unlock`) before re-starting. It is important to make sure no jobs are running if you do that or the results could become corrupted. However, the re-launch would just get stuck again so I would suggest tracking down why squeue is failing on your system, perhaps the verkko main command which submits to the grid needs to run on a head node instead of being submitted. It's lightweight itself and doesn't do any computation when run with grid enabled.

**Comment by skoren** [comment]
Yes, that may be why squeue is failing for you but I'd confirm with your cluster administrator.

**Comment by jinhua2024** [comment]
Thank you for your guidance! I'm still having trouble resolving the issue. I plan to contact our cluster support team to see if they can provide assistance.
