### ISSUE TITLE
Consensus phase - segmentation fault

### ISSUE THREAD

**Issue by jlipovac** [marbl/verkko#94]
Hi,

I'm running verrko and in the consensus phase in the buildPackages step, I encountered a segmentation fault. Below is a printout of the buildPackages.err file:
<img width="600" alt="verkko_consensus" src="https://user-images.githubusercontent.com/43972645/182861139-0c9649ea-0c08-416e-a98c-3c4787227f26.png">

Do you have any idea what this is about?

Thanks in advance!

Josipa

**Comment by brianwalenz** [comment]
I'm going to guess there is a length zero read in there somewhere.

My seqrequester utility (https://github.com/marbl/seqrequester) will find these: `seqrequester extract -length 0 C004C_pacbio.fq.gz` or can remove them: `-length 1-9999999`.  Sadly, the seqrequester packaged with verkko 1.0 appears to be broken.

**Comment by PengjuZ** [comment]
Hi, @brianwalenz 
I also in trouble in the consensus phase at the buildPackages step with a segmentation fault.  But it's another error message.
![image](https://user-images.githubusercontent.com/109416356/183013375-1902f461-3ef0-4662-9a4d-db28f3450b68.png)

This is what causes it?
Thanks

**Comment by PengjuZ** [comment]
> Hi,
> 
> I'm running verrko and in the consensus phase in the buildPackages step, I encountered a segmentation fault. Below is a printout of the buildPackages.err file: <img alt="verkko_consensus" width="600" src="https://user-images.githubusercontent.com/43972645/182861139-0c9649ea-0c08-416e-a98c-3c4787227f26.png">
> 
> Do you have any idea what this is about?
> 
> Thanks in advance!
> 
> Josipa

Hi， Did you solve this problem ?

**Comment by jlipovac** [comment]
> > Hi,
> > I'm running verrko and in the consensus phase in the buildPackages step, I encountered a segmentation fault. Below is a printout of the buildPackages.err file: <img alt="verkko_consensus" width="600" src="https://user-images.githubusercontent.com/43972645/182861139-0c9649ea-0c08-416e-a98c-3c4787227f26.png">
> > Do you have any idea what this is about?
> > Thanks in advance!
> > Josipa
> 
> Hi， Did you solve this problem ?

Hi,

yes, with seqrequester I extracted zero length reads and that solved the problem. Thanks @brianwalenz!

**Comment by skoren** [comment]
This should be fixed by the above commit and will be in the next verkko release.
