### ISSUE TITLE
WorkflowError in v1.1: wrong type of job_id

### ISSUE THREAD

**Issue by ptrebert** [marbl/verkko#95]
Hi,
for the current bioconda v1.1 of Verkko (Snakemake 7.12.1), I get the following error when processing the test dataset:

```
WorkflowErrorin line 78 of [...]/lib/verkko/Snakefiles/c3-computeOverlaps.sm:
Resource job_id is of type str but global resource constraint defines an int with value 1. Resources with the same name need to have the same types (int, float, or str are allowed).
```
Any advice? Thanks.

+Peter

**Comment by brianwalenz** [comment]
Snakemake 7.11.0 and on detect this error; 7.10.0 seems to be immune.  I've fixed verkko to use integers for all similar resource constraints.

**Comment by ptrebert** [comment]
Indeed, I manually fixed a few dozen of these issues, and now Verkko actually starts running. Would be great to get this fix as a minor release in the near future.

**Comment by skoren** [comment]
Fixed in latest release.
