### ISSUE TITLE
what reads for trio-based phasing modue? 

### ISSUE THREAD

**Issue by PengJia6** [marbl/verkko#96]
Hi, 

I want to use the trio-based phasing modue in verkko. I have Illumina, HiFi, and ONT reads of the parents. Which technology should I choose for merqury?  Do you have any recommendations?

Best,
Peng

**Comment by skoren** [comment]
We typically use Illumina for the parents but I suspect HiFi should also work well. Make sure you build the merqury databases in homopolymer-compressed space for use with verkko.
