### ISSUE TITLE
compressedSequences[realUnitig].get(realOff) == compressed' failed

### ISSUE THREAD

**Issue by xfcypeng** [marbl/verkko#97]
Hi,

running the Verkko 1.0 release version (via bioconda) results in this error for a human female sample:
......
MBG: src/ConsensusMaker.h:65: void ConsensusMaker::addStrings(size_t, size_t, size_t, F) [with F = addCounts(ConsensusMaker&, const SequenceCharType&, const SequenceLengthType&, const string&, size_t, size_t, size_t, size_t, size_t, bool)::<lambda(size_t)>; size_t = long unsigned int]: Assertion `compressedSequences[realUnitig].get(realOff) == 0 || compressedSequences[realUnitig].get(realOff) == compressed' failed.

I can share data for debugging if needed.

Best,
Peng

**Comment by skoren** [comment]
This seems the same error as #83. Can you check your `hifi-corrected.fasta.gz` for duplicate reads as well as your input HiFi data for duplicates.

**Comment by skoren** [comment]
Any update, were you able to check for duplicated reads?

**Comment by skoren** [comment]
Idle, likely same as #83 so will keep that issue open. Still looking for a test set where the corrected reads have a duplicated ID, ideally along with the input data so we can see if this is being introduced during the run or was in the input originally.
