### ISSUE TITLE
OSError: [Errno 5] Input/output error: '../6-layoutContigs/unitig-popped.layout'

### ISSUE THREAD

**Issue by xfcypeng** [marbl/verkko#98]
Hi,
..............
File "/home/cypeng/anaconda3/envs/verkko/lib/verkko/scripts/get_layout_from_mbg.py", line 417, in <module>
    tig_layout_file = open(f"{layout_output}", mode="w")
OSError: [Errno 5] Input/output error: '../6-layoutContigs/unitig-popped.layout'

Best,
Peng

**Comment by brianwalenz** [comment]
I/O errors are generally errors at the file system level and not something caused by the application program itself.  Check that the device isn't full or quota exceeded, file permissions, etc.  I see mentions of NFS file locking when I google the error.  Ask your sysadmin for advice.

**Comment by skoren** [comment]
Idle, looks like OS/system issue not verkko.
